# Generated by Django 4.0.1 on 2024-08-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_branch_modified_date_and_more'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('error', models.BooleanField(default=False)),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
