# Generated by Django 4.0.1 on 2024-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_tasklogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
