# Generated by Django 4.0.1 on 2024-08-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogs',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.task'),
        ),
    ]
