# Generated by Django 4.0.1 on 2024-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_tasklogs_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('version_type', models.CharField(blank=True, max_length=50, null=True)),
                ('isDeprecated', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='patches/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tasklogs',
            options={'ordering': ['-created_date']},
        ),
    ]
