# Generated by Django 4.0.1 on 2024-10-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_versionhelper_alter_tasklogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='domain_name',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
    ]
