# Generated by Django 4.0.1 on 2024-10-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_task_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='application',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('CLOUD', 'CLOUD')], default='LOCAL', max_length=200),
        ),
    ]
