# Generated by Django 4.0.1 on 2024-10-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_task_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_domain_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='domain_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
