# Generated by Django 4.0.1 on 2024-10-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_task_client_domain_name_alter_task_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='db_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
