from importlib.resources import contents
from multiprocessing import context
from urllib import response
import os
from pathlib import Path

from django.shortcuts import render
import datetime


def vendor_adavnce_data(vendor_advance_response):
    vendor_advance_response = vendor_advance_response
    vendor_advance= {
        "va_id": "866dd299-644b-4180-9a25-a077a5640044",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-04-28T12:04:47.764037+05:30",
        "modified_id": "None",
        "modified_date": "2022-04-28T12:04:47.764037+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-04-28T12:04:47.764037+05:30",
        "is_vendor_advance_generated": True,
        "status": "Manually Added",
        "gst_treatment": None,
        "payment_serial": "Pay123",
        "vendor_gstin": None,
        "source_place": None,
        "destination_place": None,
        "amount": "2000.00",
        "vendor_advance_date": "2022-04-28",
        "vendor_advance_ref_no": None,
        "deposit_to": "None",
        "paid_via": "Cash",
        "description": None,
        "description_supply": None,
        "tax_rate": "0.00",
        "tax_name": None,
        "tax_type": None,
        "balance_amount": "2000.00",
        "tax_amount": "0.00",
        "reverse_charge": False,
        "attach_file": "https://products.coderize.in:8002/media/None",
        "tds_amount": "0.00",
        "is_bank_transaction": True,
        "company_id": {
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "created_id": "None",
            "created_date": "2022-04-27T17:32:44.842193+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:32:44.842193+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:32:44.842193+05:30",
            "trial_company": None,
            "company_name": "CodeRize Technologies Pune",
            "alias_name": "",
            "address": "Pune",
            "locality": "",
            "landmark": "",
            "pincode": 422064,
            "city": "",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "",
            "primary_mobile_number": "995656656566",
            "primary_alternate_number": "",
            "primary_email": "coderize@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "",
            "website": "",
            "books_start_date": "2022-04-01",
            "method": "None",
            "company_type": "Private",
            "pan_number": "CODE121212",
            "gstin": "",
            "cin": "",
            "other_registration_number": "",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "https://products.coderize.in:8002/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "bank_id": {
            "bank_id": "209ee4ef-3f1b-4820-9643-79e1496d4b68",
            "created_id": "None",
            "created_date": "2022-04-27T17:38:53.246756+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:38:53.246756+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:38:53.246756+05:30",
            "account_code": "",
            "account_number": "",
            "account_name": "Test Bank",
            "account_type": "Bank",
            "bank_name": "Test bank",
            "description": "",
            "status": "None",
            "ifsc_code": "",
            "coa_id": "c3e09a9b-1686-4fee-b5ad-0398971eaa96",
            "branch_id": None,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538"
        },
        "coa_id": None,
        "vendor_id": {
            "vendor_id": "0f717183-4700-4702-bac0-90714005e370",
            "created_id": "None",
            "created_date": "2022-04-27T17:37:40.051177+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:37:40.051177+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:37:40.051177+05:30",
            "salutation": None,
            "vendor_name": "Sham Satpute",
            "vendor_mobile": "889955565656",
            "vendor_display_name": "Sham",
            "vendor_contact": "",
            "vendor_email": "sham@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "Due on Receipt",
            "no_of_days": 0,
            "set_credit_limit": "0.00",
            "gst_treatment": "Registered Business - Regular",
            "gstin_number": "SHAM@1223",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "SHAM@1223",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Maharashtra",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        },
        "tds_id": None
    }

   
       
    contents={

        "company_name":vendor_advance_response['company_id']['company_name'],
        "address":vendor_advance_response['company_id']['address'],
        "city":vendor_advance_response['company_id']['city'],
        "gst_in":vendor_advance_response['company_id']['gstin'],
        "vendor_advance_date":vendor_advance_response['vendor_advance_date'],
      #  "credit_date":datetime.datetime.strptime(customer_advance_response['ca_date'], "%Y-%m-%dT%H:%M:%S%z").date(),     
        "paid_via":vendor_advance_response['paid_via'],   
        "total_in_words":'',
        "vendor_name":vendor_advance_response['vendor_id']['vendor_name'],
        "description_supply":vendor_advance_response['description_supply'], 
        "vendor_advance_ref_no":  vendor_advance_response['vendor_advance_ref_no'],
        "place_of_supply":vendor_advance_response['destination_place'],
        "cgst_amount":vendor_advance_response['cgst_amount'],
        "sgst_amount": vendor_advance_response['sgst_amount'],
        "igst_amount": vendor_advance_response['igst_amount'],
        "balance_amount":vendor_advance_response['balance_amount'],
        "payment_serial":vendor_advance_response['payment_serial'],
        "tds_amount":vendor_advance_response['tds_amount'],
       
    }
    print(contents)
    return contents






if __name__ == '__main__':
    va_Response={
        "va_id": "866dd299-644b-4180-9a25-a077a5640044",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-04-28T12:04:47.764037+05:30",
        "modified_id": "None",
        "modified_date": "2022-04-28T12:04:47.764037+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-04-28T12:04:47.764037+05:30",
        "is_vendor_advance_generated": True,
        "status": "Manually Added",
        "gst_treatment": None,
        "payment_serial": "Pay123",
        "vendor_gstin": None,
        "source_place": None,
        "destination_place": None,
        "amount": "2000.00",
        "vendor_advance_date": "2022-04-28",
        "vendor_advance_ref_no": None,
        "deposit_to": "None",
        "paid_via": "Cash",
        "description": None,
        "description_supply": None,
        "tax_rate": "0.00",
        "tax_name": None,
        "tax_type": None,
        "balance_amount": "2000.00",
        "tax_amount": "0.00",
        "reverse_charge": False,
        "attach_file": "https://products.coderize.in:8002/media/None",
        "tds_amount": "0.00",
        "is_bank_transaction": True,
        "company_id": {
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "created_id": "None",
            "created_date": "2022-04-27T17:32:44.842193+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:32:44.842193+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:32:44.842193+05:30",
            "trial_company": None,
            "company_name": "CodeRize Technologies Pune",
            "alias_name": "",
            "address": "Pune",
            "locality": "",
            "landmark": "",
            "pincode": 422064,
            "city": "",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "",
            "primary_mobile_number": "995656656566",
            "primary_alternate_number": "",
            "primary_email": "coderize@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "",
            "website": "",
            "books_start_date": "2022-04-01",
            "method": "None",
            "company_type": "Private",
            "pan_number": "CODE121212",
            "gstin": "",
            "cin": "",
            "other_registration_number": "",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "https://products.coderize.in:8002/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "bank_id": {
            "bank_id": "209ee4ef-3f1b-4820-9643-79e1496d4b68",
            "created_id": "None",
            "created_date": "2022-04-27T17:38:53.246756+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:38:53.246756+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:38:53.246756+05:30",
            "account_code": "",
            "account_number": "",
            "account_name": "Test Bank",
            "account_type": "Bank",
            "bank_name": "Test bank",
            "description": "",
            "status": "None",
            "ifsc_code": "",
            "coa_id": "c3e09a9b-1686-4fee-b5ad-0398971eaa96",
            "branch_id": None,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538"
        },
        "coa_id": None,
        "vendor_id": {
            "vendor_id": "0f717183-4700-4702-bac0-90714005e370",
            "created_id": "None",
            "created_date": "2022-04-27T17:37:40.051177+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:37:40.051177+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:37:40.051177+05:30",
            "salutation": None,
            "vendor_name": "Sham Satpute",
            "vendor_mobile": "889955565656",
            "vendor_display_name": "Sham",
            "vendor_contact": "",
            "vendor_email": "sham@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "Due on Receipt",
            "no_of_days": 0,
            "set_credit_limit": "0.00",
            "gst_treatment": "Registered Business - Regular",
            "gstin_number": "SHAM@1223",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "SHAM@1223",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Maharashtra",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        },
        "tds_id": None
    }

    a = vendor_adavnce_data(va_Response)
    #print(a)


def generate_vendor_advance_pdf(data,output_path):
    # first dict data give in y object
  #  y=invoice_data(data)
    # second dict data give in x object
    x = vendor_adavnce_data(data)
    # use update method to combine both dictionaries
    # here we use update method to give x dict data in y
   # y.update(x)
    # and here y is passed as a parameter to the render function context=y
    html = render(None, "core/vendor_advance.html", x)
    return html