from templates.img_conversion import image_url_to_base64
from django.shortcuts import render

import datetime

def bill_data(bill_response):
    bill_response = bill_response[0]
    bill_response_sadfsa=[ {
        "bill_id": "f24169f5-cdd2-4a6b-ab27-f3ddfae94ebe",
        "bill_items": [
            {
                "bill_id": {
                    "bill_id": "f24169f5-cdd2-4a6b-ab27-f3ddfae94ebe",
                    "cgst_total": "0.00",
                    "sgst_total": "0.00",
                    "igst_total": "0.00",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-04T17:52:14.899535+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-04T17:52:14.899535+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-04T17:52:14.899535+05:30",
                    "is_bill_generate": True,
                    "bill_status": "Save and Send",
                    "payment_status": "unpaid",
                    "bill_serial": "10",
                    "bill_ref_no": "None",
                    "order_no": "15",
                    "bill_date": "2022-03-04",
                    "due_date": "2022-03-19",
                    "discount_type": "Transaction level",
                    "tax_Type": "TDS",
                    "amount_due": "4980.00",
                    "supply_place": "Gujarat",
                    "sub_total": "5000.00",
                    "total": "4980.00",
                    "total_gst": None,
                    "notes": "credit note",
                    "tcs_amount": "0.00",
                    "tds_amount": "0.00",
                    "total_quantity": "0.00",
                    "entered_discount": "20.00",
                    "discount_account": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "discount": "20.00",
                    "terms_condition": "None",
                    "term_name": "cash on delivery",
                    "no_of_days": "15.00",
                    "shipping_charges": None,
                    "packing_charges": None,
                    "adjustment": None,
                    "select_tax": "None",
                    "attach_file": None,
                    "OpenAmount": None,
                    "AmountIncludesVAT": "None",
                    "convt_type": "None",
                    "convt_id": "None",
                    "convt_serial": "None",
                    "convt_ref_no": "None",
                    "is_converted": False,
                    "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "tcs_id": None,
                    "tds_id": None
                },
                "billitem_id": "26a71a40-b6e7-407c-acfc-8d80ac6f1896",
                "vendor_id": None,
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "customer_id": None,
                "item_name": "Test1",
                "amount": "5000.00",
                "discount": "0.00",
                "quantity": 1,
                "rate": "5000.00",
                "taxamount": None,
                "tax_name": None,
                "sgst_amount": "0.00",
                "cgst_amount": "0.00",
                "igst_amount": "0.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-03-04T17:52:14.899535+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-04T17:52:14.899535+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-04T17:52:14.899535+05:30",
        "is_bill_generate": True,
        "bill_status": "Save and Send",
        "payment_status": "unpaid",
        "bill_serial": "10",
        "bill_ref_no": "None",
        "order_no": "15",
        "bill_date": "2022-03-04",
        "due_date": "2022-03-19",
        "discount_type": "Transaction level",
        "tax_Type": "TDS",
        "amount_due": "4980.00",
        "supply_place": "Gujarat",
        "sub_total": "5000.00",
        "total": "4980.00",
        "total_gst": None,
        "notes": "credit note",
        "tcs_amount": "0.00",
        "tds_amount": "0.00",
        "total_quantity": "0.00",
        "entered_discount": "20.00",
        "discount_account": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
        "discount": "20.00",
        "terms_condition": "None",
        "term_name": "cash on delivery",
        "no_of_days": "15.00",
        "shipping_charges": None,
        "packing_charges": None,
        "adjustment": None,
        "select_tax": "None",
        "attach_file": None,
        "OpenAmount": None,
        "AmountIncludesVAT": "None",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "is_converted": False,
        "vendor_id": {
            "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
            "created_id": "None",
            "created_date": "2022-03-04T17:51:08.904962+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-04T17:51:08.904962+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-04T17:51:08.904962+05:30",
            "salutation": None,
            "vendor_name": "Test",
            "vendor_mobile": "09822607468",
            "vendor_display_name": "test display",
            "vendor_contact": "09822607468",
            "vendor_email": "gayatrireddy800@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "test technology",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "cash on delivery",
            "no_of_days": 15,
            "set_credit_limit": "0.00",
            "gst_treatment": "Registered Business - Composition",
            "gstin_number": "GN156489",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "GN156489",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Karnataka",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "tcs_id": None,
        "tds_id": None
    }
]

    contents={
        "company_name":bill_response['company_id']['company_name'],
        "address":bill_response['company_id']['address'],
        "city":bill_response['company_id']['city'],
        "gst_in":bill_response['company_id']['gstin'],
        "bill_serial":bill_response['bill_serial'],
        "bill_date":datetime.datetime.strptime(bill_response['bill_date'], "%Y-%m-%d").date(),
        "due_date":bill_response["due_date"],
        "place_of_supply":bill_response['supply_place'],
        'bill_items': [dict(a) for a in bill_response['bill_items']],
        
       
        "sub_total":bill_response['sub_total'],
        "term_name":bill_response['term_name'],
        "discount":bill_response['discount'],
        "total_in_words":'',
        "cgst_0":'',
        "itemdescription":'',
        "sgst0_0":'',

        "cgst_total":bill_response['cgst_total'],
        "sgst_total":bill_response['sgst_total'],
        "igst_total": bill_response['igst_total'],
        "tcs":bill_response['tcs_amount'],
        "cgst25_25":'',
        "sgst25_25":'',
        "cgst6_6":'',
        "sgst6_6":'',
        "cgst9_9":'',
        "sgst9_9":bill_response['sgst_total'],
        "shipping_charges":bill_response['shipping_charges'],
        "total":bill_response['total'],
        "credit_remaining":'',
        "customer_name":bill_response['vendor_id']['vendor_name'],
    }
    print(contents)
    return contents














if __name__ == '__main__':
    bill_Response=[ {
        "bill_id": "f24169f5-cdd2-4a6b-ab27-f3ddfae94ebe",
        "bill_items": [
            {
                "bill_id": {
                    "bill_id": "f24169f5-cdd2-4a6b-ab27-f3ddfae94ebe",
                    "cgst_total": "0.00",
                    "sgst_total": "0.00",
                    "igst_total": "0.00",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-04T17:52:14.899535+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-04T17:52:14.899535+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-04T17:52:14.899535+05:30",
                    "is_bill_generate": True,
                    "bill_status": "Save and Send",
                    "payment_status": "unpaid",
                    "bill_serial": "10",
                    "bill_ref_no": "None",
                    "order_no": "15",
                    "bill_date": "2022-03-04",
                    "due_date": "2022-03-19",
                    "discount_type": "Transaction level",
                    "tax_Type": "TDS",
                    "amount_due": "4980.00",
                    "supply_place": "Gujarat",
                    "sub_total": "5000.00",
                    "total": "4980.00",
                    "total_gst": None,
                    "notes": "credit note",
                    "tcs_amount": "0.00",
                    "tds_amount": "0.00",
                    "total_quantity": "0.00",
                    "entered_discount": "20.00",
                    "discount_account": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "discount": "20.00",
                    "terms_condition": "None",
                    "term_name": "cash on delivery",
                    "no_of_days": "15.00",
                    "shipping_charges": None,
                    "packing_charges": None,
                    "adjustment": None,
                    "select_tax": "None",
                    "attach_file": None,
                    "OpenAmount": None,
                    "AmountIncludesVAT": "None",
                    "convt_type": "None",
                    "convt_id": "None",
                    "convt_serial": "None",
                    "convt_ref_no": "None",
                    "is_converted": False,
                    "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "tcs_id": None,
                    "tds_id": None
                },
                "billitem_id": "26a71a40-b6e7-407c-acfc-8d80ac6f1896",
                "vendor_id": None,
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "customer_id": None,
                "item_name": "Test1",
                "amount": "5000.00",
                "discount": "0.00",
                "quantity": 1,
                "rate": "5000.00",
                "taxamount": None,
                "tax_name": None,
                "sgst_amount": "0.00",
                "cgst_amount": "0.00",
                "igst_amount": "0.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-03-04T17:52:14.899535+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-04T17:52:14.899535+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-04T17:52:14.899535+05:30",
        "is_bill_generate": True,
        "bill_status": "Save and Send",
        "payment_status": "unpaid",
        "bill_serial": "10",
        "bill_ref_no": "None",
        "order_no": "15",
        "bill_date": "2022-03-04",
        "due_date": "2022-03-19",
        "discount_type": "Transaction level",
        "tax_Type": "TDS",
        "amount_due": "4980.00",
        "supply_place": "Gujarat",
        "sub_total": "5000.00",
        "total": "4980.00",
        "total_gst": None,
        "notes": "credit note",
        "tcs_amount": "0.00",
        "tds_amount": "0.00",
        "total_quantity": "0.00",
        "entered_discount": "20.00",
        "discount_account": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
        "discount": "20.00",
        "terms_condition": "None",
        "term_name": "cash on delivery",
        "no_of_days": "15.00",
        "shipping_charges": None,
        "packing_charges": None,
        "adjustment": None,
        "select_tax": "None",
        "attach_file": None,
        "OpenAmount": None,
        "AmountIncludesVAT": "None",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "is_converted": False,
        "vendor_id": {
            "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
            "created_id": "None",
            "created_date": "2022-03-04T17:51:08.904962+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-04T17:51:08.904962+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-04T17:51:08.904962+05:30",
            "salutation": None,
            "vendor_name": "Test",
            "vendor_mobile": "09822607468",
            "vendor_display_name": "test display",
            "vendor_contact": "09822607468",
            "vendor_email": "gayatrireddy800@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "test technology",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "cash on delivery",
            "no_of_days": 15,
            "set_credit_limit": "0.00",
            "gst_treatment": "Registered Business - Composition",
            "gstin_number": "GN156489",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "GN156489",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Karnataka",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "tcs_id": None,
        "tds_id": None
    }
]
    a = bill_data(bill_Response)
    print(a)


# api to generate credit note pdf
def generate_bill_pdf(data, output_path):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html = render(None, "core/bill.html",data)
    return html
    # config = pdfkit.configuration(
    #         wkhtmltopdf=os.path.join(Path(__file__).parent.parent.parent, r'wkhtmltox\bin\wkhtmltopdf.exe'))
    # pdfkit.from_string(html.content.decode(), output_path, configuration=config)
    # return output_path