from templates.img_conversion import image_url_to_base64
from django.shortcuts import render
import datetime

def dn_data(dn_response):
    dn_response = dn_response[0]


    contents={
        "company_name":dn_response['company_id']['company_name'],
        "address":dn_response['company_id']['address'],
        "city":dn_response['company_id']['city'],
        "gst_in":dn_response['company_id']['gstin'],
        "dn_serial":dn_response['dn_serial'],
#        "due_date":dn_response['due_date'],
 #       "terms":dn_response['term_name'],
        "dn_date":datetime.datetime.strptime(dn_response['dn_date'], "%Y-%m-%dT%H:%M:%S%z").date(),
        "source_place":dn_response['source_place'],
        #here we send a list in invoice items 
        #and convert a order dict into dict
        'debit_note_items': [dict(a) for a in dn_response['debit_note_items']],
        "sub_total":dn_response['sub_total'],
        "cgst_total":dn_response['cgst_total'],
        "sgst_total":dn_response['sgst_total'],
        "igst_total":dn_response['igst_total'],
        "discount":dn_response['discount'],       
     #   "shipping_charges":dn_response['shipping_charges'],
        "total":dn_response['total'],
        "credit_remaining":dn_response['total'],
        #"customer_note":dn_response['customer_note'],
        "customer_name":dn_response['vendor_id']['vendor_name'],
    
    }

    print(" CONTENTS               @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@2",contents)
    return contents





if __name__ == '__main__':
    dn_Response=[
    {
        "dn_id": "bf49309c-850d-4765-8b22-7cc7058caac9",
        "debit_note_items": [
            {
                "dn_id": {
                    "dn_id": "bf49309c-850d-4765-8b22-7cc7058caac9",
                    "cgst_total": "300.00",
                    "sgst_total": "300.00",
                    "igst_total": "0.00",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-07T09:08:41.282798+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-07T09:08:41.282798+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-07T09:08:41.282798+05:30",
                    "source_place": "Maharashtra",
                    "supply_destination": "Maharashtra",
                    "bill_serial": None,
                    "bill_type": None,
                    "order_no": None,
                    "dn_date": "2022-03-07T00:00:00+05:30",
                    "discount": "555.00",
                    "entered_discount": "555.00",
                    "sub_total": "5000.00",
                    "total": "5045.00",
                    "balance_amount": "5045.00",
                    "total_gst": None,
                    "terms_condition": "None",
                    "note": "",
                    "status": "Open",
                    "is_dn_converted": False,
                    "is_dn_generated": True,
                    "dn_status": "Save as Open",
                    "dn_serial": "DN1234",
                    "dn_ref_no": "None",
                    "convt_type": "None",
                    "convt_id": "None",
                    "convt_serial": "None",
                    "convt_ref_no": "None",
                    "attach_file": "/media/None",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "vendor_id": "0b2382e1-ae2a-463d-a66e-3dab1738d857",
                    "item_id": None
                },
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "dnitem_id": "05b7d81f-a2ea-4f53-85d0-54e47683b6f2",
                "item_name": "Test1",
                "amount": "5000.00",
                "quantity": "1.00",
                "rate": "5000.00",
                "tax_name": "GST12 [12%]",
                "taxamount": None,
                "cgst_amount": "300.00",
                "sgst_amount": "300.00",
                "igst_amount": "600.00"
            }
        ],
        "cgst_total": "300.00",
        "sgst_total": "300.00",
        "igst_total": "0.00",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-03-07T09:08:41.282798+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-07T09:08:41.282798+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-07T09:08:41.282798+05:30",
        "source_place": "Maharashtra",
        "supply_destination": "Maharashtra",
        "bill_serial": None,
        "bill_type": None,
        "order_no": None,
        "dn_date": "2022-03-07T00:00:00+05:30",
        "discount": "555.00",
        "entered_discount": "555.00",
        "sub_total": "5000.00",
        "total": "5045.00",
        "balance_amount": "5045.00",
        "total_gst": None,
        "terms_condition": "None",
        "note": "",
        "status": "Open",
        "is_dn_converted": False,
        "is_dn_generated": True,
        "dn_status": "Save as Open",
        "dn_serial": "DN1234",
        "dn_ref_no": "None",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "attach_file": "/media/None",
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "vendor_id": {
            "vendor_id": "0b2382e1-ae2a-463d-a66e-3dab1738d857",
            "created_id": "None",
            "created_date": "2022-03-07T08:07:08.572887+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-07T08:07:08.572887+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-07T08:07:08.572887+05:30",
            "salutation": "Mrs.",
            "vendor_name": "Test1",
            "vendor_mobile": "555655655656",
            "vendor_display_name": "test",
            "vendor_contact": "",
            "vendor_email": "test@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "Due on Receipt",
            "no_of_days": 0,
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Maharashtra",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "item_id": None
    }
]
    a = dn_data(dn_Response)


# debit note item and debit note join
# API POST for poitem
# api to generate credit note pdf
def generate_dn_pdf(data):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html =  render(None, "core/dn.html",data)
    return html
