from django.shortcuts import render
from templates.img_conversion import image_url_to_base64
def exp_data(exp_response):
    exp_response = exp_response[0]

    exp_response_sadfs=[
    {
        "er_id": "cfd18c2b-3d0f-486d-90e0-787ac89f92e4",
        "expense_transactions": [
            {
                "expensejt_id": "a1b83b02-79c3-4eff-b8cd-1640625b50dc",
                "created_id": "None",
                "created_date": "2022-03-06T22:55:31.268713+05:30",
                "modified_id": "None",
                "modified_date": "2022-03-06T22:55:31.268713+05:30",
                "deleted_id": "None",
                "deleted_date": "2022-03-06T22:55:31.268713+05:30",
                "transaction_type": "Expence Payment",
                "date": "2022-03-06",
                "type": "Debit",
                "debit": "50000.00",
                "credit": "0.00",
                "er_id": {
                    "er_id": "cfd18c2b-3d0f-486d-90e0-787ac89f92e4",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "2500.00",
                    "expense_date": "2022-03-06T00:00:00+05:30",
                    "expense_account": "None",
                    "expense_type": "Services",
                    "expense_serial": "1245",
                    "expense_ref_no": "None",
                    "invoice_serial": None,
                    "expense_status": "Non-Billable",
                    "is_expense_generated": True,
                    "paid_through": "8fe7d475-dca5-43fc-96ac-58b0edbfa190",
                    "notes": "",
                    "gst_treatment": "Non-GST Supply",
                    "vendor_gstin": "",
                    "supply_place": "West Bengal",
                    "destination_place": "Maharashtra",
                    "attach_file": None,
                    "reporting_tag": "None",
                    "account": "None",
                    "sales_tax": "0.00",
                    "total_amount": "0.00",
                    "item_details": "None",
                    "quantity": "0.00",
                    "rate": "0.00",
                    "customer_details": "None",
                    "discount": "0.00",
                    "amount": "50000.00",
                    "tax": None,
                    "expense_total": "50000.00",
                    "status": "None",
                    "sac": "",
                    "hsn_code": "",
                    "tax_rate": "5.00",
                    "tax_name": "IGST5 [5%]",
                    "tax_type": "single",
                    "tax_amount": "0.00",
                    "tax_percentage": "5.00",
                    "invoice_id": None,
                    "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
                    "customer_id": "27c60af3-975a-42d5-8ff1-c010f1135459",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "bank_id": None,
                    "branch_id": None,
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c"
                },
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "company_id": {
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "created_id": "None",
                    "created_date": "2022-03-03T12:15:37.699309+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T12:15:37.699309+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T12:15:37.699309+05:30",
                    "trial_company": None,
                    "company_name": "coderize",
                    "alias_name": "abc",
                    "address": "Balaji heights, near bank of maharashtra, Narhe",
                    "locality": "pune",
                    "landmark": "balaji nagar",
                    "pincode": 411041,
                    "city": "Pune",
                    "state": "Maharashtra",
                    "other": "",
                    "is_primary": True,
                    "primary_phone_number": "09822607468",
                    "primary_mobile_number": "5655254554",
                    "primary_alternate_number": "9875631489",
                    "primary_email": "gayatrireddy800@gmail.com",
                    "secondary_phone_number": "",
                    "secondary_mobile_number": "",
                    "secondary_alternate_number": "",
                    "secondary_email": "gayatrireddy800@gmail.com",
                    "website": "",
                    "books_start_date": "2022-03-03",
                    "method": "None",
                    "company_type": "Government",
                    "pan_number": "5648796445",
                    "gstin": "5489863266",
                    "cin": "269655663",
                    "other_registration_number": "it",
                    "password": "584587587",
                    "security_control": "False",
                    "audit_feature": "True",
                    "logo_image": "/media/None",
                    "report_basis": "None",
                    "company_edit_id": "None",
                    "tax_edit_id": "None",
                    "separate_payment_address": "False",
                    "address_receive_payment": "None"
                },
                "branch_id": None,
                "vendor_id": {
                    "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
                    "created_id": "None",
                    "created_date": "2022-03-04T17:51:08.904962+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-04T17:51:08.904962+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-04T17:51:08.904962+05:30",
                    "salutation": None,
                    "vendor_name": "Test",
                    "vendor_mobile": "09822607468",
                    "vendor_display_name": "test display",
                    "vendor_contact": "09822607468",
                    "vendor_email": "gayatrireddy800@gmail.com",
                    "vendor_type": "None",
                    "vendor_designation": "",
                    "vendor_department": "",
                    "parent_vendor": "None",
                    "enable_portal": False,
                    "company_name": "test technology",
                    "company_display_name": "None",
                    "company_email": "None",
                    "company_number": "None",
                    "website": "",
                    "opening_balance": None,
                    "currency": "None",
                    "payment_terms": "None",
                    "term_name": "cash on delivery",
                    "no_of_days": 15,
                    "set_credit_limit": "0.00",
                    "gst_treatment": "Registered Business - Composition",
                    "gstin_number": "GN156489",
                    "tax_preference": "Taxable",
                    "tds": "None",
                    "cin_number": "None",
                    "trn_number": "None",
                    "vat_number": "None",
                    "pan_number": "GN156489",
                    "b_attention": "",
                    "bill_address1": "",
                    "bill_address2": "",
                    "bill_address_city": "",
                    "bill_address_state": "",
                    "bill_address_postal_code": 0,
                    "bill_address_country": "",
                    "bill_contact_number": "",
                    "bill_fax_number": "",
                    "s_attention": "",
                    "ship_address1": "",
                    "ship_address2": "",
                    "ship_address_city": "",
                    "ship_address_state": "",
                    "ship_address_postal_code": 0,
                    "ship_address_country": "",
                    "ship_contact_number": "",
                    "ship_fax_number": "",
                    "source_place": "Karnataka",
                    "tax_prefrances": "None",
                    "exemption_reason": "",
                    "remarks": "",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                }
            }
]  
    }  
    ]
    contents={
             'expense_transactions': [dict(a) for a in exp_response['expense_transactions']],
            # "expense_date":exp_response['expense_transactions'][0]['er_id']['expense_date'],
            # "expense_serial":exp_response['expense_transactions'][0]['er_id']['expense_serial'],
            # "expense_ref_no":exp_response['expense_transactions'][0]['er_id']['expense_ref_no'],
            # "paid_through":exp_response['expense_transactions'][0]['er_id']['paid_through'],
            # "supply_place":exp_response['expense_transactions'][0]['er_id']['supply_place'],
            # "destination_place":exp_response['expense_transactions'][0]['er_id']['destination_place'], 
            # "expense_total":exp_response['expense_transactions'][0]['er_id']['expense_total'],  
            # "vendor_name":exp_response['expense_transactions'][0]['vendor_id']['vendor_name'],
            # "amount":exp_response['expense_transactions'][0]['er_id']['amount'],
    }
    print("-------------------------",contents)
    return contents

if __name__ == '__main__':
    Exp_Response=[
    {
        "er_id": "cfd18c2b-3d0f-486d-90e0-787ac89f92e4",
        "expense_transactions": [
            {
                "expensejt_id": "a1b83b02-79c3-4eff-b8cd-1640625b50dc",
                "created_id": "None",
                "created_date": "2022-03-06T22:55:31.268713+05:30",
                "modified_id": "None",
                "modified_date": "2022-03-06T22:55:31.268713+05:30",
                "deleted_id": "None",
                "deleted_date": "2022-03-06T22:55:31.268713+05:30",
                "transaction_type": "Expence Payment",
                "date": "2022-03-06",
                "type": "Debit",
                "debit": "50000.00",
                "credit": "0.00",
                "er_id": {
                    "er_id": "cfd18c2b-3d0f-486d-90e0-787ac89f92e4",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "2500.00",
                    "expense_date": "2022-03-06T00:00:00+05:30",
                    "expense_account": "None",
                    "expense_type": "Services",
                    "expense_serial": "1245",
                    "expense_ref_no": "None",
                    "invoice_serial": None,
                    "expense_status": "Non-Billable",
                    "is_expense_generated": True,
                    "paid_through": "8fe7d475-dca5-43fc-96ac-58b0edbfa190",
                    "notes": "",
                    "gst_treatment": "Non-GST Supply",
                    "vendor_gstin": "",
                    "supply_place": "West Bengal",
                    "destination_place": "Maharashtra",
                    "attach_file": None,
                    "reporting_tag": "None",
                    "account": "None",
                    "sales_tax": "0.00",
                    "total_amount": "0.00",
                    "item_details": "None",
                    "quantity": "0.00",
                    "rate": "0.00",
                    "customer_details": "None",
                    "discount": "0.00",
                    "amount": "50000.00",
                    "tax": None,
                    "expense_total": "50000.00",
                    "status": "None",
                    "sac": "",
                    "hsn_code": "",
                    "tax_rate": "5.00",
                    "tax_name": "IGST5 [5%]",
                    "tax_type": "single",
                    "tax_amount": "0.00",
                    "tax_percentage": "5.00",
                    "invoice_id": None,
                    "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
                    "customer_id": "27c60af3-975a-42d5-8ff1-c010f1135459",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "bank_id": None,
                    "branch_id": None,
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c"
                },
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "company_id": {
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "created_id": "None",
                    "created_date": "2022-03-03T12:15:37.699309+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T12:15:37.699309+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T12:15:37.699309+05:30",
                    "trial_company": None,
                    "company_name": "coderize",
                    "alias_name": "abc",
                    "address": "Balaji heights, near bank of maharashtra, Narhe",
                    "locality": "pune",
                    "landmark": "balaji nagar",
                    "pincode": 411041,
                    "city": "Pune",
                    "state": "Maharashtra",
                    "other": "",
                    "is_primary": True,
                    "primary_phone_number": "09822607468",
                    "primary_mobile_number": "5655254554",
                    "primary_alternate_number": "9875631489",
                    "primary_email": "gayatrireddy800@gmail.com",
                    "secondary_phone_number": "",
                    "secondary_mobile_number": "",
                    "secondary_alternate_number": "",
                    "secondary_email": "gayatrireddy800@gmail.com",
                    "website": "",
                    "books_start_date": "2022-03-03",
                    "method": "None",
                    "company_type": "Government",
                    "pan_number": "5648796445",
                    "gstin": "5489863266",
                    "cin": "269655663",
                    "other_registration_number": "it",
                    "password": "584587587",
                    "security_control": "False",
                    "audit_feature": "True",
                    "logo_image": "/media/None",
                    "report_basis": "None",
                    "company_edit_id": "None",
                    "tax_edit_id": "None",
                    "separate_payment_address": "False",
                    "address_receive_payment": "None"
                },
                "branch_id": None,
                "vendor_id": {
                    "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
                    "created_id": "None",
                    "created_date": "2022-03-04T17:51:08.904962+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-04T17:51:08.904962+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-04T17:51:08.904962+05:30",
                    "salutation": None,
                    "vendor_name": "Test",
                    "vendor_mobile": "09822607468",
                    "vendor_display_name": "test display",
                    "vendor_contact": "09822607468",
                    "vendor_email": "gayatrireddy800@gmail.com",
                    "vendor_type": "None",
                    "vendor_designation": "",
                    "vendor_department": "",
                    "parent_vendor": "None",
                    "enable_portal": False,
                    "company_name": "test technology",
                    "company_display_name": "None",
                    "company_email": "None",
                    "company_number": "None",
                    "website": "",
                    "opening_balance": None,
                    "currency": "None",
                    "payment_terms": "None",
                    "term_name": "cash on delivery",
                    "no_of_days": 15,
                    "set_credit_limit": "0.00",
                    "gst_treatment": "Registered Business - Composition",
                    "gstin_number": "GN156489",
                    "tax_preference": "Taxable",
                    "tds": "None",
                    "cin_number": "None",
                    "trn_number": "None",
                    "vat_number": "None",
                    "pan_number": "GN156489",
                    "b_attention": "",
                    "bill_address1": "",
                    "bill_address2": "",
                    "bill_address_city": "",
                    "bill_address_state": "",
                    "bill_address_postal_code": 0,
                    "bill_address_country": "",
                    "bill_contact_number": "",
                    "bill_fax_number": "",
                    "s_attention": "",
                    "ship_address1": "",
                    "ship_address2": "",
                    "ship_address_city": "",
                    "ship_address_state": "",
                    "ship_address_postal_code": 0,
                    "ship_address_country": "",
                    "ship_contact_number": "",
                    "ship_fax_number": "",
                    "source_place": "Karnataka",
                    "tax_prefrances": "None",
                    "exemption_reason": "",
                    "remarks": "",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                }
            }
]  
    }  
    ] 
    a = exp_data(Exp_Response)
    print(a)

# get expense record byid
# get expense transaction by pr id
def generate_expense_pdf(data):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html =  render(None, "core/exp.html",data)
    return html



