from templates.img_conversion import image_url_to_base64
from django.shortcuts import render
import datetime


def po_data(po_response):
    po_response = po_response[0]
    po_response_fdasafd=[
    {
        "po_id": "8fa734c4-57e1-4060-a608-a75c075e1c0a",
        "po_items": [
            {
                "po_id": {
                    "po_id": "8fa734c4-57e1-4060-a608-a75c075e1c0a",
                    "cgst_total": "0.00",
                    "sgst_total": "0.00",
                    "igst_total": "0.00",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-07T12:21:13.956523+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-07T12:21:13.956523+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-07T12:21:13.956523+05:30",
                    "is_po_generated": True,
                    "po_status": "Save and Send",
                    "po_serial": "200",
                    "po_ref_no": "200",
                    "po_date": "2022-03-07",
                    "po_amount": None,
                    "supply_place": "Manipur",
                    "bill_status": "None",
                    "destination_place": "Jharkhand",
                    "term_name": "cash on delivery",
                    "no_of_days": "15",
                    "shipment_preference": None,
                    "discount_type": "item level",
                    "sub_total": "1500",
                    "total": "1500",
                    "entered_discount": "0",
                    "discount": "0",
                    "customer_note": "",
                    "terms_condition": "",
                    "tcs_amount": "0",
                    "expected_delivery_date": "2022-03-10",
                    "attach_file": None,
                    "vendor_id": "0b2382e1-ae2a-463d-a66e-3dab1738d857",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "tcs_id": None,
                    "customer_id": None
                },
                "poitem_id": "fb41a729-e79d-4bda-87ff-0bec5cb313d0",
                "item_name": "Test Item 2",
                "amount": "1500.00",
                "discount": "0.00",
                "quantity": "1.00",
                "rate": "1500.00",
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "customer_id": None,
                "cgst_amount": "0.00",
                "sgst_amount": "0.00",
                "igst_amount": "0.00",
                "tax_name": "Non-Taxable"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-03-07T12:21:13.956523+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-07T12:21:13.956523+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-07T12:21:13.956523+05:30",
        "is_po_generated": True,
        "po_status": "Save and Send",
        "po_serial": "200",
        "po_ref_no": "200",
        "po_date": "2022-03-07",
        "po_amount": None,
        "supply_place": "Manipur",
        "bill_status": "None",
        "destination_place": "Jharkhand",
        "term_name": "cash on delivery",
        "no_of_days": "15",
        "shipment_preference": None,
        "discount_type": "item level",
        "sub_total": "1500",
        "total": "1500",
        "entered_discount": "0",
        "discount": "0",
        "customer_note": "",
        "terms_condition": "",
        "tcs_amount": "0",
        "expected_delivery_date": "2022-03-10",
        "attach_file": None,
        "vendor_id": {
            "vendor_id": "0b2382e1-ae2a-463d-a66e-3dab1738d857",
            "created_id": "None",
            "created_date": "2022-03-07T08:07:08.572887+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-07T08:07:08.572887+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-07T08:07:08.572887+05:30",
            "salutation": "Mrs.",
            "vendor_name": "Test1",
            "vendor_mobile": "555655655656",
            "vendor_display_name": "test",
            "vendor_contact": "",
            "vendor_email": "test@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "Due on Receipt",
            "no_of_days": 0,
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Maharashtra",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "tcs_id": None,
        "customer_id": None
    }
]

    contents={

        "company_name":po_response['company_id']['company_name'],
        "address":po_response['company_id']['address'],
        "city":po_response['company_id']['city'],
        "gst_in":po_response['company_id']['gstin'],
        "po_serial":po_response['po_serial'],
        "po_date":datetime.datetime.strptime(po_response['po_date'], "%Y-%m-%d").date(),
        "place_of_supply":po_response['supply_place'],
        "sub_total":po_response['sub_total'],
        "vendor_name":po_response['vendor_id']['vendor_name'],
        "vendor_address":po_response['vendor_id']['bill_address1'],
        "ship_address":po_response['vendor_id']['ship_address1'],
        "discount":po_response['discount'],
        'po_items': [dict(a) for a in po_response['po_items']],
        "total_in_words":'',
        "cgst_0":'',
        "itemdescription":'',
        "sgst0_0":'',
        "cgst25_25":po_response['cgst_total'],
        "sgst25_25":'',
        "cgst6_6":'',
        "sgst6_6":'',
        "cgst9_9":'',
        "sgst_total":po_response['sgst_total'],
        "cgst_total":po_response['cgst_total'],
        "igst_total":po_response['igst_total'],
        "tcs":po_response['tcs_amount'],
       # "shipping_charges":po_response['shipping_charges'],
        "total":po_response['total'],
       # "credit_remaining":po_response['credit_remaining'],
        "customer_name":po_response['vendor_id']['vendor_name'],
        #"item_serial":invoice_response['invoice_items'][0]['item_serial'],
        
    }
    print(contents)
    return contents



if __name__ == '__main__':
    po_Response=[
    {
        "po_id": "8fa734c4-57e1-4060-a608-a75c075e1c0a",
        "po_items": [
            {
                "po_id": {
                    "po_id": "8fa734c4-57e1-4060-a608-a75c075e1c0a",
                    "cgst_total": "0.00",
                    "sgst_total": "0.00",
                    "igst_total": "0.00",
                    "cgst_amount": "0.00",
                    "sgst_amount": "0.00",
                    "igst_amount": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-07T12:21:13.956523+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-07T12:21:13.956523+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-07T12:21:13.956523+05:30",
                    "is_po_generated": True,
                    "po_status": "Save and Send",
                    "po_serial": "200",
                    "po_ref_no": "200",
                    "po_date": "2022-03-07",
                    "po_amount": None,
                    "supply_place": "Manipur",
                    "bill_status": "None",
                    "destination_place": "Jharkhand",
                    "term_name": "cash on delivery",
                    "no_of_days": "15",
                    "shipment_preference": None,
                    "discount_type": "item level",
                    "sub_total": "1500",
                    "total": "1500",
                    "entered_discount": "0",
                    "discount": "0",
                    "customer_note": "",
                    "terms_condition": "",
                    "tcs_amount": "0",
                    "expected_delivery_date": "2022-03-10",
                    "attach_file": None,
                    "vendor_id": "0b2382e1-ae2a-463d-a66e-3dab1738d857",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "tcs_id": None,
                    "customer_id": None
                },
                "poitem_id": "fb41a729-e79d-4bda-87ff-0bec5cb313d0",
                "item_name": "Test Item 2",
                "amount": "1500.00",
                "discount": "0.00",
                "quantity": "1.00",
                "rate": "1500.00",
                "coa_id": {
                    "coa_id": "c3e81bdb-9b4e-4952-af69-97d8d5225c6c",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:38:48.087046+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:38:48.087046+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:38:48.087046+05:30",
                    "account_type": "Expense",
                    "account_head": "Cost of material consumed",
                    "account_subhead": "Cost of material consumed",
                    "account_name": "Purchase Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "customer_id": None,
                "cgst_amount": "0.00",
                "sgst_amount": "0.00",
                "igst_amount": "0.00",
                "tax_name": "Non-Taxable"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "created_id": "None",
        "created_date": "2022-03-07T12:21:13.956523+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-07T12:21:13.956523+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-07T12:21:13.956523+05:30",
        "is_po_generated": True,
        "po_status": "Save and Send",
        "po_serial": "200",
        "po_ref_no": "200",
        "po_date": "2022-03-07",
        "po_amount": None,
        "supply_place": "Manipur",
        "bill_status": "None",
        "destination_place": "Jharkhand",
        "term_name": "cash on delivery",
        "no_of_days": "15",
        "shipment_preference": None,
        "discount_type": "item level",
        "sub_total": "1500",
        "total": "1500",
        "entered_discount": "0",
        "discount": "0",
        "customer_note": "",
        "terms_condition": "",
        "tcs_amount": "0",
        "expected_delivery_date": "2022-03-10",
        "attach_file": None,
        "vendor_id": {
            "vendor_id": "0b2382e1-ae2a-463d-a66e-3dab1738d857",
            "created_id": "None",
            "created_date": "2022-03-07T08:07:08.572887+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-07T08:07:08.572887+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-07T08:07:08.572887+05:30",
            "salutation": "Mrs.",
            "vendor_name": "Test1",
            "vendor_mobile": "555655655656",
            "vendor_display_name": "test",
            "vendor_contact": "",
            "vendor_email": "test@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "Due on Receipt",
            "no_of_days": 0,
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Maharashtra",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "tcs_id": None,
        "customer_id": None
    }
]
    a = po_data(po_Response)
    print(a)



def generate_po_pdf(data):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html =  render(None, "core/po.html",data)
    return html