from templates.img_conversion import image_url_to_base64
from django.shortcuts import render
import datetime
def pm_data(pm_response):
    pm_response = pm_response[0]
    pm_response_sadfsa= [
        {
        "pm_id": "76b22725-d9bc-4c65-8360-3288791b44f5",
        "payment_ref_no": "45",
        "paid_through": "032bf95f-1541-441c-913b-d90ea1a7f085",
        "amount_payable": "20000.00",
        "bill_serial": "BILL345",
        "balance_amount": "0.00",
        "vendor_id": {
            "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
            "created_id": "None",
            "created_date": "2022-03-04T17:51:08.904962+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-04T17:51:08.904962+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-04T17:51:08.904962+05:30",
            "salutation": None,
            "vendor_name": "Test",
            "vendor_mobile": "09822607468",
            "vendor_display_name": "test display",
            "vendor_contact": "09822607468",
            "vendor_email": "gayatrireddy800@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "test technology",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "cash on delivery",
            "no_of_days": 15,
            "set_credit_limit": "0.00",
            "gst_treatment": "Registered Business - Composition",
            "gstin_number": "GN156489",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "GN156489",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Karnataka",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "true",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "payment_date": "2022-03-07",
        "payment_ref_no": "45",
        "bill_date": "2022-03-05T00:00:00+05:30",
        "bill_amount": "4994.00",
        "payment_mode": "Cash",
        "amount_payable": "20000.00",
        "amount_due": "4994.00",
        "payment_serial": "1235"
    },
    ]
    

    contents={
        "company_name":pm_response['company_id']['company_name'],
        "address":pm_response['company_id']['address'],
        "city":pm_response['company_id']['city'],
        "gst_in":pm_response['company_id']['gstin'],
        "payment_serial":pm_response['payment_serial'],
        "payment_date":datetime.datetime.strptime(pm_response['payment_date'], "%Y-%m-%d").date() if pm_response['payment_date'] else None,
        "payment_mode":pm_response['payment_mode'],
      #  "total":pm_response['total'],
       # "credit_remaining":pm_response['total'],
        "customer_name":pm_response['vendor_id']['vendor_name'],
        "bill_serial":pm_response["bill_serial"],
        "payment_ref_no":pm_response['payment_ref_no'],
        "paid_through":pm_response['paid_through'],
        "amount_payable":pm_response['amount_payable'],
        "bill_date":pm_response['bill_date'],
        "bill_amount":pm_response['bill_amount'],
        "gstin_number":pm_response['vendor_id']['gstin_number']
    }
  #  print("----------------------------------------------------------------",contents)
    return contents
if __name__ == '__main__':
    pm_Response=[
    {
        "pm_id": "76b22725-d9bc-4c65-8360-3288791b44f5",
        "payment_ref_no": "45",
        "paid_through": "032bf95f-1541-441c-913b-d90ea1a7f085",
        "amount_payable": "20000.00",
        "bill_serial": "BILL345",
        "balance_amount": "0.00",
        "vendor_id": {
            "vendor_id": "18ac0347-1686-4440-a5ca-5504e329cfe4",
            "created_id": "None",
            "created_date": "2022-03-04T17:51:08.904962+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-04T17:51:08.904962+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-04T17:51:08.904962+05:30",
            "salutation": None,
            "vendor_name": "Test",
            "vendor_mobile": "09822607468",
            "vendor_display_name": "test display",
            "vendor_contact": "09822607468",
            "vendor_email": "gayatrireddy800@gmail.com",
            "vendor_type": "None",
            "vendor_designation": "",
            "vendor_department": "",
            "parent_vendor": "None",
            "enable_portal": False,
            "company_name": "test technology",
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "payment_terms": "None",
            "term_name": "cash on delivery",
            "no_of_days": 15,
            "set_credit_limit": "0.00",
            "gst_treatment": "Registered Business - Composition",
            "gstin_number": "GN156489",
            "tax_preference": "Taxable",
            "tds": "None",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "GN156489",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "source_place": "Karnataka",
            "tax_prefrances": "None",
            "exemption_reason": "",
            "remarks": "",
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "true",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "payment_date": "2022-03-07",
        "payment_ref_no": "45",
        "payment_mode": "Cash",
        "amount_payable": "20000.00",
        "amount_due": "4994.00",
        "payment_serial": "1235"
    },
    ]
    a = pm_data(pm_Response)

def generate_payment_made_pdf(data):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html =  render(None, "core/pm.html",data)
    return html