# Generated by Django 4.0.1 on 2024-09-18 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfiling',
            name='id',
        ),
        migrations.AddField(
            model_name='requestfiling',
            name='filing_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
