# Generated by Django 4.0.1 on 2025-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0002_remove_requestfiling_id_requestfiling_filing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfiling',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestfiling',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
