# Generated by Django 4.0.1 on 2023-03-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
        ('salescustomer', '0002_alter_salescustomer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerob',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
    ]
