# Generated by Django 4.0.1 on 2023-03-16 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0003_customerob_coa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerob',
            name='migration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
