# Generated by Django 4.0.1 on 2023-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0004_alter_customerob_migration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='so',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='From_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='so',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='To_is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
