# Generated by Django 4.0.1 on 2023-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0005_so_from_convt_id_so_from_convt_ref_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='convt_id',
            new_name='From_convt_id',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='convt_ref_no',
            new_name='From_convt_ref_no',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='convt_serial',
            new_name='From_convt_serial',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='convt_type',
            new_name='From_convt_type',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='is_converted',
            new_name='From_is_converted',
        ),
        migrations.AddField(
            model_name='estimate',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='To_is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
