# Generated by Django 4.0.1 on 2023-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0006_rename_convt_id_estimate_from_convt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
