# Generated by Django 4.0.1 on 2023-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0007_creditnote_from_convt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
