# Generated by Django 4.0.1 on 2023-08-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
        ('salescustomer', '0008_creditnote_is_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateditem',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
    ]
