# Generated by Django 4.0.1 on 2023-08-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
        ('salescustomer', '0009_estimateditem_coa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soitem',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
    ]
