# Generated by Django 4.0.1 on 2023-08-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0007_estimate_convt_id_estimate_convt_ref_no_and_more'),
        ('salescustomer', '0011_dcitem_coa_id'),
    ]

    operations = [
    ]
