# Generated by Django 4.0.1 on 2023-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0011_dcitem_coa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc',
            name='ClassRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='CustomerMsgRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='CustomerRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='CustomerSalesTaxCodeRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='From_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dc',
            name='ItemSalesTaxRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='SalesRepRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='ShipMethodRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='TemplateRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='TermsRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='To_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dc',
            name='TxnID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
