# Generated by Django 4.0.1 on 2023-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0012_dc_classreflistid_dc_customermsgreflistid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='To_is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
