# Generated by Django 4.0.1 on 2023-08-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0012_dc_classreflistid_dc_customermsgreflistid_and_more'),
        ('salescustomer', '0012_merge_20230822_0314'),
    ]

    operations = [
    ]
