# Generated by Django 4.0.1 on 2023-09-08 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_financial_year'),
        ('salescustomer', '0012_dc_classreflistid_dc_customermsgreflistid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple_Invoice_Details',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mul_bill_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('insert_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='salescustomer.invoice')),
                ('pr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='salescustomer.pr')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
