# Generated by Django 4.0.1 on 2023-09-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0013_creditnote_to_convt_id_creditnote_to_convt_ref_no_and_more'),
        ('salescustomer', '0013_merge_20230829_0606'),
    ]

    operations = [
    ]
