# Generated by Django 4.0.1 on 2023-09-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0013_multiple_invoice_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiple_invoice_details',
            old_name='mul_bill_id',
            new_name='mul_inv_id',
        ),
    ]
