# Generated by Django 4.0.1 on 2023-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0014_merge_20230907_0426'),
        ('salescustomer', '0014_rename_mul_bill_id_multiple_invoice_details_mul_inv_id'),
    ]

    operations = [
    ]
