# Generated by Django 4.0.1 on 2023-09-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0015_merge_20230908_0443'),
        ('salescustomer', '0015_merge_20230911_1449'),
    ]

    operations = [
    ]
