# Generated by Django 4.0.1 on 2023-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0016_merge_20230913_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cess_rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
