# Generated by Django 4.0.1 on 2023-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0017_invoice_cess_total_invoiceitem_cess_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
