# Generated by Django 4.0.1 on 2023-12-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0018_invoice_discount_type_invoiceitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invoices', to='salescustomer.salescustomer'),
        ),
    ]
