# Generated by Django 4.0.1 on 2023-12-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0019_invoice_customer_name_alter_invoice_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-invoice_date',), 'verbose_name_plural': 'Invoice'},
        ),
    ]
