# Generated by Django 4.0.1 on 2024-01-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0020_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dc',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Delivery Challan'},
        ),
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'estimate'},
        ),
        migrations.AlterModelOptions(
            name='estimateditem',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'estimated item'},
        ),
        migrations.AlterModelOptions(
            name='pr',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Payment Receive'},
        ),
        migrations.AlterModelOptions(
            name='salescustomer',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'customer'},
        ),
    ]
