# Generated by Django 4.0.1 on 2024-01-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_charges_percentage_charges_rate'),
        ('salescustomer', '0021_alter_dc_options_alter_estimate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charges',
            field=models.ManyToManyField(blank=True, related_name='charges_transaction', to='transaction.ChargeTransaction'),
        ),
    ]
