# Generated by Django 4.0.1 on 2024-01-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0024_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='so',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Sales Order'},
        ),
        migrations.AddField(
            model_name='dc',
            name='shipping_tax_rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
