# Generated by Django 4.0.1 on 2024-01-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0025_alter_so_options_dc_shipping_tax_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Credit Note'},
        ),
    ]
