# Generated by Django 4.0.1 on 2024-01-29 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0026_alter_creditnote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_prs', to='salescustomer.invoice'),
        ),
    ]
