# Generated by Django 4.0.1 on 2024-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0027_alter_pr_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retail_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
