# Generated by Django 4.0.1 on 2024-06-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0028_invoice_retail_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'invoice item'},
        ),
        migrations.AddField(
            model_name='salescustomer',
            name='tcs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.tcs'),
        ),
        migrations.AddField(
            model_name='tcs',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
