# Generated by Django 4.0.1 on 2024-06-05 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0029_alter_invoiceitem_options_salescustomer_tcs_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTcs',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('tcs_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('company_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer_tcs',
                'managed': False,
            },
        ),
    ]
