# Generated by Django 4.0.1 on 2024-07-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0030_customertcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
