# Generated by Django 4.0.1 on 2024-07-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0031_invoiceitem_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
