# Generated by Django 4.0.1 on 2024-07-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0032_invoiceitem_expire_date_invoiceitem_mfg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credititem',
            name='batches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='credititem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credititem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
