# Generated by Django 4.0.1 on 2024-08-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0033_credititem_batches_credititem_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='dc',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dc',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='estimate',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='pr',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='salescustomer',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salescustomer',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='so',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
