# Generated by Django 4.0.1 on 2024-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0035_alter_credititem_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcs',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tcs',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
    ]
