# Generated by Django 4.0.1 on 2024-09-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0036_tcs_ext_id_tcs_ext_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcs',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=100),
        ),
        migrations.AlterField(
            model_name='tcs',
            name='nature_of_collection',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tcs',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tcs',
            name='tcs_payable_account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tcs',
            name='tcs_receivable_account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
