# Generated by Django 4.0.1 on 2024-09-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0037_alter_tcs_ext_type_alter_tcs_nature_of_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='TermsRefFullName',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='TermsRefListID',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_method',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deposit_to',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subject',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supply_place',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='b_attention',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='bill_address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='bill_address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='bill_address_city',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='bill_address_country',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='bill_address_state',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='cin_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='company_display_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='company_email',
            field=models.EmailField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='company_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='contact_department',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='contact_designation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='contact_email',
            field=models.EmailField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='contact_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='contact_salutation',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customerRefListId',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customerTypeRefListId',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customerTypeReffullName',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customer_department',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customer_designation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customer_display_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customer_email',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customer_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='customer_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='exemption_reason',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=100),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='gst_treatment',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='parent_customer',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ship_address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ship_address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ship_address_city',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ship_address_country',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ship_address_state',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='ship_fax_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='supply_place',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='tax_preference',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='term_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='trn_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='vat_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salescustomer',
            name='website',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
