# Generated by Django 4.0.1 on 2024-09-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0038_alter_invoice_from_convt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credititem',
            name='item_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credititem',
            name='selected_item_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credititem',
            name='selected_tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credititem',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credititem',
            name='tax_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='cn_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='cn_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='cn_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='customer_email',
            field=models.EmailField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='customer_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='received_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='supply_place',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='terms_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
