# Generated by Django 4.0.1 on 2024-10-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0040_remove_pr_notes_creditnote_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
