# Generated by Django 4.0.1 on 2024-10-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0041_pr_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
