# Generated by Django 4.0.1 on 2024-10-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0009_basecoa_system_coa_system'),
        ('salescustomer', '0042_alter_invoice_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescustomer',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
    ]
