# Generated by Django 4.0.1 on 2024-10-31 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0009_basecoa_system_coa_system'),
        ('salescustomer', '0043_salescustomer_coa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='cgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_cgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='coa_total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='igst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_igst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sales_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_sales', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_sgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='shipping_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_shipping', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tcs_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_tcs', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tds_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_tds', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_cgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='coa_total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_igst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_sgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_salesshipping', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tcs_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_tcs', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_tds', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='pr',
            name='cgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_pr_cgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='pr',
            name='coa_total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='igst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_pr_igst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='pr',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_pr_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='pr',
            name='sgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_pr_sgst', to='coa.coa'),
        ),
    ]
