# Generated by Django 4.0.1 on 2024-10-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0009_basecoa_system_coa_system'),
        ('salescustomer', '0044_creditnote_cgst_account_creditnote_coa_total_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cess_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_cess', to='coa.coa'),
        ),
    ]
