# Generated by Django 4.0.1 on 2024-10-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0009_basecoa_system_coa_system'),
        ('salescustomer', '0045_invoice_cess_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='cess_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_cess', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='discount_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_cn_discount', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_sales_discount', to='coa.coa'),
        ),
    ]
