# Generated by Django 4.0.1 on 2024-11-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_consumption_godown_id_consumption_godown_name_and_more'),
        ('salescustomer', '0046_creditnote_cess_account_creditnote_discount_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credititem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='credititem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dcitem',
            name='batches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dcitem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcitem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='dcitem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dcitem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soitem',
            name='batches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soitem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soitem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='soitem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soitem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
