# Generated by Django 4.0.1 on 2024-11-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0016_remove_tax_rate_1'),
        ('salescustomer', '0047_credititem_godown_id_credititem_godown_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.tax'),
        ),
    ]
