# Generated by Django 4.0.1 on 2024-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0048_invoiceitem_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='credititem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
