# Generated by Django 4.0.1 on 2024-11-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0049_credititem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='discount_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
