# Generated by Django 4.0.1 on 2024-11-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0050_creditnote_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
