# Generated by Django 4.0.1 on 2024-11-27 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0051_creditnote_total_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrView',
            fields=[
                ('pr_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('company_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('branch_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('amount_excess', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_ref_no', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('payment_serial', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('invoice_serial', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('customer_name', models.CharField(blank=True, default='null', max_length=200, null=True)),
            ],
            options={
                'db_table': 'pr_view',
                'managed': False,
            },
        ),
    ]
