# Generated by Django 4.0.1 on 2023-02-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_vendor_vendor_name'),
        ('salescustomer', '0002_alter_salescustomer_customer_name'),
        ('accounting', '0002_initial'),
        ('statement', '0002_alter_transaction_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_transaction', to='salescustomer.invoice'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='purchase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_transaction', to='purchase.paymentmade'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='voucher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_transaction', to='accounting.manualjournal'),
        ),
    ]
