# Generated by Django 4.0.1 on 2023-02-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('statement', '0003_alter_transactiondetail_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
    ]
