# Generated by Django 4.0.1 on 2023-03-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('statement', '0004_alter_fileupload_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_files', to='company.company'),
        ),
    ]
