# Generated by Django 4.0.1 on 2023-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0005_alter_fileupload_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
