# Generated by Django 4.0.1 on 2023-03-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_vendor_vendor_name'),
        ('salescustomer', '0002_alter_salescustomer_customer_name'),
        ('statement', '0006_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_transaction', to='purchase.bill'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='salescustomer.pr'),
        ),
    ]
