# Generated by Django 4.0.1 on 2023-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0002_alter_salescustomer_customer_name'),
        ('purchase', '0003_alter_vendor_vendor_name'),
        ('statement', '0007_transactiondetail_bill_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='bill_id',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='bill_id',
            field=models.ManyToManyField(related_name='bill_transaction', to='purchase.Bill'),
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='invoice_id',
            field=models.ManyToManyField(related_name='invoice_transaction', to='salescustomer.Invoice'),
        ),
    ]
