# Generated by Django 4.0.1 on 2023-11-02 02:51

from django.db import migrations, models
import statement.models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0009_alter_transactiondetail_bill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=statement.models.statement_path),
        ),
    ]
