# Generated by Django 4.0.1 on 2023-11-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0010_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
    ]
