# Generated by Django 4.0.1 on 2023-12-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0020_alter_invoice_options'),
        ('purchase', '0013_bill_cess_total_bill_item_cess_amount_and_more'),
        ('accounting', '0002_initial'),
        ('statement', '0012_alter_transaction_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='payment_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='payment_transactions', to='salescustomer.PR'),
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='purchase_id',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='purchase_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchase_transactions', to='purchase.PaymentMade'),
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='voucher_id',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='voucher_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='voucher_transactions', to='accounting.ManualJournal'),
        ),
    ]
