# Generated by Django 4.0.1 on 2024-01-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0014_alter_transactiondetail_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
