# Generated by Django 4.0.1 on 2024-01-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0015_alter_bank_options_alter_fileupload_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='transactiondetail',
            options={'ordering': ['-created_date']},
        ),
    ]
