# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('item', '0001_initial'),
        ('salescustomer', '0001_initial'),
        ('coa', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='est_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_data', to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.taxname'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='adjustmentitem',
            name='adj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adj_items', to='item.adjustment'),
        ),
        migrations.AddField(
            model_name='adjustmentitem',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='adjustmentitem',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='adjustmentitem',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
    ]
