# Generated by Django 4.0.1 on 2023-11-21 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_user'),
        ('item', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Stock'},
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('taxgroup_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id1', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id2', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
