# Generated by Django 4.0.1 on 2023-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_stock_options_taxgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Item'},
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
