# Generated by Django 4.0.1 on 2024-01-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_options_item_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustment',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Adjustment'},
        ),
    ]
