# Generated by Django 4.0.1 on 2024-06-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_branch_options'),
        ('item', '0006_alter_adjustment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
    ]
