# Generated by Django 4.0.1 on 2024-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_adjustment_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
