# Generated by Django 4.0.1 on 2024-10-29 06:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('item', '0010_alter_item_item_grp_id'), ('item', '0011_stocktransfertransaction_sec_item_id_and_more'), ('item', '0012_alter_stock_adjusted_qty_alter_stock_quantity_and_more'), ('item', '0013_alter_adjustmentitem_adjusted_qty_and_more'), ('item', '0014_stocktransfertransaction_sec_batches_and_more'), ('item', '0015_alter_stocktransfertransaction_sec_batches'), ('item', '0016_consumption_production_stockjournal'), ('item', '0017_consumption_sj_id_production_sj_id'), ('item', '0018_rename_batch_no_consumption_batches_and_more'), ('item', '0019_alter_consumption_item_id_alter_production_item_id'), ('item', '0020_alter_stock_options_stock_purchase_stock'), ('item', '0021_alter_stock_options_alter_consumption_sj_id_and_more')]

    dependencies = [
        ('item', '0009_batch_squashed_0026_rename_batch_no_manufacturingbyitem_batches_and_more'),
        ('company', '0022_remove_defaults_id_defaults_def_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_grp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_items', to='item.itemgroup'),
        ),
        migrations.AddField(
            model_name='stocktransfertransaction',
            name='sec_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec_items', to='item.item'),
        ),
        migrations.AlterField(
            model_name='stocktransfertransaction',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_items', to='item.item'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='adjusted_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adjustmentitem',
            name='adjusted_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adjustmentitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adjustmentitem',
            name='stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfertransaction',
            name='sec_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfertransaction',
            name='sec_mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfertransaction',
            name='sec_batches',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.CreateModel(
            name='StockJournal',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sj_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ext_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ext_type', models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('total_consumption', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_production', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_consumption_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_production_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Stock'},
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.stock'),
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Stock'},
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cmp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('item_name', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('warehouse_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('batches', models.CharField(blank=True, max_length=200, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sj_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_items', to='item.stockjournal')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prd_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('item_name', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('warehouse_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('batches', models.CharField(blank=True, max_length=200, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sj_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_items', to='item.stockjournal')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
