# Generated by Django 4.0.1 on 2024-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_item_grp_id_squashed_0021_alter_stock_options_alter_consumption_sj_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='module_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
