# Generated by Django 4.0.1 on 2024-11-13 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_stock_module_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAvgTransaction',
            fields=[
                ('item_id', models.CharField(default="<class 'uuid.UUID'>", max_length=200, primary_key=True, serialize=False)),
                ('closing_stock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('closing_stock_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('avg_weighted_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=200, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('module_date', models.DateTimeField(blank=True, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=200, null=True)),
                ('company_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'avg_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTransaction',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sum_last_transactions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('avg_weighted_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=200, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('module_date', models.DateTimeField(blank=True, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=200, null=True)),
                ('company_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'item_transaction',
                'managed': False,
            },
        ),
    ]
