# Generated by Django 4.0.1 on 2024-11-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_itemavgtransaction_itemtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='closing_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='closing_stock_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='closing_stock_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
