# Generated by Django 4.0.1 on 2024-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_stock_closing_stock_stock_closing_stock_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='warehouse_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
