# Generated by Django 4.0.1 on 2024-11-19 05:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_stock_warehouse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('wh_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='warehouse_id',
            new_name='godown_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='flow_type',
            field=models.CharField(blank=True, choices=[('INWARD', 'INWARD'), ('OUTWARD', 'OUTWARD')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
    ]
