# Generated by Django 4.0.1 on 2024-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_warehouse_rename_warehouse_id_stock_godown_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
    ]
