# Generated by Django 4.0.1 on 2024-11-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_remove_defaults_id_defaults_def_id'),
        ('item', '0016_warehouse_ext_id_warehouse_ext_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
    ]
