# Generated by Django 4.0.1 on 2024-11-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_warehouse_branch_id_warehouse_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingbyitem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='manufacturingbyitem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingjournalitem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='manufacturingjournalitem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='production',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
