# Generated by Django 4.0.1 on 2024-11-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0016_remove_tax_rate_1'),
        ('item', '0019_manufacturingjournal_godown_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='central_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_central_tax', to='coa.tax'),
        ),
        migrations.AddField(
            model_name='item',
            name='state_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_state_tax', to='coa.tax'),
        ),
    ]
