# Generated by Django 4.0.1 on 2024-11-27 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_item_central_tax_item_state_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('unit', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_category', models.CharField(blank=True, max_length=200, null=True)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'item_view',
                'managed': False,
            },
        ),
    ]
