debit_note_items =[
        {
            "item_name": "TEST Item 2",
            "quantity": 1,
            "rate": 2000,
            "amount": 2000,
            "item_id": "2209b4db-d8aa-42a9-aedb-b2c8f87ef6aa",
            "coa_id": "8ea8bb62-a298-473e-9c22-bb7659621e56",
            "selected_item_name": {
                "item_id": "2209b4db-d8aa-42a9-aedb-b2c8f87ef6aa",
                "created_id": "None",
                "created_date": "2022-02-25T18:22:18.803255+05:30",
                "modified_id": "None",
                "modified_date": "2022-02-25T18:22:18.803255+05:30",
                "deleted_id": "None",
                "deleted_date": "2022-02-25T18:22:18.803255+05:30",
                "ref_no": "None",
                "item_category": "Goods",
                "name": "TEST Item 2",
                "sku": "None",
                "sac": "",
                "hsn_code": "",
                "unit": "",
                "category": "None",
                "tax_preference": "Taxable",
                "item_description": "None",
                "sale_price": "2500.00",
                "sales_account": "73c6e8fd-3fd7-452d-ab43-e650c6a90918",
                "sale_description": "",
                "cost_price": "2000.00",
                "purchase_account": "8ea8bb62-a298-473e-9c22-bb7659621e56",
                "purchase_description": "",
                "inventory_account": "85a45977-4cf7-47c7-852f-8f54d76e157d",
                "inter_rate": None,
                "intra_rate": "GST0 [0%]",
                "opening_stock": "0.00",
                "opening_stock_rate": "0.00",
                "discount": "0.00",
                "reorder_point": "0.00",
                "preferred_vendor": None,
                "date": None,
                "exemption_reason": "",
                "company_id": {
                    "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
                    "created_id": "None",
                    "created_date": "2022-02-18T11:31:16.270717+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-02-18T11:31:16.270717+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-02-18T11:31:16.270717+05:30",
                    "trial_company": None,
                    "company_name": "Coderize Technologies Pvt. Ltd.",
                    "alias_name": "",
                    "address": "Pune",
                    "locality": "",
                    "landmark": "",
                    "pincode": 411037,
                    "city": "",
                    "state": "Maharashtra",
                    "other": "",
                    "is_primary": True,
                    "primary_phone_number": "",
                    "primary_mobile_number": "9554215425",
                    "primary_alternate_number": "",
                    "primary_email": "support@coderize.in",
                    "secondary_phone_number": "",
                    "secondary_mobile_number": "",
                    "secondary_alternate_number": "",
                    "secondary_email": "",
                    "website": "",
                    "books_start_date": "2022-02-01",
                    "method": "None",
                    "company_type": "Private",
                    "pan_number": "KJSHFU5486",
                    "gstin": "",
                    "cin": "",
                    "other_registration_number": "",
                    "password": "584587587",
                    "security_control": "false",
                    "audit_feature": "True",
                    "logo_image": "/media/None",
                    "report_basis": "None",
                    "company_edit_id": "None",
                    "tax_edit_id": "None",
                    "separate_payment_address": "False",
                    "address_receive_payment": "None"
                },
                "branch_id": None,
                "est_id": None,
                "vendor_id": None,
                "coa_id": None,
                "tax_id": None
            },
            "selected_tax_name": None,
            "tax_name": None,
            "tax_rate": 0,
            "tax_type": None,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "igst_amount": 0,
            "taxamount": None
        },
        {
            "item_name": "TEST Item 2",
            "quantity": 1,
            "rate": 2000,
            "amount": 2000,
            "item_id": "2209b4db-d8aa-42a9-aedb-b2c8f87ef6aa",
            "coa_id": "8ea8bb62-a298-473e-9c22-bb7659621e56",
            "selected_item_name": {
                "item_id": "2209b4db-d8aa-42a9-aedb-b2c8f87ef6aa",
                "created_id": "None",
                "created_date": "2022-02-25T18:22:18.803255+05:30",
                "modified_id": "None",
                "modified_date": "2022-02-25T18:22:18.803255+05:30",
                "deleted_id": "None",
                "deleted_date": "2022-02-25T18:22:18.803255+05:30",
                "ref_no": "None",
                "item_category": "Goods",
                "name": "TEST Item 2",
                "sku": "None",
                "sac": "",
                "hsn_code": "",
                "unit": "",
                "category": "None",
                "tax_preference": "Taxable",
                "item_description": "None",
                "sale_price": "2500.00",
                "sales_account": "73c6e8fd-3fd7-452d-ab43-e650c6a90918",
                "sale_description": "",
                "cost_price": "2000.00",
                "purchase_account": "8ea8bb62-a298-473e-9c22-bb7659621e56",
                "purchase_description": "",
                "inventory_account": "85a45977-4cf7-47c7-852f-8f54d76e157d",
                "inter_rate": None,
                "intra_rate": "GST0 [0%]",
                "opening_stock": "0.00",
                "opening_stock_rate": "0.00",
                "discount": "0.00",
                "reorder_point": "0.00",
                "preferred_vendor": None,
                "date": None,
                "exemption_reason": "",
                "company_id": {
                    "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
                    "created_id": "None",
                    "created_date": "2022-02-18T11:31:16.270717+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-02-18T11:31:16.270717+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-02-18T11:31:16.270717+05:30",
                    "trial_company": None,
                    "company_name": "Coderize Technologies Pvt. Ltd.",
                    "alias_name": "",
                    "address": "Pune",
                    "locality": "",
                    "landmark": "",
                    "pincode": 411037,
                    "city": "",
                    "state": "Maharashtra",
                    "other": "",
                    "is_primary": True,
                    "primary_phone_number": "",
                    "primary_mobile_number": "9554215425",
                    "primary_alternate_number": "",
                    "primary_email": "support@coderize.in",
                    "secondary_phone_number": "",
                    "secondary_mobile_number": "",
                    "secondary_alternate_number": "",
                    "secondary_email": "",
                    "website": "",
                    "books_start_date": "2022-02-01",
                    "method": "None",
                    "company_type": "Private",
                    "pan_number": "KJSHFU5486",
                    "gstin": "",
                    "cin": "",
                    "other_registration_number": "",
                    "password": "584587587",
                    "security_control": "false",
                    "audit_feature": "True",
                    "logo_image": "/media/None",
                    "report_basis": "None",
                    "company_edit_id": "None",
                    "tax_edit_id": "None",
                    "separate_payment_address": "False",
                    "address_receive_payment": "None"
                },
                "branch_id": None,
                "est_id": None,
                "vendor_id": None,
                "coa_id": None,
                "tax_id": None
            },
            "selected_tax_name": None,
            "tax_name": None,
            "tax_rate": 0,
            "tax_type": None,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "igst_amount": 0,
            "taxamount": None
        },
        {
            "item_name": "Test4",
            "quantity": 1,
            "rate": 4000,
            "amount": 4000,
            "item_id": "71ea962a-662d-4f3b-b8dd-87b3f01e23a9",
            "coa_id": "add130af-1dae-4fa4-b550-9d7c4dc9ee7d",
            "selected_item_name": {
                "item_id": "71ea962a-662d-4f3b-b8dd-87b3f01e23a9",
                "created_id": "None",
                "created_date": "2022-02-28T12:03:55.441130+05:30",
                "modified_id": "None",
                "modified_date": "2022-02-28T12:03:55.441130+05:30",
                "deleted_id": "None",
                "deleted_date": "2022-02-28T12:03:55.441130+05:30",
                "ref_no": "None",
                "item_category": "Goods",
                "name": "Test4",
                "sku": "None",
                "sac": "",
                "hsn_code": "",
                "unit": "",
                "category": "None",
                "tax_preference": "Taxable",
                "item_description": "None",
                "sale_price": "5000.00",
                "sales_account": "7b0af606-fabc-4244-ae04-6a07a4466386",
                "sale_description": "",
                "cost_price": "4000.00",
                "purchase_account": "add130af-1dae-4fa4-b550-9d7c4dc9ee7d",
                "purchase_description": "",
                "inventory_account": "85a45977-4cf7-47c7-852f-8f54d76e157d",
                "inter_rate": None,
                "intra_rate": None,
                "opening_stock": "0.00",
                "opening_stock_rate": "0.00",
                "discount": "0.00",
                "reorder_point": "0.00",
                "preferred_vendor": None,
                "date": None,
                "exemption_reason": "",
                "company_id": {
                    "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
                    "created_id": "None",
                    "created_date": "2022-02-18T11:31:16.270717+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-02-18T11:31:16.270717+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-02-18T11:31:16.270717+05:30",
                    "trial_company": None,
                    "company_name": "Coderize Technologies Pvt. Ltd.",
                    "alias_name": "",
                    "address": "Pune",
                    "locality": "",
                    "landmark": "",
                    "pincode": 411037,
                    "city": "",
                    "state": "Maharashtra",
                    "other": "",
                    "is_primary": True,
                    "primary_phone_number": "",
                    "primary_mobile_number": "9554215425",
                    "primary_alternate_number": "",
                    "primary_email": "support@coderize.in",
                    "secondary_phone_number": "",
                    "secondary_mobile_number": "",
                    "secondary_alternate_number": "",
                    "secondary_email": "",
                    "website": "",
                    "books_start_date": "2022-02-01",
                    "method": "None",
                    "company_type": "Private",
                    "pan_number": "KJSHFU5486",
                    "gstin": "",
                    "cin": "",
                    "other_registration_number": "",
                    "password": "584587587",
                    "security_control": "false",
                    "audit_feature": "True",
                    "logo_image": "/media/None",
                    "report_basis": "None",
                    "company_edit_id": "None",
                    "tax_edit_id": "None",
                    "separate_payment_address": "False",
                    "address_receive_payment": "None"
                },
                "branch_id": None,
                "est_id": None,
                "vendor_id": None,
                "coa_id": None,
                "tax_id": None
            },
            "selected_tax_name": None,
            "tax_name": None,
            "tax_rate": 0,
            "tax_type": None,
            "cgst_amount": 0,
            "sgst_amount": 0,
            "igst_amount": 0,
            "taxamount": None
        }
    ]


coa_amount_dict = {}
for debit_note_item in debit_note_items:

    if coa_amount_dict.get(debit_note_item['coa_id']) is None:
        coa_amount_dict[debit_note_item['coa_id']] = debit_note_item['amount']
    else:
        coa_amount_dict[debit_note_item['coa_id']] = coa_amount_dict[debit_note_item['coa_id']] + debit_note_item['amount']

print(coa_amount_dict)

for key, value in coa_amount_dict.items():
    print(key, value)
