# Generated by Django 4.0.1 on 2024-02-04 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('month', models.PositiveIntegerField(default=0)),
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pm', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'dashboard',
                'managed': False,
            },
        ),
    ]
