# Generated by Django 4.0.1 on 2024-02-05 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTotal',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cash_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('bill_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'dashboard_total',
                'managed': False,
            },
        ),
    ]
