# Generated by Django 4.0.1 on 2024-02-16 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_dashboardtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReport',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_head', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_subhead', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('trans_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_report',
                'managed': False,
            },
        ),
    ]
