# Generated by Django 4.0.1 on 2024-02-20 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_accountreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('coa_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_head', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_subhead', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('label', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('value', models.CharField(blank=True, default='null', max_length=100, null=True)),
            ],
            options={
                'db_table': 'account_balance',
                'managed': False,
            },
        ),
    ]
