# Generated by Django 4.0.1 on 2024-02-22 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_purchasegst'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGst',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_serial', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('module', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('gstin_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('tax_name', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('i_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('c_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('s_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'sales_gst',
                'managed': False,
            },
        ),
    ]
