# Generated by Django 4.0.1 on 2024-02-22 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_salesgst'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('account', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'cash_book',
                'managed': False,
            },
        ),
    ]
