# Generated by Django 4.0.1 on 2024-04-23 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_bankbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR3B',
            fields=[
                ('ref_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('module', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_id', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, default='null', max_length=100, null=True)),
            ],
            options={
                'db_table': 'gstr_3b_report',
                'managed': False,
            },
        ),
    ]
