# Generated by Django 4.0.1 on 2024-09-25 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_gstr2a_gstr2b_alter_accountbalance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cash_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('bill_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'dashboard_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockValuationReport',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('branch_id', models.UUIDField(blank=True, null=True)),
                ('stk_in', models.IntegerField(default=0)),
                ('stk_out', models.IntegerField(default=0)),
                ('last_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=200, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'stock_report',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='accountreport',
            table='account_report_data',
        ),
    ]
