# Generated by Django 4.0.1 on 2025-09-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_stockreport_stockvaluationreport_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountreport',
            table='account_report_data_mat',
        ),
    ]
