# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('item', '0002_initial'),
        ('salescustomer', '0001_initial'),
        ('coa', '0001_initial'),
        ('purchase', '0001_initial'),
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='po_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='purchase.po'),
        ),
        migrations.AddField(
            model_name='po',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='po',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_po', to='company.company'),
        ),
        migrations.AddField(
            model_name='po',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='po',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='po',
            name='tcs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.tcs'),
        ),
        migrations.AddField(
            model_name='po',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_paymentmade', to='purchase.bill'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_paymentmade', to='company.company'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_paymentmade', to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.invoice'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.bill'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ven_debitnote', to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='dn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note_items', to='purchase.debitnote'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='purchase.bill'),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item'),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='bill',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Company_bills', to='company.company'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tcs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.tcs'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.tds'),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.vendor'),
        ),
    ]
