# Generated by Django 4.0.1 on 2023-06-03 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('purchase', '0003_alter_vendor_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple_Bill_Details',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mul_bill_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('insert_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='purchase.bill')),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
                ('pm_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='purchase.paymentmade')),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
