# Generated by Django 4.0.1 on 2023-04-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_vendorob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorob',
            options={'verbose_name_plural': 'Vendor Opening Balance'},
        ),
        migrations.AlterField(
            model_name='vendorob',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_balance', to='purchase.vendor'),
        ),
    ]
