# Generated by Django 4.0.1 on 2023-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_multiple_bill_details'),
        ('purchase', '0005_alter_vendorob_options_alter_vendorob_vendor_id'),
    ]

    operations = [
    ]
