# Generated by Django 4.0.1 on 2023-07-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_merge_20230606_0219'),
        ('purchase', '0006_merge_20230712_2318'),
    ]

    operations = [
    ]
