# Generated by Django 4.0.1 on 2023-07-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_merge_20230714_0550'),
        ('purchase', '0007_merge_20230715_0300'),
    ]

    operations = [
    ]
