# Generated by Django 4.0.1 on 2023-08-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_merge_20230715_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
