# Generated by Django 4.0.1 on 2023-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_expenserecord_is_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='From_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='TermsRefFullName',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='TermsRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
