# Generated by Django 4.0.1 on 2023-08-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_expenserecord_is_converted'),
        ('purchase', '0008_merge_20230725_0210'),
    ]

    operations = [
    ]
