# Generated by Django 4.0.1 on 2023-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_po_amountincludesvat_po_from_convt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='To_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='ClassRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='CustomerMsgRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='CustomerRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='CustomerSalesTaxCodeRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='From_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='ItemSalesTaxRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='SalesRepRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='ShipMethodRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='TemplateRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='TermsRefListID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='To_convt_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='To_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='To_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='To_convt_type',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='To_is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='TxnID',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
