# Generated by Django 4.0.1 on 2023-09-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_merge_20230822_0314'),
        ('purchase', '0011_bill_to_convt_id_bill_to_convt_ref_no_and_more'),
    ]

    operations = [
    ]
