# Generated by Django 4.0.1 on 2023-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_merge_20230907_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='cess_rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
