# Generated by Django 4.0.1 on 2024-01-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_bill_cess_total_bill_item_cess_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmade',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Payment Made'},
        ),
    ]
