# Generated by Django 4.0.1 on 2024-01-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_charges_percentage_charges_rate'),
        ('purchase', '0014_alter_paymentmade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='charges',
            field=models.ManyToManyField(blank=True, related_name='bill_charges_transaction', to='transaction.ChargeTransaction'),
        ),
    ]
