# Generated by Django 4.0.1 on 2024-01-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_bill_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
