# Generated by Django 4.0.1 on 2024-01-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_bill_total_charges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Bills'},
        ),
    ]
