# Generated by Django 4.0.1 on 2024-01-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_alter_bill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenserecord',
            options={'ordering': ['-expense_date'], 'verbose_name_plural': 'Expense Record'},
        ),
    ]
