# Generated by Django 4.0.1 on 2024-02-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_expenserecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Vendor'},
        ),
    ]
