# Generated by Django 4.0.1 on 2024-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_alter_vendor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitnote',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Debit Note'},
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='created_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='deleted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='deleted_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='modified_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
