# Generated by Django 4.0.1 on 2024-02-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_alter_debitnote_options_expenserecord_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenserecord',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Expense Record'},
        ),
    ]
