# Generated by Django 4.0.1 on 2024-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_alter_expenserecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tds',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
