# Generated by Django 4.0.1 on 2024-06-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_tds_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.tds'),
        ),
    ]
