# Generated by Django 4.0.1 on 2024-06-06 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_vendor_tds_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTds',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('tds_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('company_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vendor_tds',
                'managed': False,
            },
        ),
    ]
