# Generated by Django 4.0.1 on 2024-07-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_vendortds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debititem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='debititem',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debititem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='batch',
            field=models.BooleanField(default=False),
        ),
    ]
