# Generated by Django 4.0.1 on 2024-08-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_alter_bill_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill_item',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'bill item'},
        ),
    ]
