# Generated by Django 4.0.1 on 2024-09-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_tds_ext_id_tds_ext_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
