# Generated by Django 4.0.1 on 2024-09-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_alter_bill_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_item',
            name='item_name',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
    ]
