# Generated by Django 4.0.1 on 2024-09-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0031_alter_bill_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tds',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=100),
        ),
        migrations.AlterField(
            model_name='tds',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='tds_receivable_account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='tds_section',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
