# Generated by Django 4.0.1 on 2024-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0034_alter_debititem_batch_no_alter_debititem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='po',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='po',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='account_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='batch_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='item_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='tax_rate',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='tax_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='attach_file',
            field=models.FileField(blank=True, default='null', max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='customer_details',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='destination_place',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='expense_account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='expense_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='expense_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='expense_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='expense_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='gst_treatment',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='hsn_code',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='invoice_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='item_details',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='notes',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='paid_through',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='reporting_tag',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='sac',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='supply_place',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='tax_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='vendor_gstin',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='bill_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='deposit_to',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='destination_of_supply',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='form_type',
            field=models.CharField(blank=True, default='Payment Made', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='paid_through',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='payment_mode',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='payment_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='payment_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='payment_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='pm_method',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='pm_terms',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='terms_condition',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='AmountIncludesVAT',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='From_convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='From_convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='From_convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='From_convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='TermsRefFullName',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='TermsRefListID',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='attach_file',
            field=models.FileField(blank=True, default='null', max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='po',
            name='bill_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='convt_id',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='convt_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='convt_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='convt_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='customer_note',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='discount',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='discount_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='entered_discount',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
        migrations.AlterField(
            model_name='po',
            name='no_of_days',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='po_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='po_serial',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='po_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='shipment_preference',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='sub_total',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='supply_place',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='tcs_amount',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='term_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='terms_condition',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='total',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='item_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='tax_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='tax_rate',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='tax_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='taxamount',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tds',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
        migrations.AlterField(
            model_name='tds',
            name='tds_payable_account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bill_contact_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstin_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='remarks',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='salutation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ship_contact_number',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_mobile',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_department',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_designation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_email',
            field=models.EmailField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_mobile',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_phone',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='contact_salutation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
