# Generated by Django 4.0.1 on 2024-10-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_coacharges_coa_name'),
        ('coa', '0009_basecoa_system_coa_system'),
        ('purchase', '0036_vendor_coa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cess_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_cess', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_cgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='co_charges',
            field=models.ManyToManyField(blank=True, related_name='charges_coa_bill_transaction', to='transaction.CoaCharges'),
        ),
        migrations.AddField(
            model_name='bill',
            name='coa_total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='igst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_igst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_purchase', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_sgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipping_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_shipping', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tcs_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_tcs', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tds_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_tds', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='cess_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_cess', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='cgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_cgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='co_charges',
            field=models.ManyToManyField(blank=True, related_name='charges_coa_dn_transaction', to='transaction.CoaCharges'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='coa_total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='igst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_igst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='purchase_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_purchase', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='sgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_sgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='shipping_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_shipping', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='tcs_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_tcs', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='tds_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_tds', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='co_charges',
            field=models.ManyToManyField(blank=True, related_name='charges_coa_pm_transaction', to='transaction.CoaCharges'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='coa_total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_pm_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='purchase_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_pm_purchase', to='coa.coa'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_bill_discount', to='coa.coa'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='discount_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_dn_discount', to='coa.coa'),
        ),
    ]
