# Generated by Django 4.0.1 on 2024-10-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0037_bill_cess_account_bill_cgst_account_bill_co_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='co_charges',
        ),
    ]
