# Generated by Django 4.0.1 on 2024-10-31 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0038_remove_bill_co_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='co_charges',
        ),
        migrations.RemoveField(
            model_name='paymentmade',
            name='co_charges',
        ),
    ]
