# Generated by Django 4.0.1 on 2024-11-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_consumption_godown_id_consumption_godown_name_and_more'),
        ('purchase', '0039_remove_debitnote_co_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_item',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='bill_item',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='debititem',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.warehouse'),
        ),
        migrations.AddField(
            model_name='debititem',
            name='godown_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
