# Generated by Django 4.0.1 on 2024-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0040_bill_item_godown_id_bill_item_godown_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debititem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='discount_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='total_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
