# Generated by Django 4.0.1 on 2024-11-27 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0041_debititem_discount_debitnote_discount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillView',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_serial', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('bill_ref_no', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('order_no', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('branch_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('payment_status', models.CharField(blank=True, default='null', max_length=200, null=True)),
            ],
            options={
                'db_table': 'bill_view',
                'managed': False,
            },
        ),
    ]
