# Generated by Django 4.0.1 on 2025-09-24 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0042_billview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNoteView',
            fields=[
                ('dn_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('branch_id', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('vendor_name', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('dn_date', models.DateField(blank=True, null=True)),
                ('dn_serial', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('dn_ref_no', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('order_no', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dn_status', models.CharField(blank=True, default='null', max_length=200, null=True)),
            ],
            options={
                'db_table': 'debit_note_view',
                'managed': False,
            },
        ),
    ]
