# Generated by Django 4.0.1 on 2023-11-06 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_company_user'),
        ('salescustomer', '0016_merge_20230913_2258'),
        ('purchase', '0012_merge_20230907_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTransaction',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mast_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('L1detail_id', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('L1detailstbl_name', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('L2detail_id', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('L2detailstbl_name', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('L3detail_id', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('L3detailstbl_name', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('main_module', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('module', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('sub_module', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('transc_deatils', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('banking_module_type', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('journal_module_type', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('trans_status', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('to_account', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('to_acc_type', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('to_acc_head', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('to_acc_subhead', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('to_acc_name', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('from_account', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('from_acc_type', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('from_acc_head', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('from_acc_subhead', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('from_acc_name', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('is_customer', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('comp_yearid', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('attach_file', models.FileField(blank=True, default='null', null=True, upload_to='')),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer')),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor')),
            ],
            options={
                'verbose_name_plural': 'Master_Transaction',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('acc_type', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('acc_head', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('acc_subhead', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('acc_name', models.CharField(blank=True, default='null', max_length=150, null=True)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_ledgers', to='transaction.mastertransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
