# Generated by Django 4.0.1 on 2024-01-02 04:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_invoice_sequence'),
        ('salescustomer', '0021_alter_dc_options_alter_estimate_options_and_more'),
        ('purchase', '0014_alter_paymentmade_options'),
        ('transaction', '0002_alter_mastertransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chg_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('charge_name', models.CharField(blank=True, max_length=50, null=True)),
                ('amt_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate_per', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.bill')),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.invoice')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
