# Generated by Django 4.0.1 on 2024-01-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='total_charge',
        ),
    ]
