# Generated by Django 4.0.1 on 2024-01-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_charges_bill_id_remove_charges_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='amt_qty',
            field=models.CharField(blank=True, choices=[('total', 'total'), ('custom', 'custom')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charges',
            name='rate_per',
            field=models.CharField(blank=True, choices=[('rate', 'rate'), ('percentage', 'percentage')], max_length=50, null=True),
        ),
    ]
