# Generated by Django 4.0.1 on 2024-01-02 05:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salescustomer', '0021_alter_dc_options_alter_estimate_options_and_more'),
        ('purchase', '0014_alter_paymentmade_options'),
        ('transaction', '0005_alter_charges_amt_qty_alter_charges_rate_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTransaction',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chg_transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.bill')),
                ('chg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_transaction', to='transaction.charges')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
