# Generated by Django 4.0.1 on 2024-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_chargetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='charges',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
