# Generated by Django 4.0.1 on 2024-01-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_charges_percentage_charges_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargetransaction',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='chargetransaction',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
