# Generated by Django 4.0.1 on 2024-01-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_expenserecord_options'),
        ('salescustomer', '0027_alter_pr_invoice_id'),
        ('transaction', '0008_alter_chargetransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargetransaction',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_charge_transactions', to='purchase.bill'),
        ),
        migrations.AlterField(
            model_name='chargetransaction',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_charge_transactions', to='salescustomer.invoice'),
        ),
    ]
