# Generated by Django 4.0.1 on 2024-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_chargetransaction_bill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargetransaction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastertransaction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
