# Generated by Django 4.0.1 on 2024-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_mastertransaction_l1detail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='amt_qty',
            field=models.CharField(blank=True, choices=[('total', 'total'), ('custom', 'custom')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='charges',
            name='charge_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='charges',
            name='rate_per',
            field=models.CharField(blank=True, choices=[('rate', 'rate'), ('percentage', 'percentage')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chargetransaction',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='acc_head',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='acc_name',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='acc_subhead',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='acc_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
