# Generated by Django 4.0.1 on 2024-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_charges_amt_qty_alter_charges_charge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertransaction',
            name='batch_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mastertransaction',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertransaction',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
