# Generated by Django 4.0.1 on 2024-10-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0036_vendor_coa_id'),
        ('salescustomer', '0043_salescustomer_coa_id'),
        ('coa', '0009_basecoa_system_coa_system'),
        ('transaction', '0013_mastertransaction_batch_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoaCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('module', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_coa_transactions', to='purchase.bill')),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_charges', to='coa.coa')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_coa_transactions', to='salescustomer.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
