# Generated by Django 4.0.1 on 2024-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_coacharges_delete_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertransaction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
