# Generated by Django 4.0.1 on 2024-10-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0036_vendor_coa_id'),
        ('salescustomer', '0043_salescustomer_coa_id'),
        ('transaction', '0015_mastertransaction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coacharges',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='coacharges',
            name='cn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cn_coa_transactions', to='salescustomer.creditnote'),
        ),
        migrations.AddField(
            model_name='coacharges',
            name='dn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_coa_transactions', to='purchase.debitnote'),
        ),
    ]
