# Generated by Django 4.0.1 on 2024-10-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_coacharges_amount_coacharges_cn_id_coacharges_dn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coacharges',
            name='coa_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
