# Generated by Django 4.0.1 on 2024-10-30 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_coacharges_coa_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coacharges',
            name='id',
        ),
        migrations.AddField(
            model_name='coacharges',
            name='ch_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
