# Generated by Django 4.0.1 on 2024-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_remove_coacharges_id_coacharges_ch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coacharges',
            name='charges_type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('TAX', 'TAX')], default='DEFAULT', max_length=200),
        ),
    ]
