# Generated by Django 4.0.1 on 2024-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_coacharges_charges_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coacharges',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
