# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('banking', '0001_initial'),
        ('salescustomer', '0001_initial'),
        ('purchase', '0001_initial'),
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.bill'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='tds_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.tds'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='ttaa',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='ttaa',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='ttaa',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='ttaa',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='transferfromanotheraccount',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='transferfromanotheraccount',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='transferfromanotheraccount',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='transferfromanotheraccount',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='transferfromanotheraccount',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='cn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.creditnote'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='dn_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.debitnote'),
        ),
        migrations.AddField(
            model_name='refundmaster',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='paymentrefunds',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='paymentrefunds',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='paymentrefunds',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='paymentrefunds',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='paymentrefunds',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='paymentrefunds',
            name='pr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.pr'),
        ),
        migrations.AddField(
            model_name='ownerscontribution',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='ownerscontribution',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='ownerscontribution',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='ownerscontribution',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='ownerdrawing',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='ownerdrawing',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='ownerdrawing',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='ownerdrawing',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.bill'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='interestincome',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='interestincome',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='interestincome',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='interestincome',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='interestincome',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='expenserefund',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='expenserefund',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='expenserefund',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='expenserefund',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='expenserefund',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='dtoa',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='dtoa',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='dtoa',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='dtoa',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='dtoa',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='dfoa',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='dfoa',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='dfoa',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='dfoa',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='dfoa',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.invoice'),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ad', to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.banking'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='banking',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='banking',
            name='coa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa'),
        ),
        migrations.AddField(
            model_name='banking',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankcompany', to='company.company'),
        ),
        migrations.AddField(
            model_name='banking',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
    ]
