# Generated by Django 4.0.1 on 2023-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradvanced',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
