# Generated by Django 4.0.1 on 2024-01-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_vendoradvanced_is_converted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banking',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Banking '},
        ),
    ]
