# Generated by Django 4.0.1 on 2024-02-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_banking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeradvance',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'CustomerAdvanced'},
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='created_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='deleted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='deleted_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='modified_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
