# Generated by Django 4.0.1 on 2024-04-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_customeradvance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendoradvanced',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'VendorAdvanced'},
        ),
    ]
