# Generated by Django 4.0.1 on 2024-11-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0009_basecoa_system_coa_system'),
        ('banking', '0008_alter_ttaa_options_banking_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradvanced',
            name='cgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_va_cgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='igst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_va_igst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='party_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_va_party', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='sgst_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_va_sgst', to='coa.coa'),
        ),
        migrations.AddField(
            model_name='vendoradvanced',
            name='tds_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_va_tds', to='coa.coa'),
        ),
    ]
