from importlib.resources import contents
from multiprocessing import context
from urllib import response
from django.shortcuts import render
from django.http import HttpResponse
import os

from pathlib import Path
from collections import OrderedDict
import datetime
from templates.img_conversion import image_url_to_base64
def est_data(est_response):
    est_response = est_response
    est_response_sadfsa=[OrderedDict([('est_id', '23bf0fba-5db3-4028-9e97-51cf44869fcf'), 
            ('estimate_items', [OrderedDict
                      ([('est_id', ('23bf0fba-5db3-4028-9e97-51cf44869fcf')),
                      ('estitem_id', '650c4ccd-10fb-446f-a377-915b30304c78'), 
                      ('item_name', 'Advance & Refund'), 
                      ('amount', '5000.00'), 
                      ('quantity', '1.00'), 
                      ('rate', '5000.00'), 
                      ('tax_name', 'GST12 [12%]'), 
                      ('taxamount', None), 
                      ('igst_amount', '600.00'), 
                      ('cgst_amount', '300.00'), 
                      ('sgst_amount', '300.00')])]), 
                      ('cgst_total', '300.00'), 
                      ('sgst_total', '300.00'), 
                      ('igst_total', '0.00'), 
                      ('created_id', 'null'), 
                      ('created_date', '2022-05-10T15:25:40.781417+05:30'), 
                      ('modified_id', 'null'), ('modified_date', '2022-05-10T15:25:40.781417+05:30'), 
                      ('deleted_id', 'null'), 
                      ('deleted_date', '2022-05-10T15:25:40.781417+05:30'),
                       ('supply_place', 'Maharashtra'), ('est_serial', 'EST001'), 
                       ('est_ref_no', 'REF-001'), ('est_status', 'Save and Send'), 
                       ('est_date', '2022-05-10'), ('is_estimate_generated', True),
                        ('expiry_date', '2022-05-10'), ('project_name', 'null'), 
                        ('subject', 'Test Estimate PDF View'), 
                        ('total_quantity', None),
                         ('discount', '40.00'), 
                         ('entered_discount', '40.00'), 
                         ('amount', None), 
                         ('sub_total', '5000.00'), 
                         ('shipping_charges', '100.00'), 
                         ('shipping_tax_rate', 0), 
                         ('shipping_tax_name', None), 
                         ('entered_shipping_charges', '100.00'), 
                         ('adjustment', None), ('tcs_amount', '1140.00'), 
                         ('total', '6800.00'), ('total_gst', None), 
                         ('round_off', None), ('tax', 'null'), 
                         ('grand_total', None), 
                         ('customer_note', 'Customer Note is HERE'), 
                         ('terms_condition', 'TERMS & CONDITIONS ARE APPLICABLE'), 
                         ('attach_file', None), 
                         ('convt_type', 'null'), 
                         ('convt_id', 'null'),
                          ('convt_serial', 'null'),
                           ('convt_ref_no', 'null'), 
                           ('is_converted', False), 
                           ('customer_id', 
            OrderedDict([('customer_id', '302739e3-79e7-4fd2-8d59-702414fa96c8'),
            ('created_id', 'null'), ('created_date', '2022-05-10T15:08:46.063882+05:30'), 
            ('modified_id', 'null'), ('modified_date', '2022-05-10T15:08:46.063882+05:30'),
            ('deleted_id', 'null'), ('deleted_date', '2022-05-10T15:08:46.063882+05:30'),
            ('salutation', None), 
            ('customer_name', 'Customer PDF'), 
            ('customer_mobile', '9860896850'), 
            ('company_name', ''), 
            ('customer_display_name', 'Customer PDF'), 
            ('print_as_check_as', False), 
            ('customer_contact', ''), 
            ('customer_email', 'email@example.com'), 
            ('customer_type', 'Business'), 
            ('customer_designation', ''),
                ('customer_department', ''), 
                ('exemption_reason', ''), ('customerRefListId', 'null'), ('customerTypeRefListId', 'null'),
                ('customerTypeReffullName', 'null'), ('is_subcustomer', False), ('parent_customer', 'null'),
                ('enable_portal', True), ('company_display_name', 'null'), ('company_email', 'null'), 
                ('company_number', 'null'), ('website', ''), ('opening_balance', None), ('currency', 'null'),
                ('set_credit_limit', '0.00'), ('gst_treatment', 'Unregistered Business'),
                    ('gstin_number', ''), ('tax_preference', 'Taxable'), ('cin_number', 'null'), 
                    ('trn_number', 'null'), ('vat_number', 'null'), ('pan_number', ''), ('b_attention', ''),
                    ('bill_address1', ''), ('bill_address2', ''), ('bill_address_city', ''), 
                    ('bill_address_state', ''), ('bill_address_postal_code', 0), ('bill_address_country', ''),
                    ('bill_contact_number', ''), ('bill_fax_number', ''), ('s_attention', ''), 
                    ('ship_address1', ''), ('ship_address2', ''), ('ship_address_city', ''), 
                    ('ship_address_state', ''), ('ship_address_postal_code', 0), 
                    ('ship_address_country', ''), ('ship_contact_number', ''), ('ship_fax_number', ''), 
                    ('supply_place', 'Maharashtra'), ('contact_salutation', None), ('contact_name', ''),
                    ('contact_phone', ''), ('contact_mobile', ''), ('contact_email', ''), 
                    ('contact_designation', ''), ('contact_department', ''), ('remarks', ''), 
                    ('term_name', ''), ('no_of_days', 0), 
        ('company_id',('048a4957-39ad-44bd-97ea-f7a044ad4538')), ('branch_id', None)])),
        ('item_id', None), ('emp_id', None), ('so_id', None), ('tcs_id',
    OrderedDict([('tcs_id', '7e8a8ec9-3cce-4a34-bcbb-3b2564e6f399'), 
                ('nature_of_collection', 'Sales of Goods'), ('rate', '20.00'), ('tax_name', 'TCS'),
                ('tcs_payable_account', 'null'), ('tcs_receivable_account', 'null'), ('company_id', None), 
                ('branch_id', None)])), ('invoice_id', None), ('company_id',
    OrderedDict([('company_id', '048a4957-39ad-44bd-97ea-f7a044ad4538'), ('created_id', 'null'), 
                ('created_date', '2022-04-27T17:32:44.842193+05:30'), ('modified_id', 'null'), 
                    ('modified_date', '2022-04-27T17:32:44.842193+05:30'), ('deleted_id', 'null'), 
                    ('deleted_date', '2022-04-27T17:32:44.842193+05:30'), ('trial_company', None), 
                ('company_name', 'CodeRize Technologies Pune'), ('alias_name', ''), ('address', 'Pune'),
                ('locality', ''), ('landmark', ''), ('pincode', 422064), ('city', ''), ('state', 'Maharashtra'), 
                ('other', ''), ('is_primary', True), ('primary_phone_number', ''), 
                ('primary_mobile_number', '995656656566'), ('primary_alternate_number', ''), 
                ('primary_email', 'coderize@gmail.com'), ('secondary_phone_number', ''), 
                ('secondary_mobile_number', ''), ('secondary_alternate_number', ''), ('secondary_email', ''), 
            ('website', ''), ('books_start_date', '2022-04-01'), ('method', 'null'), ('company_type', 'Private'), 
            ('pan_number', 'CODE121212'), ('gstin', ''), ('cin', ''), ('other_registration_number', ''), 
            ('password', '584587587'), ('security_control', 'false'), ('audit_feature', 'true'),
                ('logo_image', '/media/null'), ('report_basis', 'null'), ('company_edit_id', 'null'), 
            ('tax_edit_id', 'null'), ('separate_payment_address', 'False'), ('address_receive_payment', 'null')])),
            ('branch_id', None)])]
    {'company_name': 'CodeRize Technologies Pune', 
    'address': 'Pune', 
    'city': '', 'gst_in': '', 
    'estimate_serial': 'EST001', 
    'expiry_date': '2022-05-10', 
    'invoice_serial': '', 
    'estimate_date': '2022-05-10', 
    'place_of_supply': 'Maharashtra', 
    'estimate_items': [{'est_id':('23bf0fba-5db3-4028-9e97-51cf44869fcf'), 
                    'estitem_id': '650c4ccd-10fb-446f-a377-915b30304c78', 
                    'item_name': 'Advance & Refund', 
                    'amount': '5000.00', 'quantity': '1.00', 
                    'rate': '5000.00', 
                    'tax_name': 'GST12 [12%]', 
                    'taxamount': None,
                    'igst_amount': '600.00', 
                    'cgst_amount': '300.00', 
                    'sgst_amount': '300.00'}], 
        'sub_total': '5000.00', 
        'discount': '40.00', 
        'cgst_0': '', 
        'itemdescription': '',
        'sgst0_0': '',
        'cgst25_25': '300.00',
        'total': '6800.00', 
        'igst_total': '0.00', 
        'customer_note': 'Customer Note is HERE',
        'sgst25_25': '',
        'cgst6_6': '',
            'sgst6_6': '', 
            'cgst9_9': '', 
            'sgst9_9': '300.00', 
        'shipping_charges': '100.00',
        'credit_remaining': '', 
        'customer_name': 'Customer PDF'}

    contents={
        "company_name":est_response['company_id']['company_name'],
        "address":est_response['company_id']['address'],
        "city":est_response['company_id']['city'],
        "gst_in":est_response['company_id']['gstin'],
        "estimate_serial":est_response['est_serial'],
        "expiry_date":est_response['expiry_date'],
        "invoice_serial":'',
        "estimate_date":est_response['est_date'], 
        "place_of_supply":est_response['supply_place'],
        'estimate_items': [dict(a) for a in est_response['estimate_items']],
        "sub_total":est_response['sub_total'],
        "discount":est_response['discount'],
        "total_in_words":'',
        "cgst_0":'',
        "itemdescription":'',
        "sgst0_0":'',
        "cgst25_25":est_response['cgst_total'],
        "total":est_response['total'],
        "igst_total":est_response['igst_total'],
        "tcs":est_response['tcs_amount'],
        "sgst9_9":est_response['sgst_total'],
        "shipping_charges":est_response['shipping_charges'],
        "customer_note":est_response['customer_note'],
        "total":est_response['total'],
        "credit_remaining":'',
        "customer_name":est_response['customer_id']['customer_name'],
    }
    print(contents)
    return contents

if __name__ == '__main__':
    est_Response = [OrderedDict([('est_id', '23bf0fba-5db3-4028-9e97-51cf44869fcf'), 
            ('estimate_items', [OrderedDict
                      ([('est_id', ('23bf0fba-5db3-4028-9e97-51cf44869fcf')),
                      ('estitem_id', '650c4ccd-10fb-446f-a377-915b30304c78'), 
                      ('item_name', 'Advance & Refund'), 
                      ('amount', '5000.00'), 
                      ('quantity', '1.00'), 
                      ('rate', '5000.00'), 
                      ('tax_name', 'GST12 [12%]'), 
                      ('taxamount', None), 
                      ('igst_amount', '600.00'), 
                      ('cgst_amount', '300.00'), 
                      ('sgst_amount', '300.00')])]), 
                      ('cgst_total', '300.00'), 
                      ('sgst_total', '300.00'), 
                      ('igst_total', '0.00'), 
                      ('created_id', 'null'), 
                      ('created_date', '2022-05-10T15:25:40.781417+05:30'), 
                      ('modified_id', 'null'), ('modified_date', '2022-05-10T15:25:40.781417+05:30'), 
                      ('deleted_id', 'null'), 
                      ('deleted_date', '2022-05-10T15:25:40.781417+05:30'),
                       ('supply_place', 'Maharashtra'), ('est_serial', 'EST001'), 
                       ('est_ref_no', 'REF-001'), ('est_status', 'Save and Send'), 
                       ('est_date', '2022-05-10'), ('is_estimate_generated', True),
                        ('expiry_date', '2022-05-10'), ('project_name', 'null'), 
                        ('subject', 'Test Estimate PDF View'), 
                        ('total_quantity', None),
                         ('discount', '40.00'), 
                         ('entered_discount', '40.00'), 
                         ('amount', None), 
                         ('sub_total', '5000.00'), 
                         ('shipping_charges', '100.00'), 
                         ('shipping_tax_rate', 0), 
                         ('shipping_tax_name', None), 
                         ('entered_shipping_charges', '100.00'), 
                         ('adjustment', None), ('tcs_amount', '1140.00'), 
                         ('total', '6800.00'), ('total_gst', None), 
                         ('round_off', None), ('tax', 'null'), 
                         ('grand_total', None), 
                         ('customer_note', 'Customer Note is HERE'), 
                         ('terms_condition', 'TERMS & CONDITIONS ARE APPLICABLE'), 
                         ('attach_file', None), 
                         ('convt_type', 'null'), 
                         ('convt_id', 'null'),
                          ('convt_serial', 'null'),
                           ('convt_ref_no', 'null'), 
                           ('is_converted', False), 
                           ('customer_id', 
            OrderedDict([('customer_id', '302739e3-79e7-4fd2-8d59-702414fa96c8'),
            ('created_id', 'null'), ('created_date', '2022-05-10T15:08:46.063882+05:30'), 
            ('modified_id', 'null'), ('modified_date', '2022-05-10T15:08:46.063882+05:30'),
            ('deleted_id', 'null'), ('deleted_date', '2022-05-10T15:08:46.063882+05:30'),
            ('salutation', None), 
            ('customer_name', 'Customer PDF'), 
            ('customer_mobile', '9860896850'), 
            ('company_name', ''), 
            ('customer_display_name', 'Customer PDF'), 
            ('print_as_check_as', False), 
            ('customer_contact', ''), 
            ('customer_email', 'email@example.com'), 
            ('customer_type', 'Business'), 
            ('customer_designation', ''),
                ('customer_department', ''), 
                ('exemption_reason', ''), ('customerRefListId', 'null'), ('customerTypeRefListId', 'null'),
                ('customerTypeReffullName', 'null'), ('is_subcustomer', False), ('parent_customer', 'null'),
                ('enable_portal', True), ('company_display_name', 'null'), ('company_email', 'null'), 
                ('company_number', 'null'), ('website', ''), ('opening_balance', None), ('currency', 'null'),
                ('set_credit_limit', '0.00'), ('gst_treatment', 'Unregistered Business'),
                    ('gstin_number', ''), ('tax_preference', 'Taxable'), ('cin_number', 'null'), 
                    ('trn_number', 'null'), ('vat_number', 'null'), ('pan_number', ''), ('b_attention', ''),
                    ('bill_address1', ''), ('bill_address2', ''), ('bill_address_city', ''), 
                    ('bill_address_state', ''), ('bill_address_postal_code', 0), ('bill_address_country', ''),
                    ('bill_contact_number', ''), ('bill_fax_number', ''), ('s_attention', ''), 
                    ('ship_address1', ''), ('ship_address2', ''), ('ship_address_city', ''), 
                    ('ship_address_state', ''), ('ship_address_postal_code', 0), 
                    ('ship_address_country', ''), ('ship_contact_number', ''), ('ship_fax_number', ''), 
                    ('supply_place', 'Maharashtra'), ('contact_salutation', None), ('contact_name', ''),
                    ('contact_phone', ''), ('contact_mobile', ''), ('contact_email', ''), 
                    ('contact_designation', ''), ('contact_department', ''), ('remarks', ''), 
                    ('term_name', ''), ('no_of_days', 0), 
        ('company_id', ('048a4957-39ad-44bd-97ea-f7a044ad4538')), ('branch_id', None)])),
        ('item_id', None), ('emp_id', None), ('so_id', None), ('tcs_id',
    OrderedDict([('tcs_id', '7e8a8ec9-3cce-4a34-bcbb-3b2564e6f399'), 
    ('nature_of_collection', 'Sales of Goods'), ('rate', '20.00'), ('tax_name', 'TCS'),
    ('tcs_payable_account', 'null'), ('tcs_receivable_account', 'null'), ('company_id', None), 
    ('branch_id', None)])), ('invoice_id', None), ('company_id',
    OrderedDict([('company_id', '048a4957-39ad-44bd-97ea-f7a044ad4538'), ('created_id', 'null'), 
    ('created_date', '2022-04-27T17:32:44.842193+05:30'), ('modified_id', 'null'), 
    ('modified_date', '2022-04-27T17:32:44.842193+05:30'), ('deleted_id', 'null'), 
    ('deleted_date', '2022-04-27T17:32:44.842193+05:30'), ('trial_company', None), 
    ('company_name', 'CodeRize Technologies Pune'), ('alias_name', ''), ('address', 'Pune'),
    ('locality', ''), ('landmark', ''), ('pincode', 422064), ('city', ''), ('state', 'Maharashtra'), 
    ('other', ''), ('is_primary', True), ('primary_phone_number', ''), 
    ('primary_mobile_number', '995656656566'), ('primary_alternate_number', ''), 
    ('primary_email', 'coderize@gmail.com'), ('secondary_phone_number', ''), 
    ('secondary_mobile_number', ''), ('secondary_alternate_number', ''), ('secondary_email', ''), 
    ('website', ''), ('books_start_date', '2022-04-01'), ('method', 'null'), ('company_type', 'Private'), 
    ('pan_number', 'CODE121212'), ('gstin', ''), ('cin', ''), ('other_registration_number', ''), 
    ('password', '584587587'), ('security_control', 'false'), ('audit_feature', 'true'),
    ('logo_image', '/media/null'), ('report_basis', 'null'), ('company_edit_id', 'null'), 
    ('tax_edit_id', 'null'), ('separate_payment_address', 'False'), ('address_receive_payment', 'null')])),
        ('branch_id', None)])]
    {'company_name': 'CodeRize Technologies Pune', 
    'address': 'Pune', 
    'city': '', 'gst_in': '', 'estimate_serial': 'EST001', 'expiry_date': '2022-05-10', 
    'invoice_serial': '', 'estimate_date': '2022-05-10', 
    'place_of_supply': 'Maharashtra', 
    'estimate_items': [{'est_id': ('23bf0fba-5db3-4028-9e97-51cf44869fcf'), 
                    'estitem_id': '650c4ccd-10fb-446f-a377-915b30304c78', 
                    'item_name': 'Advance & Refund', 
                    'amount': '5000.00', 'quantity': '1.00', 
                    'rate': '5000.00', 
                    'tax_name': 'GST12 [12%]', 
                    'taxamount': None,
                    'igst_amount': '600.00', 
                    'cgst_amount': '300.00', 
                    'sgst_amount': '300.00'}], 
        'sub_total': '5000.00', 
        'discount': '40.00', 
        'cgst_0': '', 
        'itemdescription': '',
        'sgst0_0': '',
        'cgst25_25': '300.00',
        'total': '6800.00', 
        'igst_total': '0.00', 
        'customer_note': 'Customer Note is HERE',
        'sgst25_25': '',
        'cgst6_6': '',
            'sgst6_6': '', 
            'cgst9_9': '', 
            'sgst9_9': '300.00', 
        'shipping_charges': '100.00',
        'credit_remaining': '', 
        'customer_name': 'Customer PDF'}

    a = est_data( est_Response )
    print(a)


# api to generate credit note pdf
def generate_estimate_pdf(data):

    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'] )
    html =  render(None, "core/estimate.html",data)
    return html