
from templates.img_conversion import image_url_to_base64

from django.shortcuts import render
from collections import OrderedDict
import datetime

def pr_data(pr_response):
    pr_response = pr_response[0]
    fyjgh=[OrderedDict([('pr_id', '059bdf37-3408-487d-9656-70443e82501a'),
             ('payment_serial','PR0020'),
              ('amount_excess', '0.00'), 
              ('payment_ref_no', ''), 
              ('invoice_serial', 'INV434343'),
               ('invoice_amount', '5200.00'), 
               ('balance_amount', '300.00'),
                ('payment_date', '2022-03-28'), 
                ('payment_mode', 'cash'), 
                ('amount_received', '4500.00'),
        ('customer_id', OrderedDict([('customer_id', '9efee1d4-81a4-4761-b39f-8d99042819de'), 
                                    ('created_id', 'null'), 
                                    ('created_date', '2022-04-09T15:18:32.961663+05:30'), 
                                    ('modified_id', 'null'), 
                                    ('modified_date', '2022-04-09T15:18:32.961663+05:30'), 
                                    ('deleted_id', 'null'), 
                                    ('deleted_date', '2022-04-09T15:18:32.961663+05:30'), 
                                    ('salutation', None), 
                                    ('customer_name', 'Mr Sham Patil'), 
                                    ('customer_mobile', '9921447210'),
                                     ('company_name', ''), 
                                     ('customer_display_name', 'Mr Sham Patil'), 
                                     ('print_as_check_as', False),
                                      ('customer_contact', ''), 
                                      ('customer_email', 'sham@gmail.com'), 
                                      ('customer_type', 'Business'), 
                                      ('customer_designation', ''),
                                       ('customer_department', ''), 
                                       ('exemption_reason', ''), 
                                       ('customerRefListId', 'null'), 
                                       ('customerTypeRefListId', 'null'),
                                        ('customerTypeReffullName', 'null'), 
                                        ('is_subcustomer', False), 
                                        ('parent_customer', 'null'), 
                                        ('enable_portal', True), 
                                        ('company_display_name', 'null'),
                                         ('company_email', 'null'), 
                                         ('company_number', 'null'), 
                                         ('website', ''), 
                                         ('opening_balance', None), 
                                         ('currency', 'null'), 
                                         ('set_credit_limit', '0.00'), 
                                         ('gst_treatment', 'Registered Business - Regular'),
                                          ('gstin_number', 'SHMA@1223333322'),
                                           ('tax_preference', 'Taxable'),
                                            ('cin_number', 'null'),
                                             ('trn_number', 'null'),
                                              ('vat_number', 'null'),
                                               ('pan_number', ''), 
                                               ('b_attention', ''), 
                                               ('bill_address1', ''), 
                                               ('bill_address2', ''), 
                                               ('bill_address_city', ''), 
                                               ('bill_address_state', ''), 
                                               ('bill_address_postal_code', 0), 
                                               ('bill_address_country', ''), 
                                               ('bill_contact_number', ''),
                                                ('bill_fax_number', ''), 
                                                ('s_attention', ''),
                                                 ('ship_address1', ''),
                                                  ('ship_address2', ''),
                                                   ('ship_address_city', ''), 
                                                   ('ship_address_state', ''), 
                                                   ('ship_address_postal_code', 0),
                                                   ('ship_address_country', ''), 
                                                   ('ship_contact_number', ''), 
                                                   ('ship_fax_number', ''), 
                                                   ('supply_place', 'Maharashtra'),
                                                    ('contact_salutation', None), 
                                                    ('contact_name', ''), 
                                                    ('contact_phone', ''), 
                                                    ('contact_mobile', ''),
                                                     ('contact_email', ''), 
                                                     ('contact_designation', ''), 
                                                     ('contact_department', ''), 
                                                     ('remarks', ''), ('term_name', ''), 
                                                     ('no_of_days', 0), 
                                                    ('company_id', ('ea138e80-4746-4d28-a85e-f3153c96b86e')), ('branch_id', None)])), ('company_id', OrderedDict([('company_id', 'ea138e80-4746-4d28-a85e-f3153c96b86e'), 
                                                    ('created_id', 'null'), ('created_date', '2022-04-09T15:16:43.130598+05:30'), 
                                                    ('modified_id', 'null'), ('modified_date', '2022-04-09T15:16:43.130598+05:30'), 
                                                    ('deleted_id', 'null'),
                                                    ('deleted_date', '2022-04-09T15:16:43.130598+05:30'),
                                                    ('trial_company', None), 
                                                    ('company_name', 'CodeRize Test'),
                                                      ('alias_name', ''), 
                                                    ('address', 'Pune'), 
                                                    ('locality', ''),
                                                    ('landmark', ''), ('pincode', 121223),
                                                      ('city', ''), ('state', 'Maharashtra'), 
                                                    ('other', ''), ('is_primary', True), 
                                                    ('primary_phone_number', ''), 
                                                    ('primary_mobile_number', '956565656565'),
                                                    ('primary_alternate_number', ''), 
                                                    ('primary_email', 'coderize@gmail.com'),
                                                    ('secondary_phone_number', ''),
                                                    ('secondary_mobile_number', ''), ('secondary_alternate_number', ''), 
                                                    ('secondary_email', ''), ('website', ''), 
                                                    ('books_start_date', '2022-04-01'), 
                                                    ('method', 'null'), ('company_type', 'Private'), 
                                                    ('pan_number', 'Coderize12'), 
                                                    ('gstin', ''), ('cin', ''), ('other_registration_number', ''), ('password', '584587587'), 
                                                    ('security_control', 'false'), ('audit_feature', 'true'), ('logo_image', '/media/null'), 
                                                    ('report_basis', 'null'), ('company_edit_id', 'null'), ('tax_edit_id', 'null'), 
                                                    ('separate_payment_address', 'False'), ('address_receive_payment', 'null')])), 
                                                    ('branch_id', None)])]
                                                      
   
    contents={

        "company_name":pr_response['company_id']['company_name'],
        "address":pr_response['company_id']['address'],
        "city":pr_response['company_id']['city'],
        "gst_in":pr_response['company_id']['gstin'],
        "payment_serial":pr_response['payment_serial'],
        "payment_date":datetime.datetime.strptime(pr_response['payment_date'], "%Y-%m-%d").date(),
        "payment_mode":pr_response['payment_mode'],
        "amount_received":pr_response['amount_received'],
       "invoice_serial":pr_response['invoice_serial'],
       "invoice_amount":pr_response['invoice_amount'],
        "place_of_supply":pr_response['customer_id']['supply_place'],
        "cgst_0":'',
        "payment_ref_no":pr_response['payment_ref_no'],
        "itemdescription":'',
        "sgst0_0":'',

        "sgst25_25":'',
        "cgst6_6":'',
        "sgst6_6":'',
        "cgst9_9":'',
        
        "total":'',
        "credit_remaining":'',
        "customer_name":pr_response['customer_id']['customer_name'],
        
    }
    print("''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''",contents)
    return contents

if __name__ == '__main__':
  pr_Response=[OrderedDict([('pr_id', '059bdf37-3408-487d-9656-70443e82501a'),
             ('payment_serial','PR0020'),
              ('amount_excess', '0.00'), 
              ('payment_ref_no', ''), 
              ('invoice_serial', 'INV434343'),
               ('invoice_amount', '5200.00'), 
               ('balance_amount', '300.00'),
                ('payment_date', '2022-03-28'), 
                ('payment_mode', 'cash'), 
                ('amount_received', '4500.00'),
        ('customer_id', OrderedDict([('customer_id', '9efee1d4-81a4-4761-b39f-8d99042819de'), 
                                    ('created_id', 'null'), 
                                    ('created_date', '2022-04-09T15:18:32.961663+05:30'), 
                                    ('modified_id', 'null'), 
                                    ('modified_date', '2022-04-09T15:18:32.961663+05:30'), 
                                    ('deleted_id', 'null'), 
                                    ('deleted_date', '2022-04-09T15:18:32.961663+05:30'), 
                                    ('salutation', None), 
                                    ('customer_name', 'Mr Sham Patil'), 
                                    ('customer_mobile', '9921447210'),
                                     ('company_name', ''), 
                                     ('customer_display_name', 'Mr Sham Patil'), 
                                     ('print_as_check_as', False),
                                      ('customer_contact', ''), 
                                      ('customer_email', 'sham@gmail.com'), 
                                      ('customer_type', 'Business'), 
                                      ('customer_designation', ''),
                                       ('customer_department', ''), 
                                       ('exemption_reason', ''), 
                                       ('customerRefListId', 'null'), 
                                       ('customerTypeRefListId', 'null'),
                                        ('customerTypeReffullName', 'null'), 
                                        ('is_subcustomer', False), 
                                        ('parent_customer', 'null'), 
                                        ('enable_portal', True), 
                                        ('company_display_name', 'null'),
                                         ('company_email', 'null'), 
                                         ('company_number', 'null'), 
                                         ('website', ''), 
                                         ('opening_balance', None), 
                                         ('currency', 'null'), 
                                         ('set_credit_limit', '0.00'), 
                                         ('gst_treatment', 'Registered Business - Regular'),
                                          ('gstin_number', 'SHMA@1223333322'),
                                           ('tax_preference', 'Taxable'),
                                            ('cin_number', 'null'),
                                             ('trn_number', 'null'),
                                              ('vat_number', 'null'),
                                               ('pan_number', ''), 
                                               ('b_attention', ''), 
                                               ('bill_address1', ''), 
                                               ('bill_address2', ''), 
                                               ('bill_address_city', ''), 
                                               ('bill_address_state', ''), 
                                               ('bill_address_postal_code', 0), 
                                               ('bill_address_country', ''), 
                                               ('bill_contact_number', ''),
                                                ('bill_fax_number', ''), 
                                                ('s_attention', ''),
                                                 ('ship_address1', ''),
                                                  ('ship_address2', ''),
                                                   ('ship_address_city', ''), 
                                                   ('ship_address_state', ''), 
                                                   ('ship_address_postal_code', 0),
                                                   ('ship_address_country', ''), 
                                                   ('ship_contact_number', ''), 
                                                   ('ship_fax_number', ''), 
                                                   ('supply_place', 'Maharashtra'),
                                                    ('contact_salutation', None), 
                                                    ('contact_name', ''), 
                                                    ('contact_phone', ''), 
                                                    ('contact_mobile', ''),
                                                     ('contact_email', ''), 
                                                     ('contact_designation', ''), 
                                                     ('contact_department', ''), 
                                                     ('remarks', ''), ('term_name', ''), 
                                                     ('no_of_days', 0), 
                                                    ('company_id', ('ea138e80-4746-4d28-a85e-f3153c96b86e')), ('branch_id', None)])), ('company_id', OrderedDict([('company_id', 'ea138e80-4746-4d28-a85e-f3153c96b86e'), 
                                                    ('created_id', 'null'), ('created_date', '2022-04-09T15:16:43.130598+05:30'), 
                                                    ('modified_id', 'null'), ('modified_date', '2022-04-09T15:16:43.130598+05:30'), 
              ('deleted_id', 'null'),
              ('deleted_date', '2022-04-09T15:16:43.130598+05:30'),
              ('trial_company', None), 
              ('company_name', 'CodeRize Test'),
                ('alias_name', ''), 
              ('address', 'Pune'), 
              ('locality', ''),
              ('landmark', ''), ('pincode', 121223),
                ('city', ''), ('state', 'Maharashtra'), 
              ('other', ''), ('is_primary', True), 
              ('primary_phone_number', ''), 
              ('primary_mobile_number', '956565656565'),
              ('primary_alternate_number', ''), 
              ('primary_email', 'coderize@gmail.com'),
              ('secondary_phone_number', ''),
              ('secondary_mobile_number', ''), ('secondary_alternate_number', ''), 
              ('secondary_email', ''), ('website', ''), 
              ('books_start_date', '2022-04-01'), 
              ('method', 'null'), ('company_type', 'Private'), 
              ('pan_number', 'Coderize12'), 
              ('gstin', ''), ('cin', ''), ('other_registration_number', ''), ('password', '584587587'), 
              ('security_control', 'false'), ('audit_feature', 'true'), ('logo_image', '/media/null'), 
              ('report_basis', 'null'), ('company_edit_id', 'null'), ('tax_edit_id', 'null'), 
              ('separate_payment_address', 'False'), ('address_receive_payment', 'null')])), 
              ('branch_id', None)])]

  a = pr_data(pr_Response)
  
 # print(a)


# api to generate credit note pdf
def generate_pr_pdf(data):
    print(data['company_id']['logo_image'])
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html =  render(None, "core/pr.html",data)
    return html