from importlib.resources import contents
from multiprocessing import context
from urllib import response
from django.shortcuts import render
from templates.img_conversion import image_url_to_base64
import os
from pathlib import Path
import datetime
def dc_data(dc_response):
    dc_response = dc_response[0]
    dc_response_fdasafd=[
    {
        "dc_id": "921021c4-bcba-4681-9a49-4f2ed0d8b2ee",
        "dc_items": [
            {
                "dc_id": "921021c4-bcba-4681-9a49-4f2ed0d8b2ee",
                "dcitem_id": "6641ad61-7ebd-4580-84d9-7ef792ed2e92",
                "item_name": "Test Item 2",
                "taxamount": None,
                "amount": "1500.00",
                "quantity": "1.00",
                "rate": "1500.00",
                "tax_name": "IGST5 [5%]",
                "cgst_amount": "37.50",
                "sgst_amount": "37.50",
                "igst_amount": "75.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "75.00",
        "created_id": "None",
        "created_date": "2022-03-06T22:20:19.436001+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-06T22:20:19.436001+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-06T22:20:19.436001+05:30",
        "is_converted": False,
        "is_dc_generated": True,
        "customer_note": "",
        "dc_ref_no": "25",
        "dc_date": "2022-03-07T00:00:00+05:30",
        "dc_serial": "1454",
        "dc_status": "Save and Send",
        "dc_type": "Job Work",
        "supply_place": "Goa",
        "terms_name": "None",
        "so_delete": "None",
        "emp_role": "None",
        "subject": "None",
        "item_name": "None",
        "quantity": None,
        "rate": None,
        "discount": "20.00",
        "entered_discount": "20.00",
        "amount": None,
        "sub_total": "1500.00",
        "total_gst": "0.00",
        "total_quantity": None,
        "shipping_charges": "20.00",
        "shipping_tax_name": "IGST5 [5%]",
        "entered_shipping_charges": "20.00",
        "adjustment": None,
        "round_off": 0,
        "total": "1575.00",
        "terms_condition": "",
        "attach_file": None,
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "invoice_id": None,
        "so_id": None,
        "customer_id": {
            "customer_id": "27c60af3-975a-42d5-8ff1-c010f1135459",
            "created_id": "None",
            "created_date": "2022-03-05T16:59:04.821344+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-05T16:59:04.821344+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-05T16:59:04.821344+05:30",
            "salutation": None,
            "customer_name": "Test Customer Master Transactions",
            "customer_mobile": "8090708050",
            "company_name": "",
            "customer_display_name": "Test Customer Master Transactions",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "example@email.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "est_id": None,
        "emp_id": None,
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None
    }
]
    contents={

        "company_name":dc_response['company_id']['company_name'],
        "address":dc_response['company_id']['address'],
        "city":dc_response['company_id']['city'],
        "gst_in":dc_response['company_id']['gstin'],
        "dc_serial":dc_response['dc_serial'],
        "dc_date":datetime.datetime.strptime(dc_response['dc_date'], "%Y-%m-%dT%H:%M:%S%z").date(),
        "invoice_serial":'',
        "invoice_date":'',
        "place_of_supply":dc_response['supply_place'],
        "sub_total":dc_response['sub_total'],
        "discount":dc_response['discount'],
        "total_in_words":'',
        "dc_ref_no":dc_response['dc_ref_no'],
        "cgst_0":'',
        "itemdescription":'',
        "sgst0_0":'',
        "cgst_total":dc_response['cgst_total'],
        "igst_total":dc_response['igst_total'],
        "customer_note":dc_response['customer_note'],
        "sgst_total":dc_response['sgst_total'],
       # "tcs":dc_response['tcs_amount'],
        "sgst_total":dc_response['sgst_total'],
        "shipping_charges":dc_response['shipping_charges'],
        "total":dc_response['total'],
        "credit_remaining":'',
        "customer_name":dc_response['customer_id']['customer_name'],
         #and convert a order dict into dict
        'dc_items': [dict(a) for a in dc_response['dc_items']],
    }
    print(contents)
    return contents

if __name__ == '__main__':
    dc_Response=[
    {
        "dc_id": "921021c4-bcba-4681-9a49-4f2ed0d8b2ee",
        "dc_items": [
            {
                "dc_id": "921021c4-bcba-4681-9a49-4f2ed0d8b2ee",
                "dcitem_id": "6641ad61-7ebd-4580-84d9-7ef792ed2e92",
                "item_name": "Test Item 2",
                "taxamount": None,
                "amount": "1500.00",
                "quantity": "1.00",
                "rate": "1500.00",
                "tax_name": "IGST5 [5%]",
                "cgst_amount": "37.50",
                "sgst_amount": "37.50",
                "igst_amount": "75.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "75.00",
        "created_id": "None",
        "created_date": "2022-03-06T22:20:19.436001+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-06T22:20:19.436001+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-06T22:20:19.436001+05:30",
        "is_converted": False,
        "is_dc_generated": True,
        "customer_note": "",
        "dc_ref_no": "25",
        "dc_date": "2022-03-07T00:00:00+05:30",
        "dc_serial": "1454",
        "dc_status": "Save and Send",
        "dc_type": "Job Work",
        "supply_place": "Goa",
        "terms_name": "None",
        "so_delete": "None",
        "emp_role": "None",
        "subject": "None",
        "item_name": "None",
        "quantity": None,
        "rate": None,
        "discount": "20.00",
        "entered_discount": "20.00",
        "amount": None,
        "sub_total": "1500.00",
        "total_gst": "0.00",
        "total_quantity": None,
        "shipping_charges": "20.00",
        "shipping_tax_name": "IGST5 [5%]",
        "entered_shipping_charges": "20.00",
        "adjustment": None,
        "round_off": 0,
        "total": "1575.00",
        "terms_condition": "",
        "attach_file": None,
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "invoice_id": None,
        "so_id": None,
        "customer_id": {
            "customer_id": "27c60af3-975a-42d5-8ff1-c010f1135459",
            "created_id": "None",
            "created_date": "2022-03-05T16:59:04.821344+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-05T16:59:04.821344+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-05T16:59:04.821344+05:30",
            "salutation": None,
            "customer_name": "Test Customer Master Transactions",
            "customer_mobile": "8090708050",
            "company_name": "",
            "customer_display_name": "Test Customer Master Transactions",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "example@email.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "est_id": None,
        "emp_id": None,
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None
    }
]
    a = dc_data(dc_Response)
    print(a)


# api to generate credit note pdf
def generate_dc_pdf(data):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html =  render(None, "core/dc.html",data)
    return html