from importlib.resources import contents
from multiprocessing import context
from urllib import response
import os
from pathlib import Path

from django.shortcuts import render
import datetime


def customer_adavnce_data(customer_advance_response):

    customer_advance= {
        "ca_id": "d31821cd-6f66-4794-9b8f-b5398260e1af",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "is_customer_advance_generated": True,
        "status": "Manually Added",
        "gst_treatment": "None",
        "gstin_no": "None",
        "supply_place": "Maharashtra",
        "balance_amount": "1231.00",
        "amount_received": "1231.00",
        "customer_advance_date": "2022-05-06",
        "customer_advance_ref_no": None,
        "received_via": "Cash",
        "description": "None",
        "description_supply": None,
        "bank_charges": None,
        "payment_serial": "PR2121",
        "tax_rate": "0.00",
        "tax_name": None,
        "tax_type": None,
        "tax_amount": "0.00",
        "attach_file": None,
        "is_bank_transaction": False,
        "company_id": {
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "created_id": "None",
            "created_date": "2022-04-27T17:32:44.842193+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:32:44.842193+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:32:44.842193+05:30",
            "trial_company": None,
            "company_name": "CodeRize Technologies Pune",
            "alias_name": "",
            "address": "Pune",
            "locality": "",
            "landmark": "",
            "pincode": 422064,
            "city": "",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "",
            "primary_mobile_number": "995656656566",
            "primary_alternate_number": "",
            "primary_email": "coderize@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "",
            "website": "",
            "books_start_date": "2022-04-01",
            "method": "None",
            "company_type": "Private",
            "pan_number": "CODE121212",
            "gstin": "",
            "cin": "",
            "other_registration_number": "",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "https://products.coderize.in:8002/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "coa_id": {
            "coa_id": "ad32e312-24f4-48c9-ab98-1ee23dd3f1c5",
            "created_id": "None",
            "created_date": "2022-05-04T16:45:28.051537+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:45:28.051537+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:45:28.051537+05:30",
            "account_type": "Assets",
            "account_head": "Current Assets",
            "account_subhead": "Cash",
            "account_name": "Petty Cash",
            "account_code": None,
            "description": None,
            "add_to_watchlist_on_my_dashboard": None,
            "mark_this_is_sub_account": None,
            "is_child_allowed": None,
            "parent_account": None,
            "parent_id": "None",
            "ListID": None,
            "EditSequence": None,
            "Name": None,
            "FullName": None,
            "IsActive": False,
            "ParentRefListID": None,
            "ParentRefFullName": None,
            "Sublevel": None,
            "SpecialAccountType": None,
            "IsTaxAccount": False,
            "AccountNumber": None,
            "BankNumber": None,
            "Balance": 0.0,
            "TotalBalance": 0.0,
            "OpenBalance": 0.0,
            "OpenBalanceDate": None,
            "SalesTaxCodeRefListID": None,
            "SalesTaxCodeRefFullName": None,
            "TaxCodeRefListID": None,
            "TaxCodeRefFullName": None,
            "TaxLineInfoRetTaxLineID": None,
            "TaxLineInfoRetTaxLineName": None,
            "CashFlowClassification": None,
            "CurrencyRefListID": None,
            "CurrencyRefFullName": None,
            "isdefault": False,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        },
        "bank_id": None,
        "customer_id": {
            "customer_id": "0cb4820c-1aa9-4a4d-810e-ce493cb3fba4",
            "created_id": "None",
            "created_date": "2022-05-04T16:41:35.428236+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:41:35.428236+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:41:35.428236+05:30",
            "salutation": None,
            "customer_name": "Cust Advance",
            "customer_mobile": "8899889966",
            "company_name": "",
            "customer_display_name": "Cust Advance",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "email@example.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        }
    },
    {
        "ca_id": "44143641-2997-45b4-bdfa-69eeb49f042b",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "is_customer_advance_generated": True,
        "status": "Manually Added",
        "gst_treatment": "None",
        "gstin_no": "None",
        "supply_place": None,
        "balance_amount": "1212.00",
        "amount_received": "1212.00",
        "customer_advance_date": "2022-05-06",
        "customer_advance_ref_no": "REF-2122",
        "received_via": "Cash",
        "description": "None",
        "description_supply": "Test Description",
        "bank_charges": None,
        "payment_serial": "PR2122",
        "tax_rate": "0.00",
        "tax_name": None,
        "tax_type": None,
        "tax_amount": "0.00",
        "attach_file": None,
        "is_bank_transaction": False,
        "company_id": {
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "created_id": "None",
            "created_date": "2022-04-27T17:32:44.842193+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:32:44.842193+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:32:44.842193+05:30",
            "trial_company": None,
            "company_name": "CodeRize Technologies Pune",
            "alias_name": "",
            "address": "Pune",
            "locality": "",
            "landmark": "",
            "pincode": 422064,
            "city": "",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "",
            "primary_mobile_number": "995656656566",
            "primary_alternate_number": "",
            "primary_email": "coderize@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "",
            "website": "",
            "books_start_date": "2022-04-01",
            "method": "None",
            "company_type": "Private",
            "pan_number": "CODE121212",
            "gstin": "",
            "cin": "",
            "other_registration_number": "",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "https://products.coderize.in:8002/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "coa_id": {
            "coa_id": "ad32e312-24f4-48c9-ab98-1ee23dd3f1c5",
            "created_id": "None",
            "created_date": "2022-05-04T16:45:28.051537+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:45:28.051537+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:45:28.051537+05:30",
            "account_type": "Assets",
            "account_head": "Current Assets",
            "account_subhead": "Cash",
            "account_name": "Petty Cash",
            "account_code": None,
            "description": None,
            "add_to_watchlist_on_my_dashboard": None,
            "mark_this_is_sub_account": None,
            "is_child_allowed": None,
            "parent_account": None,
            "parent_id": "None",
            "ListID": None,
            "EditSequence": None,
            "Name": None,
            "FullName": None,
            "IsActive": False,
            "ParentRefListID": None,
            "ParentRefFullName": None,
            "Sublevel": None,
            "SpecialAccountType": None,
            "IsTaxAccount": False,
            "AccountNumber": None,
            "BankNumber": None,
            "Balance": 0.0,
            "TotalBalance": 0.0,
            "OpenBalance": 0.0,
            "OpenBalanceDate": None,
            "SalesTaxCodeRefListID": None,
            "SalesTaxCodeRefFullName": None,
            "TaxCodeRefListID": None,
            "TaxCodeRefFullName": None,
            "TaxLineInfoRetTaxLineID": None,
            "TaxLineInfoRetTaxLineName": None,
            "CashFlowClassification": None,
            "CurrencyRefListID": None,
            "CurrencyRefFullName": None,
            "isdefault": False,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        },
        "bank_id": None,
        "customer_id": {
            "customer_id": "0cb4820c-1aa9-4a4d-810e-ce493cb3fba4",
            "created_id": "None",
            "created_date": "2022-05-04T16:41:35.428236+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:41:35.428236+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:41:35.428236+05:30",
            "salutation": None,
            "customer_name": "Cust Advance",
            "customer_mobile": "8899889966",
            "company_name": "",
            "customer_display_name": "Cust Advance",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "email@example.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        }
    }

   
       
    contents={

        "company_name":customer_advance_response['company_id']['company_name'],
        "address":customer_advance_response['company_id']['address'],
        "city":customer_advance_response['company_id']['city'],
        "gst_in":customer_advance_response['company_id']['gstin'],
        "customer_advance_date":customer_advance_response['customer_advance_date'],
      #  "credit_date":datetime.datetime.strptime(customer_advance_response['ca_date'], "%Y-%m-%dT%H:%M:%S%z").date(),     
        "place_of_supply":customer_advance_response['supply_place'],   
        "total_in_words":'',
        "customer_name":customer_advance_response['customer_id']['customer_name'],
        "description_supply":customer_advance_response['description_supply'], 
        "customer_advance_ref_no":  customer_advance_response['customer_advance_ref_no'],
        "received_via":customer_advance_response['received_via'],
        "amount_received":customer_advance_response['amount_received'],
        "cgst_amount":customer_advance_response['cgst_amount'],
        "sgst_amount": customer_advance_response['sgst_amount'],
        "igst_amount": customer_advance_response['igst_amount'],
        "balance_amount":customer_advance_response['balance_amount'],
       
    }
    print(contents)
    return contents






if __name__ == '__main__':
    ca_Response={
        "ca_id": "d31821cd-6f66-4794-9b8f-b5398260e1af",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "is_customer_advance_generated": True,
        "status": "Manually Added",
        "gst_treatment": "None",
        "gstin_no": "None",
        "supply_place": "Maharashtra",
        "balance_amount": "1231.00",
        "amount_received": "1231.00",
        "customer_advance_date": "2022-05-06",
        "customer_advance_ref_no": None,
        "received_via": "Cash",
        "description": "None",
        "description_supply": None,
        "bank_charges": None,
        "payment_serial": "PR2121",
        "tax_rate": "0.00",
        "tax_name": None,
        "tax_type": None,
        "tax_amount": "0.00",
        "attach_file": None,
        "is_bank_transaction": False,
        "company_id": {
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "created_id": "None",
            "created_date": "2022-04-27T17:32:44.842193+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:32:44.842193+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:32:44.842193+05:30",
            "trial_company": None,
            "company_name": "CodeRize Technologies Pune",
            "alias_name": "",
            "address": "Pune",
            "locality": "",
            "landmark": "",
            "pincode": 422064,
            "city": "",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "",
            "primary_mobile_number": "995656656566",
            "primary_alternate_number": "",
            "primary_email": "coderize@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "",
            "website": "",
            "books_start_date": "2022-04-01",
            "method": "None",
            "company_type": "Private",
            "pan_number": "CODE121212",
            "gstin": "",
            "cin": "",
            "other_registration_number": "",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "https://products.coderize.in:8002/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "coa_id": {
            "coa_id": "ad32e312-24f4-48c9-ab98-1ee23dd3f1c5",
            "created_id": "None",
            "created_date": "2022-05-04T16:45:28.051537+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:45:28.051537+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:45:28.051537+05:30",
            "account_type": "Assets",
            "account_head": "Current Assets",
            "account_subhead": "Cash",
            "account_name": "Petty Cash",
            "account_code": None,
            "description": None,
            "add_to_watchlist_on_my_dashboard": None,
            "mark_this_is_sub_account": None,
            "is_child_allowed": None,
            "parent_account": None,
            "parent_id": "None",
            "ListID": None,
            "EditSequence": None,
            "Name": None,
            "FullName": None,
            "IsActive": False,
            "ParentRefListID": None,
            "ParentRefFullName": None,
            "Sublevel": None,
            "SpecialAccountType": None,
            "IsTaxAccount": False,
            "AccountNumber": None,
            "BankNumber": None,
            "Balance": 0.0,
            "TotalBalance": 0.0,
            "OpenBalance": 0.0,
            "OpenBalanceDate": None,
            "SalesTaxCodeRefListID": None,
            "SalesTaxCodeRefFullName": None,
            "TaxCodeRefListID": None,
            "TaxCodeRefFullName": None,
            "TaxLineInfoRetTaxLineID": None,
            "TaxLineInfoRetTaxLineName": None,
            "CashFlowClassification": None,
            "CurrencyRefListID": None,
            "CurrencyRefFullName": None,
            "isdefault": False,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        },
        "bank_id": None,
        "customer_id": {
            "customer_id": "0cb4820c-1aa9-4a4d-810e-ce493cb3fba4",
            "created_id": "None",
            "created_date": "2022-05-04T16:41:35.428236+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:41:35.428236+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:41:35.428236+05:30",
            "salutation": None,
            "customer_name": "Cust Advance",
            "customer_mobile": "8899889966",
            "company_name": "",
            "customer_display_name": "Cust Advance",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "email@example.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        }
    },
    {
        "ca_id": "44143641-2997-45b4-bdfa-69eeb49f042b",
        "cgst_amount": "0.00",
        "sgst_amount": "0.00",
        "igst_amount": "0.00",
        "is_customer_advance_generated": True,
        "status": "Manually Added",
        "gst_treatment": "None",
        "gstin_no": "None",
        "supply_place": None,
        "balance_amount": "1212.00",
        "amount_received": "1212.00",
        "customer_advance_date": "2022-05-06",
        "customer_advance_ref_no": "REF-2122",
        "received_via": "Cash",
        "description": "None",
        "description_supply": "Test Description",
        "bank_charges": None,
        "payment_serial": "PR2122",
        "tax_rate": "0.00",
        "tax_name": None,
        "tax_type": None,
        "tax_amount": "0.00",
        "attach_file": None,
        "is_bank_transaction": False,
        "company_id": {
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "created_id": "None",
            "created_date": "2022-04-27T17:32:44.842193+05:30",
            "modified_id": "None",
            "modified_date": "2022-04-27T17:32:44.842193+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-04-27T17:32:44.842193+05:30",
            "trial_company": None,
            "company_name": "CodeRize Technologies Pune",
            "alias_name": "",
            "address": "Pune",
            "locality": "",
            "landmark": "",
            "pincode": 422064,
            "city": "",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "",
            "primary_mobile_number": "995656656566",
            "primary_alternate_number": "",
            "primary_email": "coderize@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "",
            "website": "",
            "books_start_date": "2022-04-01",
            "method": "None",
            "company_type": "Private",
            "pan_number": "CODE121212",
            "gstin": "",
            "cin": "",
            "other_registration_number": "",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "https://products.coderize.in:8002/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "coa_id": {
            "coa_id": "ad32e312-24f4-48c9-ab98-1ee23dd3f1c5",
            "created_id": "None",
            "created_date": "2022-05-04T16:45:28.051537+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:45:28.051537+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:45:28.051537+05:30",
            "account_type": "Assets",
            "account_head": "Current Assets",
            "account_subhead": "Cash",
            "account_name": "Petty Cash",
            "account_code": None,
            "description": None,
            "add_to_watchlist_on_my_dashboard": None,
            "mark_this_is_sub_account": None,
            "is_child_allowed": None,
            "parent_account": None,
            "parent_id": "None",
            "ListID": None,
            "EditSequence": None,
            "Name": None,
            "FullName": None,
            "IsActive": False,
            "ParentRefListID": None,
            "ParentRefFullName": None,
            "Sublevel": None,
            "SpecialAccountType": None,
            "IsTaxAccount": False,
            "AccountNumber": None,
            "BankNumber": None,
            "Balance": 0.0,
            "TotalBalance": 0.0,
            "OpenBalance": 0.0,
            "OpenBalanceDate": None,
            "SalesTaxCodeRefListID": None,
            "SalesTaxCodeRefFullName": None,
            "TaxCodeRefListID": None,
            "TaxCodeRefFullName": None,
            "TaxLineInfoRetTaxLineID": None,
            "TaxLineInfoRetTaxLineName": None,
            "CashFlowClassification": None,
            "CurrencyRefListID": None,
            "CurrencyRefFullName": None,
            "isdefault": False,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        },
        "bank_id": None,
        "customer_id": {
            "customer_id": "0cb4820c-1aa9-4a4d-810e-ce493cb3fba4",
            "created_id": "None",
            "created_date": "2022-05-04T16:41:35.428236+05:30",
            "modified_id": "None",
            "modified_date": "2022-05-04T16:41:35.428236+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-05-04T16:41:35.428236+05:30",
            "salutation": None,
            "customer_name": "Cust Advance",
            "customer_mobile": "8899889966",
            "company_name": "",
            "customer_display_name": "Cust Advance",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "email@example.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "048a4957-39ad-44bd-97ea-f7a044ad4538",
            "branch_id": None
        }
    }

    a = customer_adavnce_data(ca_Response)
    #print(a)


def generate_customer_advance_pdf(data):
    # first dict data give in y object
  #  y=invoice_data(data)
    # second dict data give in x object
    x = customer_adavnce_data(data)
    # use update method to combine both dictionaries
    # here we use update method to give x dict data in y
   # y.update(x)
    # and here y is passed as a parameter to the render function context=y
    html = render(None, "core/customer_advance.html", x)
    return html