from templates.img_conversion import image_url_to_base64
from django.shortcuts import render
import datetime


def credit_data(credit_response):
    credit_response = credit_response[0]
    credit_response_fdasafd={
        "cn_id": "f86a2c67-d339-4811-b96b-6eab38366c83",
        "credit_note_items": [
            {
                "cn_id": {
                    "cn_id": "f86a2c67-d339-4811-b96b-6eab38366c83",
                    "cgst_total": "0.00",
                    "sgst_total": "0.00",
                    "igst_total": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-04T12:32:07.113722+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-04T12:32:07.113722+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-04T12:32:07.113722+05:30",
                    "customer_name": "abcd",
                    "customer_email": "None",
                    "reason": "Sales Return",
                    "subject": "",
                    "received_no": "None",
                    "received_date": "2022-03-04T12:32:07.113722+05:30",
                    "supply_place": "Karnataka",
                    "cn_date": "2022-03-04T00:00:00+05:30",
                    "discount": "200.00",
                    "entered_discount": "200.00",
                    "sub_total": "5200.00",
                    "total_quantity": None,
                    "shipping_charges": "100.00",
                    "shipping_tax_name": None,
                    "shipping_tax_rate": "0.00",
                    "entered_shipping_charges": "100.00",
                    "adjustment": None,
                    "tcs_amount": "0.00",
                    "balance_amount": "5100.00",
                    "total": "5100.00",
                    "total_gst": None,
                    "customer_note": None,
                    "terms_condition": None,
                    "is_cn_converted": False,
                    "is_cn_generated": True,
                    "attach_file": None,
                    "status": "Open",
                    "cn_status": "Draft",
                    "cn_serial": "12",
                    "cn_ref_no": "12",
                    "convt_type": "None",
                    "convt_id": "None",
                    "convt_serial": "None",
                    "convt_ref_no": "None",
                    "so_id": None,
                    "customer_id": "98a1bbda-9514-44f9-8c02-e49965fbb606",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "emp_id": None,
                    "tcs_id": None,
                    "est_id": None,
                    "invoice_id": None,
                    "item_id": None,
                    "pay_id": None
                },
                "cnitem_id": "7dc08069-9220-4287-936b-3bf199db032f",
                "item_name": "Test1",
                "amount": "5200.00",
                "quantity": "1.00",
                "rate": "5200.00",
                "tax_name": None,
                "taxamount": None,
                "coa_id": {
                    "coa_id": "032bf95f-1541-441c-913b-d90ea1a7f085",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:36:29.443680+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:36:29.443680+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:36:29.443680+05:30",
                    "account_type": "Income",
                    "account_head": "Revenue from Operations",
                    "account_subhead": "Sale of Products",
                    "account_name": "Sales Of Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "cgst_amount": "0.00",
                "sgst_amount": "0.00",
                "igst_amount": "0.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "created_id": "None",
        "created_date": "2022-03-04T12:32:07.113722+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-04T12:32:07.113722+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-04T12:32:07.113722+05:30",
        "customer_name": "KKKKKKKKKKKKK",
        "customer_email": "None",
        "reason": "Sales Return",
        "subject": "",
        "received_no": "None",
        "received_date": "2022-03-04T12:32:07.113722+05:30",
        "supply_place": "Karnataka",
        "cn_date": "2022-03-04T00:00:00+05:30",
        "discount": "200.00",
        "entered_discount": "200.00",
        "sub_total": "5200.00",
        "total_quantity": None,
        "shipping_charges": "100.00",
        "shipping_tax_name": None,
        "shipping_tax_rate": "0.00",
        "entered_shipping_charges": "100.00",
        "adjustment": None,
        "tcs_amount": "0.00",
        "balance_amount": "5100.00",
        "total": "5100.00",
        "total_gst": None,
        "customer_note": None,
        "terms_condition": None,
        "is_cn_converted": False,
        "is_cn_generated": True,
        "attach_file": None,
        "status": "Open",
        "cn_status": "Draft",
        "cn_serial": "12",
        "cn_ref_no": "12",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "so_id": None,
        "customer_id": {
            "customer_id": "98a1bbda-9514-44f9-8c02-e49965fbb606",
            "created_id": "None",
            "created_date": "2022-03-03T12:21:22.782469+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:21:22.782469+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:21:22.782469+05:30",
            "salutation": "Mr.",
            "customer_name": "GAYATRI GANGADHAR CHAME",
            "customer_mobile": "09822607468",
            "company_name": "Coderize twchnology pvt ltd",
            "customer_display_name": "gayatri",
            "print_as_check_as": False,
            "customer_contact": "09822607468",
            "customer_email": "gayatrireddy800@gmail.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "nothing",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Consumer",
            "gstin_number": "",
            "tax_preference": "Non-Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "7966565",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Bihar",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "emp_id": None,
        "tcs_id": None,
        "est_id": None,
        "invoice_id": None,
        "item_id": None,
        "pay_id": None
    }
    contents={

        "company_name":credit_response['company_id']['company_name'],
        "address":credit_response['company_id']['address'],
        "city":credit_response['company_id']['city'],
        "gst_in":credit_response['company_id']['gstin'],
        "cn_serial":credit_response['cn_serial'],
        "credit_date":datetime.datetime.strptime(credit_response['cn_date'], "%Y-%m-%dT%H:%M:%S%z").date(),
        "invoice_serial":'',
        "invoice_date":datetime.datetime.strptime(credit_response['cn_date'], "%Y-%m-%dT%H:%M:%S%z").date(),
        "place_of_supply":credit_response['supply_place'],
        "sub_total":credit_response['sub_total'],
        "discount":credit_response['discount'],
        "total_in_words":'',
        "cgst_0":'',
        "total":credit_response['total'],
        "itemdescription":'',
        "sgst0_0":'',
        "cgst25_25":credit_response['cgst_total'],
        "customer_note":credit_response['customer_note'],
        "sgst25_25":'',
        "cgst6_6":'',
        "sgst6_6":'',
        "cgst9_9":'',
        "sgst9_9":credit_response['sgst_total'],
        "shipping_charges":credit_response['shipping_charges'],
        "total":credit_response['total'],
       # "credit_remaining":credit_response['credit_remaining'],
        "igst_total":credit_response['igst_total'],
        "tcs":credit_response['tcs_amount'],
        "customer_name":credit_response['customer_id']['customer_name'],
        #"item_serial":invoice_response['invoice_items'][0]['item_serial'],
       "credit_note_items":[dict(a) for a in credit_response['credit_note_items']],
    }
    print(contents)
    return contents






if __name__ == '__main__':
    cn_Response= {
        "cn_id": "f86a2c67-d339-4811-b96b-6eab38366c83",
        "credit_note_items": [
            {
                "cn_id": {
                    "cn_id": "f86a2c67-d339-4811-b96b-6eab38366c83",
                    "cgst_total": "0.00",
                    "sgst_total": "0.00",
                    "igst_total": "0.00",
                    "created_id": "None",
                    "created_date": "2022-03-04T12:32:07.113722+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-04T12:32:07.113722+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-04T12:32:07.113722+05:30",
                    "customer_name": "None",
                    "customer_email": "None",
                    "reason": "Sales Return",
                    "subject": "",
                    "received_no": "None",
                    "received_date": "2022-03-04T12:32:07.113722+05:30",
                    "supply_place": "Karnataka",
                    "cn_date": "2022-03-04T00:00:00+05:30",
                    "discount": "200.00",
                    "entered_discount": "200.00",
                    "sub_total": "5200.00",
                    "total_quantity": None,
                    "shipping_charges": "100.00",
                    "shipping_tax_name": None,
                    "shipping_tax_rate": "0.00",
                    "entered_shipping_charges": "100.00",
                    "adjustment": None,
                    "tcs_amount": "0.00",
                    "balance_amount": "5100.00",
                    "total": "5100.00",
                    "total_gst": None,
                    "customer_note": None,
                    "terms_condition": None,
                    "is_cn_converted": False,
                    "is_cn_generated": True,
                    "attach_file": None,
                    "status": "Open",
                    "cn_status": "Draft",
                    "cn_serial": "12",
                    "cn_ref_no": "12",
                    "convt_type": "None",
                    "convt_id": "None",
                    "convt_serial": "None",
                    "convt_ref_no": "None",
                    "so_id": None,
                    "customer_id": "98a1bbda-9514-44f9-8c02-e49965fbb606",
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None,
                    "emp_id": None,
                    "tcs_id": None,
                    "est_id": None,
                    "invoice_id": None,
                    "item_id": None,
                    "pay_id": None
                },
                "cnitem_id": "7dc08069-9220-4287-936b-3bf199db032f",
                "item_name": "Test1",
                "amount": "5200.00",
                "quantity": "1.00",
                "rate": "5200.00",
                "tax_name": None,
                "taxamount": None,
                "coa_id": {
                    "coa_id": "032bf95f-1541-441c-913b-d90ea1a7f085",
                    "created_id": "None",
                    "created_date": "2022-03-03T15:36:29.443680+05:30",
                    "modified_id": "None",
                    "modified_date": "2022-03-03T15:36:29.443680+05:30",
                    "deleted_id": "None",
                    "deleted_date": "2022-03-03T15:36:29.443680+05:30",
                    "account_type": "Income",
                    "account_head": "Revenue from Operations",
                    "account_subhead": "Sale of Products",
                    "account_name": "Sales Of Item",
                    "account_code": None,
                    "description": None,
                    "add_to_watchlist_on_my_dashboard": None,
                    "mark_this_is_sub_account": None,
                    "is_child_allowed": None,
                    "parent_account": None,
                    "parent_id": "None",
                    "ListID": None,
                    "EditSequence": None,
                    "Name": None,
                    "FullName": None,
                    "IsActive": False,
                    "ParentRefListID": None,
                    "ParentRefFullName": None,
                    "Sublevel": None,
                    "SpecialAccountType": None,
                    "IsTaxAccount": False,
                    "AccountNumber": None,
                    "BankNumber": None,
                    "Balance": 0.0,
                    "TotalBalance": 0.0,
                    "OpenBalance": 0.0,
                    "OpenBalanceDate": None,
                    "SalesTaxCodeRefListID": None,
                    "SalesTaxCodeRefFullName": None,
                    "TaxCodeRefListID": None,
                    "TaxCodeRefFullName": None,
                    "TaxLineInfoRetTaxLineID": None,
                    "TaxLineInfoRetTaxLineName": None,
                    "CashFlowClassification": None,
                    "CurrencyRefListID": None,
                    "CurrencyRefFullName": None,
                    "isdefault": False,
                    "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
                    "branch_id": None
                },
                "cgst_amount": "0.00",
                "sgst_amount": "0.00",
                "igst_amount": "0.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "created_id": "None",
        "created_date": "2022-03-04T12:32:07.113722+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-04T12:32:07.113722+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-04T12:32:07.113722+05:30",
        "customer_name": "None",
        "customer_email": "None",
        "reason": "Sales Return",
        "subject": "",
        "received_no": "None",
        "received_date": "2022-03-04T12:32:07.113722+05:30",
        "supply_place": "Karnataka",
        "cn_date": "2022-03-04T00:00:00+05:30",
        "discount": "200.00",
        "entered_discount": "200.00",
        "sub_total": "5200.00",
        "total_quantity": None,
        "shipping_charges": "100.00",
        "shipping_tax_name": None,
        "shipping_tax_rate": "0.00",
        "entered_shipping_charges": "100.00",
        "adjustment": None,
        "tcs_amount": "0.00",
        "balance_amount": "5100.00",
        "total": "5100.00",
        "total_gst": None,
        "customer_note": None,
        "terms_condition": None,
        "is_cn_converted": False,
        "is_cn_generated": True,
        "attach_file": None,
        "status": "Open",
        "cn_status": "Draft",
        "cn_serial": "12",
        "cn_ref_no": "12",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "so_id": None,
        "customer_id": {
            "customer_id": "98a1bbda-9514-44f9-8c02-e49965fbb606",
            "created_id": "None",
            "created_date": "2022-03-03T12:21:22.782469+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:21:22.782469+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:21:22.782469+05:30",
            "salutation": "Mr.",
            "customer_name": "GAYATRI GANGADHAR CHAME",
            "customer_mobile": "09822607468",
            "company_name": "Coderize twchnology pvt ltd",
            "customer_display_name": "gayatri",
            "print_as_check_as": False,
            "customer_contact": "09822607468",
            "customer_email": "gayatrireddy800@gmail.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "nothing",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Consumer",
            "gstin_number": "",
            "tax_preference": "Non-Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "7966565",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Bihar",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None,
        "emp_id": None,
        "tcs_id": None,
        "est_id": None,
        "invoice_id": None,
        "item_id": None,
        "pay_id": None
    }
    a = credit_data(cn_Response)
    print(a)


def generate_credit_note_pdf(data):
    print(data['company_id']['logo_image'])
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html = render(None, "core/credit_note.html", data)
    return html