from importlib.resources import contents
from multiprocessing import context
from urllib import response
from django.shortcuts import render
from django.http import HttpResponse
import os
from pathlib import Path

import datetime
from django.conf import settings
from templates.img_conversion import image_url_to_base64



def common_dict(invoice_response):
    invoice_response = invoice_response[0]
    invoice_response_sadfsa={
    "invoice_id": "62e4a1f1-7988-45e5-8274-44d28847204b",
    "invoice_items": [
                {
                    "invoice_id": "62e4a1f1-7988-45e5-8274-44d28847204b",
                    "invoiceitem_id": "ec5ec314-97b1-44c1-b838-8c84d8d77780",
                    "item_name": "Test Item",
                    "amount": "1500.00",
                    "quantity": "1.00",
                    "rate": "1500.00",
                    "tax": None,
                    "taxamount": None,
                    "tax_name": "GST5 [5%]",
                    "sgst_amount": "37.50",
                    "cgst_amount": "37.50",
                    "igst_amount": "75.00"
                }
    ],
    "created_id": "None",
    "created_date": "2022-02-23T17:34:27.505782+05:30",
    "modified_id": "None",
    "modified_date": "2022-02-23T17:34:27.505782+05:30",
    "deleted_id": "None",
    "deleted_date": "2022-02-23T17:34:27.505782+05:30",
    "supply_place": "Maharashtra",
    "invoice_ref_no": "None",
    "invoice_serial": "Inv123",
    "invoice_status": "Draft",
    "invoice_date": "2022-02-23",
    "is_invoice_generated": True,
    "payment_status": "unpaid",
    "amount_due": "1575.00",
    "amount_received": None,
    "order_no": "",
    "due_date": "2022-02-23",
    "delivery_method": "None",
    "term_name": "Custom",
    "no_of_days": 0,
    "project_name": "None",
    "subject": "",
    "total_quantity": None,
    "discount": "0.00",
    "entered_discount": "0.00",
    "amount": None,
    "cgst_total": "37.50", #
    "sgst_total": "37.50",#
    "igst_total": "0.00",#
    "sub_total": "1500.00",
    "shipping_charges": "20.00",
    "shipping_tax_rate": 0,
    "shipping_tax_name": None,
    "entered_shipping_charges": "0.00",
    "adjustment": None,
    "tcs_amount": "0.00",
    "total": "1575.00",#
    "total_gst": None,
    "payment_mode": "Cash",
    "deposit_to": None,
    "payment_received": False,
    "round_off": None,
    "tax": "None",
    "grand_total": None,
    "customer_note": "",
    "terms_condition": "",
    "attach_file": None,
    "convt_type": "None",
    "convt_id": "None",
    "convt_serial": "None",
    "convt_ref_no": "None",
    "is_converted": False,
    "TermsRefFullName": "None",
    "TermsRefListID": "None",
    "so_id": None,
    "customer_id": {
        "customer_id": "381602c6-2882-49f9-a83e-1cf3fca6dbde",
        "created_id": "None",
        "created_date": "2022-02-22T14:38:55.441620+05:30",
        "modified_id": "None",
        "modified_date": "2022-02-22T14:38:55.441620+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-02-22T14:38:55.441620+05:30",
        "salutation": "Mr.",
        "customer_name": "M Enterprise",
        "customer_mobile": "985674887848",
        "company_name": "M Company",
        "customer_display_name": "m Comapny",
        "print_as_check_as": False,
        "customer_contact": "",
        "customer_email": "M@gmail.com",
        "customer_type": "Business",
        "customer_designation": "",
        "customer_department": "",
        "exemption_reason": "",
        "customerRefListId": "None",
        "customerTypeRefListId": "None",
        "customerTypeReffullName": "None",
        "is_subcustomer": False,
        "parent_customer": "None",
        "enable_portal": True,
        "company_display_name": "None",
        "company_email": "None",
        "company_number": "None",
        "website": "",
        "opening_balance": None,
        "currency": "None",
        "set_credit_limit": "0.00",
        "gst_treatment": "Registered Business - Regular",
        "gstin_number": "MJSK1233K",
        "tax_preference": "Taxable",
        "cin_number": "None",
        "trn_number": "None",
        "vat_number": "None",
        "pan_number": "",
        "b_attention": "",
        "bill_address1": "A-222, Balaji Prasad, Near Dakshinmukhi Maruti mandir, 471, Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030",
        "bill_address2": "",
        "bill_address_city": "",
        "bill_address_state": "",
        "bill_address_postal_code": 413512,
        "bill_address_country": "",
        "bill_contact_number": "",
        "bill_fax_number": "",
        "s_attention": "",
        "ship_address1": "A-333, Balaji Prasad, Near Dakshinmukhi Maruti mandir, 471, Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030",
        "ship_address2": "",
        "ship_address_city": "",
        "ship_address_state": "",
        "ship_address_postal_code": 444444,
        "ship_address_country": "",
        "ship_contact_number": "",
        "ship_fax_number": "",
        "supply_place": "Andhra Pradesh",
        "contact_salutation": None,
        "contact_name": "",
        "contact_phone": "",
        "contact_mobile": "",
        "contact_email": "",
        "contact_designation": "",
        "contact_department": "",
        "remarks": "",
        "term_name": "",
        "no_of_days": 0,
        "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
        "branch_id": None
    },
    "emp_id": None,
    "est_id": None,
    "item_id": None,
    "tcs_id": None,
    "company_id": {
        "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
        "created_id": "None",
        "created_date": "2022-02-18T11:31:16.270717+05:30",
        "modified_id": "None",
        "modified_date": "2022-02-18T11:31:16.270717+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-02-18T11:31:16.270717+05:30",
        "trial_company": None,
        "company_name": "Coderize Technologies Pvt. Ltd.",
        "alias_name": "",
        "address": "A-444, Balaji Prasad, Near Dakshinmukhi Maruti mandir, 471, Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030",
        "locality": "",
        "landmark": "",
        "pincode": 411037,
        "city": "Pune",
        "state": "Maharashtra",
        "other": "",
        "is_primary": True,
        "primary_phone_number": "",
        "primary_mobile_number": "9554215425",
        "primary_alternate_number": "",
        "primary_email": "support@coderize.in",
        "secondary_phone_number": "",
        "secondary_mobile_number": "",
        "secondary_alternate_number": "",
        "secondary_email": "",
        "website": "",
        "books_start_date": "2022-02-01",
        "method": "None",
        "company_type": "Private",
        "pan_number": "KJSHFU5486",
        "gstin": "123456",
        "cin": "",
        "other_registration_number": "",
        "password": "584587587",
        "security_control": "False",
        "audit_feature": "True",
        "logo_image": "/media/None",
        "report_basis": "None",
        "company_edit_id": "None",
        "tax_edit_id": "None",
        "separate_payment_address": "False",
        "address_receive_payment": "None"
    },
    "branch_id": None
    }
  
    contents={
        "heading":"Tax Invoice",
        "company_name":invoice_response['company_id']['company_name'],
        "company_email":invoice_response['company_id']['primary_email'],
        "company_mobile": invoice_response['company_id']['primary_mobile_number'],
        "company_gst":invoice_response['company_id']["gstin"],
        "address":invoice_response['company_id']['address'],
        "city":invoice_response['company_id']['city'],
        "gst_in":invoice_response['company_id']['gstin'],
        "invoice_serial":invoice_response['invoice_serial'],
        "due_date":datetime.datetime.strptime(invoice_response['due_date'], "%Y-%m-%d").date(),
        "terms":invoice_response['term_name'],
        "invoice_date":datetime.datetime.strptime(invoice_response['invoice_date'], "%Y-%m-%d").date(),
        "place_of_supply":invoice_response['supply_place'],
        #here we send a list in invoice items 
        #and convert a order dict into dict
        'invoice_items': [dict(a) for a in invoice_response['invoice_items']],
        "sub_total":invoice_response['sub_total'],
        "cgst_total":invoice_response['cgst_total'],
        "sgst_total":invoice_response['sgst_total'],
        "igst_total":invoice_response['igst_total'],
        "tcs":invoice_response['tcs_amount'],
        "discount":invoice_response['discount'],
        "total_in_words":'',
        "cgst_0":'',
        "itemdescription":'',
        "sgst0_0":'',
        "cgst_total":invoice_response['cgst_total'],
        "sgst25_25":'',
        "cgst6_6":'',
        "sgst6_6":'',
        "cgst9_9":'',
        "sgst_total":invoice_response['sgst_total'],
        "shipping_charges":invoice_response['shipping_charges'],
        "total":invoice_response['total'],
        "credit_remaining":invoice_response['total'],
        "customer":invoice_response["customer_id"],
        "total_charges":invoice_response["total_charges"],
        "charges":invoice_response["charges"],
        "cess_total":invoice_response["cess_total"],
        "discount_type":invoice_response["discount_type"],
        "salesman":invoice_response["emp_id"],
        "terms_condition":invoice_response["terms_condition"]
    }



    invoice_response=invoice_response['invoice_items']

    for items in invoice_response:


        item_name=items['item_name']
        print("@@@@@@@@@@",item_name)   
        item_quantity=items['quantity']
        print("@@@@@@@@@@@@",item_quantity)
        item_rate=items['rate']
        print("@@@@@@@@@@@@",item_rate)
        item_amount=items['amount']
        print("@@@@@@@@@@@@",item_amount)


     
    print("*************************************************************************",contents)
    return contents


def invoice_data(invoice_response):
    invoice_response = invoice_response[0]
    invoice_response_fdasafd={
    "invoice_id": "62e4a1f1-7988-45e5-8274-44d28847204b",
    "invoice_items": [
                {
                    "invoice_id": "62e4a1f1-7988-45e5-8274-44d28847204b",
                    "invoiceitem_id": "ec5ec314-97b1-44c1-b838-8c84d8d77780",
                    "item_name": "Test Item",
                    "amount": "1500.00",
                    "quantity": "1.00",
                    "rate": "1500.00",
                    "tax": None,
                    "taxamount": None,
                    "tax_name": "GST5 [5%]",
                    "sgst_amount": "37.50",
                    "cgst_amount": "37.50",
                    "igst_amount": "75.00"
                }
    ],
    "created_id": "None",
    "created_date": "2022-02-23T17:34:27.505782+05:30",
    "modified_id": "None",
    "modified_date": "2022-02-23T17:34:27.505782+05:30",
    "deleted_id": "None",
    "deleted_date": "2022-02-23T17:34:27.505782+05:30",
    "supply_place": "Maharashtra",
    "invoice_ref_no": "None",
    "invoice_serial": "Inv123",
    "invoice_status": "Draft",
    "invoice_date": "2022-02-23",
    "is_invoice_generated": True,
    "payment_status": "unpaid",
    "amount_due": "1575.00",
    "amount_received": None,
    "order_no": "",
    "due_date": "2022-02-23",
    "delivery_method": "None",
    "term_name": "Custom",
    "no_of_days": 0,
    "project_name": "None",
    "subject": "",
    "total_quantity": None,
    "discount": "0.00",
    "entered_discount": "0.00",
    "amount": None,
    "cgst_total": "37.50",
    "sgst_total": "37.50",
    "igst_total": "0.00",
    "sub_total": "1500.00",
    "shipping_charges": "20.00",
    "shipping_tax_rate": 0,
    "shipping_tax_name": None,
    "entered_shipping_charges": "0.00",
    "adjustment": None,
    "tcs_amount": "0.00",
    "total": "1575.00",
    "total_gst": None,
    "payment_mode": "Cash",
    "deposit_to": None,
    "payment_received": False,
    "round_off": None,
    "tax": "None",
    "grand_total": None,
    "customer_note": "",
    "terms_condition": "",
    "attach_file": None,
    "convt_type": "None",
    "convt_id": "None",
    "convt_serial": "None",
    "convt_ref_no": "None",
    "is_converted": False,
    "TermsRefFullName": "None",
    "TermsRefListID": "None",
    "so_id": None,
    "customer_id": {
        "customer_id": "381602c6-2882-49f9-a83e-1cf3fca6dbde",
        "created_id": "None",
        "created_date": "2022-02-22T14:38:55.441620+05:30",
        "modified_id": "None",
        "modified_date": "2022-02-22T14:38:55.441620+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-02-22T14:38:55.441620+05:30",
        "salutation": "Mr.",
        "customer_name": "M Enterprise",
        "customer_mobile": "985674887848",
        "company_name": "M Company",
        "customer_display_name": "m Comapny",
        "print_as_check_as": False,
        "customer_contact": "",
        "customer_email": "M@gmail.com",
        "customer_type": "Business",
        "customer_designation": "",
        "customer_department": "",
        "exemption_reason": "",
        "customerRefListId": "None",
        "customerTypeRefListId": "None",
        "customerTypeReffullName": "None",
        "is_subcustomer": False,
        "parent_customer": "None",
        "enable_portal": True,
        "company_display_name": "None",
        "company_email": "None",
        "company_number": "None",
        "website": "",
        "opening_balance": None,
        "currency": "None",
        "set_credit_limit": "0.00",
        "gst_treatment": "Registered Business - Regular",
        "gstin_number": "MJSK1233K",
        "tax_preference": "Taxable",
        "cin_number": "None",
        "trn_number": "None",
        "vat_number": "None",
        "pan_number": "",
        "b_attention": "",
        "bill_address1": "A-222, Balaji Prasad, Near Dakshinmukhi Maruti mandir, 471, Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030",
        "bill_address2": "",
        "bill_address_city": "",
        "bill_address_state": "",
        "bill_address_postal_code": 413512,
        "bill_address_country": "",
        "bill_contact_number": "",
        "bill_fax_number": "",
        "s_attention": "",
        "ship_address1": "A-333, Balaji Prasad, Near Dakshinmukhi Maruti mandir, 471, Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030",
        "ship_address2": "",
        "ship_address_city": "",
        "ship_address_state": "",
        "ship_address_postal_code": 444444,
        "ship_address_country": "",
        "ship_contact_number": "",
        "ship_fax_number": "",
        "supply_place": "Andhra Pradesh",
        "contact_salutation": None,
        "contact_name": "",
        "contact_phone": "",
        "contact_mobile": "",
        "contact_email": "",
        "contact_designation": "",
        "contact_department": "",
        "remarks": "",
        "term_name": "",
        "no_of_days": 0,
        "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
        "branch_id": None
    },
    "emp_id": None,
    "est_id": None,
    "item_id": None,
    "tcs_id": None,
    "company_id": {
        "company_id": "a51415b7-6829-42e3-b4c1-1702396a40a6",
        "created_id": "None",
        "created_date": "2022-02-18T11:31:16.270717+05:30",
        "modified_id": "None",
        "modified_date": "2022-02-18T11:31:16.270717+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-02-18T11:31:16.270717+05:30",
        "trial_company": None,
        "company_name": "Coderize Technologies Pvt. Ltd.",
        "alias_name": "",
        "address": "A-444, Balaji Prasad, Near Dakshinmukhi Maruti mandir, 471, Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030",
        "locality": "",
        "landmark": "",
        "pincode": 411037,
        "city": "Pune",
        "state": "Maharashtra",
        "other": "",
        "is_primary": True,
        "primary_phone_number": "",
        "primary_mobile_number": "9554215425",
        "primary_alternate_number": "",
        "primary_email": "support@coderize.in",
        "secondary_phone_number": "",
        "secondary_mobile_number": "",
        "secondary_alternate_number": "",
        "secondary_email": "",
        "website": "",
        "books_start_date": "2022-02-01",
        "method": "None",
        "company_type": "Private",
        "pan_number": "KJSHFU5486",
        "gstin": "123456",
        "cin": "",
        "other_registration_number": "",
        "password": "584587587",
        "security_control": "False",
        "audit_feature": "True",
        "logo_image": "/media/None",
        "report_basis": "None",
        "company_edit_id": "None",
        "tax_edit_id": "None",
        "separate_payment_address": "False",
        "address_receive_payment": "None"
    },
    "branch_id": None
    }
    
    context={
        "bill_to_customer_name":invoice_response['customer_id']['customer_name'],
        "ship_to_customer_address":invoice_response['customer_id']['ship_address1'],
        "bill_to_customer_address":invoice_response['customer_id']['bill_address1'],
        "ship_to_city":invoice_response['customer_id']['ship_address_city'],
        "bill_to_city":invoice_response['customer_id']['bill_address_city'],
        "ship_to_postal_code":invoice_response['customer_id']['bill_address_postal_code'],
        "bill_to_postal_code":invoice_response['customer_id']['ship_address_postal_code'],
        
    }
   # print(context)
    return context

if __name__ == '__main__':
    example_Response = [
    {
        "invoice_id": "1f8bd9bd-1e94-444d-b5b6-23e903b5381e",
        "invoice_items": [],
        "created_id": "None",
        "created_date": "2022-03-03T15:49:08.518730+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-03T15:49:08.518730+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-03T15:49:08.518730+05:30",
        "supply_place": "Maharashtra",
        "invoice_ref_no": "None",
        "invoice_serial": "INV123",
        "invoice_status": "Draft",
        "invoice_date": "2022-03-03",
        "is_invoice_generated": True,
        "payment_status": "unpaid",
        "amount_due": "5460.00",
        "amount_received": None,
        "order_no": "",
        "due_date": "2022-03-18",
        "delivery_method": "None",
        "term_name": "cash on delivery",
        "no_of_days": 15,
        "project_name": "None",
        "subject": "",
        "total_quantity": None,
        "discount": "0.00",
        "entered_discount": "0.00",
        "amount": None,
        "cgst_total": "130.00",
        "sgst_total": "130.00",
        "igst_total": "0.00",
        "sub_total": "5200.00",
        "shipping_charges": "0.00",
        "shipping_tax_rate": 0,
        "shipping_tax_name": None,
        "entered_shipping_charges": "0.00",
        "adjustment": None,
        "tcs_amount": "0.00",
        "total": "5460.00",
        "total_gst": None,
        "payment_mode": "Cash",
        "deposit_to": None,
        "payment_received": False,
        "round_off": None,
        "tax": "None",
        "grand_total": None,
        "customer_note": "",
        "terms_condition": "",
        "attach_file": None,
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "is_converted": False,
        "TermsRefFullName": "None",
        "TermsRefListID": "None",
        "so_id": None,
        "customer_id": {
            "customer_id": "98a1bbda-9514-44f9-8c02-e49965fbb606",
            "created_id": "None",
            "created_date": "2022-03-03T12:21:22.782469+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:21:22.782469+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:21:22.782469+05:30",
            "salutation": "Mr.",
            "customer_name": "GAYATRI GANGADHAR CHAME",
            "customer_mobile": "09822607468",
            "company_name": "Coderize twchnology pvt ltd",
            "customer_display_name": "gayatri",
            "print_as_check_as": False,
            "customer_contact": "09822607468",
            "customer_email": "gayatrireddy800@gmail.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "nothing",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Consumer",
            "gstin_number": "",
            "tax_preference": "Non-Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "7966565",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Bihar",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "emp_id": None,
        "est_id": None,
        "item_id": None,
        "tcs_id": None,
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None
    },
    {
        "invoice_id": "fca4bb4f-5fe8-4de1-9807-4ce6234e8842",
        "invoice_items": [],
        "created_id": "None",
        "created_date": "2022-03-03T17:31:56.956948+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-03T17:31:56.956948+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-03T17:31:56.956948+05:30",
        "supply_place": "Maharashtra",
        "invoice_ref_no": "None",
        "invoice_serial": "INV1234",
        "invoice_status": "Draft",
        "invoice_date": "2022-03-03",
        "is_invoice_generated": True,
        "payment_status": "unpaid",
        "amount_due": "5824.00",
        "amount_received": None,
        "order_no": "",
        "due_date": "2022-03-18",
        "delivery_method": "None",
        "term_name": "cash on delivery",
        "no_of_days": 15,
        "project_name": "None",
        "subject": "",
        "total_quantity": None,
        "discount": "0.00",
        "entered_discount": "0.00",
        "amount": None,
        "cgst_total": "312.00",
        "sgst_total": "312.00",
        "igst_total": "0.00",
        "sub_total": "5200.00",
        "shipping_charges": "0.00",
        "shipping_tax_rate": 0,
        "shipping_tax_name": None,
        "entered_shipping_charges": "0.00",
        "adjustment": None,
        "tcs_amount": "0.00",
        "total": "5824.00",
        "total_gst": None,
        "payment_mode": "Cash",
        "deposit_to": None,
        "payment_received": False,
        "round_off": None,
        "tax": "None",
        "grand_total": None,
        "customer_note": "",
        "terms_condition": "",
        "attach_file": None,
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "is_converted": False,
        "TermsRefFullName": "None",
        "TermsRefListID": "None",
        "so_id": None,
        "customer_id": {
            "customer_id": "98a1bbda-9514-44f9-8c02-e49965fbb606",
            "created_id": "None",
            "created_date": "2022-03-03T12:21:22.782469+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:21:22.782469+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:21:22.782469+05:30",
            "salutation": "Mr.",
            "customer_name": "GAYATRI GANGADHAR CHAME",
            "customer_mobile": "09822607468",
            "company_name": "Coderize twchnology pvt ltd",
            "customer_display_name": "gayatri",
            "print_as_check_as": False,
            "customer_contact": "09822607468",
            "customer_email": "gayatrireddy800@gmail.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "nothing",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Consumer",
            "gstin_number": "",
            "tax_preference": "Non-Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "7966565",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Bihar",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "emp_id": None,
        "est_id": None,
        "item_id": None,
        "tcs_id": None,
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None
    }]
    

    a = invoice_data(example_Response)
  #  print(a)



from company.models import Company
import base64
def generate_invoice_pdf(data,output_path):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'])
    html = render(None, "core/invoice.html", data)
    return html
    # return None