from templates.img_conversion import image_url_to_base64
from django.shortcuts import render
import datetime

def so_data(so_response):
    so_response = so_response[0]
    so_response_fdasafd=[
    {
        "so_id": "62974a27-9335-4548-8b2a-7459c5761640",
        "so_items": [
            {
                "so_id": "62974a27-9335-4548-8b2a-7459c5761640",
                "soitem_id": "315687ff-adfd-40ab-8930-f7c220d80d02",
                "item_name": "Test Item 2",
                "amount": "1500.00",
                "quantity": "1.00",
                "rate": "1500.00",
                "tax_name": None,
                "taxamount": None,
                "cgst_amount": "0.00",
                "sgst_amount": "0.00",
                "igst_amount": "0.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "total_in_words":"",
        "created_id": "None",
        "created_date": "2022-03-06T12:05:33.869510+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-06T12:05:33.869510+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-06T12:05:33.869510+05:30",
        "customer_name": "None",
        "supply_place": "Delhi",
        "so_ref_no": "89",
        "so_serial": "5555",
        "so_status": "Save and Send",
        "is_so_generated": True,
        "so_date": "2022-03-06",
        "expiry_date": None,
        "expected_shipment_date": "2022-03-23",
        "delivery_method": "None",
        "term_name": "cash on delivery",
        "no_of_days": "15.00",
        "so_delete": "None",
        "project_name": "None",
        "subject": "None",
        "round_off": 0,
        "tax": "None",
        "tcs": "None",
        "total": "3400.00",
        "total_gst": "0.00",
        "sub_total": "1500.00",
        "shipping_charges": "2000.00",
        "shipping_tax_rate": 0,
        "shipping_tax_name": None,
        "entered_shipping_charges": "2000.00",
        "total_quantity": None,
        "discount": "100.00",
        "entered_discount": "100.00",
        "customer_note": None,
        "terms_condition": None,
        "attach_file": None,
        "est_status": "None",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "is_converted": False,
        "TxnID": "None",
        "ClassRefListID": "None",
        "CustomerMsgRefListID": "None",
        "CustomerRefListID": "None",
        "CustomerSalesTaxCodeRefListID": "None",
        "ItemSalesTaxRefListID": "None",
        "SalesRepRefListID": "None",
        "ShipMethodRefListID": "None",
        "TemplateRefListID": "None",
        "TermsRefListID": "None",
        "invoice_id": None,
        "emp_id": None,
        "customer_id": {
            "customer_id": "27c60af3-975a-42d5-8ff1-c010f1135459",
            "created_id": "None",
            "created_date": "2022-03-05T16:59:04.821344+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-05T16:59:04.821344+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-05T16:59:04.821344+05:30",
            "salutation": None,
            "customer_name": "Test Customer Master Transactions",
            "customer_mobile": "8090708050",
            "company_name": "",
            "customer_display_name": "Test Customer Master Transactions",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "example@email.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "est_id": None,
        "item_id": None,
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None
    }
]
    contents={

        "company_name":so_response['company_id']['company_name'],
        "address":so_response['company_id']['address'],
        "city":so_response['company_id']['city'],
        "gst_in":so_response['company_id']['gstin'],
        "so_serial":so_response['so_serial'],
        "so_date":datetime.datetime.strptime(so_response['so_date'], "%Y-%m-%d").date(),
        "expected_shipment_date":so_response['expected_shipment_date'],
        "place_of_supply":so_response['supply_place'],
        "delivery_method":so_response['delivery_method'],
        "sub_total":so_response['sub_total'],
        "discount":so_response['discount'],
#        "total_in_words":so_response['total_in_words'],
        "cgst_0":'',
        "itemdescription":'',
        "sgst0_0":'',
        "cgst25_25":so_response['cgst_total'],
        "igst_total":so_response['igst_total'],
        "tcs":so_response['tcs'],
        "cgst6_6":'',
        "sgst6_6":'',
        "cgst9_9":'',
        "sgst9_9":so_response['sgst_total'],
        "customer_note":so_response['customer_note'],
        "shipping_charges":so_response['shipping_charges'],
        "total":so_response['total'],
        "credit_remaining":'',
        'so_items': [dict(a) for a in so_response['so_items']],
        "customer_name":so_response['customer_id']['customer_name'],
        #"item_serial":invoice_response['invoice_items'][0]['item_serial'],
        "item_description":so_response['so_items'][0]['item_name'],
        #"hsn_sac":invoice_response['invoice_items'][0]['hsn_sac'],
        
    }
    print(contents)
    return contents


if __name__ == '__main__':
    so_Response=[
    {
        "so_id": "62974a27-9335-4548-8b2a-7459c5761640",
        "so_items": [
            {
                "so_id": "62974a27-9335-4548-8b2a-7459c5761640",
                "soitem_id": "315687ff-adfd-40ab-8930-f7c220d80d02",
                "item_name": "Test Item 2",
                "amount": "1500.00",
                "quantity": "1.00",
                "rate": "1500.00",
                "tax_name": None,
                "taxamount": None,
                "cgst_amount": "0.00",
                "sgst_amount": "0.00",
                "igst_amount": "0.00"
            }
        ],
        "cgst_total": "0.00",
        "sgst_total": "0.00",
        "igst_total": "0.00",
        "created_id": "None",
        "created_date": "2022-03-06T12:05:33.869510+05:30",
        "modified_id": "None",
        "modified_date": "2022-03-06T12:05:33.869510+05:30",
        "deleted_id": "None",
        "deleted_date": "2022-03-06T12:05:33.869510+05:30",
        "customer_name": "None",
        "supply_place": "Delhi",
        "so_ref_no": "89",
        "so_serial": "5555",
        "so_status": "Save and Send",
        "is_so_generated": True,
        "so_date": "2022-03-06",
        "expiry_date": None,
        "expected_shipment_date": "2022-03-23",
        "delivery_method": "None",
        "term_name": "cash on delivery",
        "no_of_days": "15.00",
        "so_delete": "None",
        "project_name": "None",
        "subject": "None",
        "round_off": 0,
        "tax": "None",
        "tcs": "None",
        "total": "3400.00",
        "total_gst": "0.00",
        "sub_total": "1500.00",
        "shipping_charges": "2000.00",
        "shipping_tax_rate": 0,
        "shipping_tax_name": None,
        "entered_shipping_charges": "2000.00",
        "total_quantity": None,
        "discount": "100.00",
        "entered_discount": "100.00",
        "customer_note": None,
        "terms_condition": None,
        "attach_file": None,
        "est_status": "None",
        "convt_type": "None",
        "convt_id": "None",
        "convt_serial": "None",
        "convt_ref_no": "None",
        "is_converted": False,
        "TxnID": "None",
        "ClassRefListID": "None",
        "CustomerMsgRefListID": "None",
        "CustomerRefListID": "None",
        "CustomerSalesTaxCodeRefListID": "None",
        "ItemSalesTaxRefListID": "None",
        "SalesRepRefListID": "None",
        "ShipMethodRefListID": "None",
        "TemplateRefListID": "None",
        "TermsRefListID": "None",
        "invoice_id": None,
        "emp_id": None,
        "customer_id": {
            "customer_id": "27c60af3-975a-42d5-8ff1-c010f1135459",
            "created_id": "None",
            "created_date": "2022-03-05T16:59:04.821344+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-05T16:59:04.821344+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-05T16:59:04.821344+05:30",
            "salutation": None,
            "customer_name": "Test Customer Master Transactions",
            "customer_mobile": "8090708050",
            "company_name": "",
            "customer_display_name": "Test Customer Master Transactions",
            "print_as_check_as": False,
            "customer_contact": "",
            "customer_email": "example@email.com",
            "customer_type": "Business",
            "customer_designation": "",
            "customer_department": "",
            "exemption_reason": "",
            "customerRefListId": "None",
            "customerTypeRefListId": "None",
            "customerTypeReffullName": "None",
            "is_subcustomer": False,
            "parent_customer": "None",
            "enable_portal": True,
            "company_display_name": "None",
            "company_email": "None",
            "company_number": "None",
            "website": "",
            "opening_balance": None,
            "currency": "None",
            "set_credit_limit": "0.00",
            "gst_treatment": "Unregistered Business",
            "gstin_number": "",
            "tax_preference": "Taxable",
            "cin_number": "None",
            "trn_number": "None",
            "vat_number": "None",
            "pan_number": "",
            "b_attention": "",
            "bill_address1": "",
            "bill_address2": "",
            "bill_address_city": "",
            "bill_address_state": "",
            "bill_address_postal_code": 0,
            "bill_address_country": "",
            "bill_contact_number": "",
            "bill_fax_number": "",
            "s_attention": "",
            "ship_address1": "",
            "ship_address2": "",
            "ship_address_city": "",
            "ship_address_state": "",
            "ship_address_postal_code": 0,
            "ship_address_country": "",
            "ship_contact_number": "",
            "ship_fax_number": "",
            "supply_place": "Maharashtra",
            "contact_salutation": None,
            "contact_name": "",
            "contact_phone": "",
            "contact_mobile": "",
            "contact_email": "",
            "contact_designation": "",
            "contact_department": "",
            "remarks": "",
            "term_name": "",
            "no_of_days": 0,
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "branch_id": None
        },
        "est_id": None,
        "item_id": None,
        "company_id": {
            "company_id": "ad7a4383-9389-436c-a38b-5b2a62c817bb",
            "created_id": "None",
            "created_date": "2022-03-03T12:15:37.699309+05:30",
            "modified_id": "None",
            "modified_date": "2022-03-03T12:15:37.699309+05:30",
            "deleted_id": "None",
            "deleted_date": "2022-03-03T12:15:37.699309+05:30",
            "trial_company": None,
            "company_name": "coderize",
            "alias_name": "abc",
            "address": "Balaji heights, near bank of maharashtra, Narhe",
            "locality": "pune",
            "landmark": "balaji nagar",
            "pincode": 411041,
            "city": "Pune",
            "state": "Maharashtra",
            "other": "",
            "is_primary": True,
            "primary_phone_number": "09822607468",
            "primary_mobile_number": "5655254554",
            "primary_alternate_number": "9875631489",
            "primary_email": "gayatrireddy800@gmail.com",
            "secondary_phone_number": "",
            "secondary_mobile_number": "",
            "secondary_alternate_number": "",
            "secondary_email": "gayatrireddy800@gmail.com",
            "website": "",
            "books_start_date": "2022-03-03",
            "method": "None",
            "company_type": "Government",
            "pan_number": "5648796445",
            "gstin": "5489863266",
            "cin": "269655663",
            "other_registration_number": "it",
            "password": "584587587",
            "security_control": "False",
            "audit_feature": "True",
            "logo_image": "/media/None",
            "report_basis": "None",
            "company_edit_id": "None",
            "tax_edit_id": "None",
            "separate_payment_address": "False",
            "address_receive_payment": "None"
        },
        "branch_id": None
    }
]
    a = so_data(so_Response)
    print(a)

def generate_so_pdf(data):
    data['company_id']['logo_image'] = image_url_to_base64(data['company_id']['logo_image'] )
    html =  render(None, "core/so.html",data)
    return html