# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2250, verbose_name='full_name')),
                ('email', models.EmailField(max_length=22250, unique=True, verbose_name='email')),
                ('mobile_no', models.CharField(max_length=2250, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_activate', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, default='null', max_length=2250, null=True)),
                ('forgot_pass_code', models.CharField(blank=True, default='null', max_length=2250, null=True)),
                ('forgot_pass_time', models.DateTimeField(null=True)),
                ('last_password_change', models.DateTimeField(null=True)),
                ('forgot_password_is_active', models.BooleanField(default=False)),
                ('forgot_password_reset_secret_key', models.CharField(max_length=16, null=True)),
                ('forgot_password_reset_secret_time', models.DateTimeField(null=True)),
                ('is_on_trial', models.CharField(blank=True, default='null', max_length=10, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('trial_expiry_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('industry', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('gender', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('district', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('username', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('department', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('designation', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='')),
                ('provider', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('address', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('pincode', models.BigIntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('state', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('created_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('deleted_date', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=250)),
                ('password', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField(default='', max_length=100)),
                ('device_type', models.TextField(default='', max_length=100)),
                ('browser', models.CharField(default='', max_length=100)),
                ('browser_family', models.CharField(default='', max_length=100)),
                ('browser_version', models.CharField(default='', max_length=100)),
                ('os_type', models.CharField(default='', max_length=100)),
                ('os_family', models.CharField(default='', max_length=100)),
                ('os_version', models.CharField(default='', max_length=100)),
                ('ip', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('subscriber_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('mobile_no', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='null', max_length=250, null=True)),
                ('username', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('created_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('deleted_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscribe',
                'db_table': 'Subscribe',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('mobile_no', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='null', max_length=250, null=True)),
                ('dev_comment', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('username', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('created_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('deleted_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Company_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
