# Generated by Django 4.0.1 on 2023-11-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Free Plan', max_length=50)),
                ('validity', models.IntegerField(default=0)),
                ('billing_cycle', models.CharField(blank=True, choices=[('MONTHLY', 'MONTHLY'), ('3 MONTHS', '3 MONTHS'), ('6 MONTHS', '6 MONTHS'), ('YEARLY', 'YEARLY')], max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='deleted_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='modified_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='username',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=200, null=True)),
                ('order_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('PENDING', 'PENDING')], default='PENDING', max_length=200)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(default='inr', max_length=4)),
                ('total_price', models.FloatField(default=0)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscribe_order', to='registration.plan')),
                ('subscribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.subscribe')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.plan')),
            ],
        ),
        migrations.AddField(
            model_name='subscribe',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscribe', to='registration.plan'),
        ),
    ]
