# Generated by Django 4.0.1 on 2024-01-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_options'),
        ('registration', '0003_remove_subscribe_user_subscribe_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='company_id',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='company_id',
            field=models.ManyToManyField(blank=True, related_name='subscribe_companies', to='company.Company'),
        ),
    ]
