# Generated by Django 4.0.1 on 2024-01-16 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_subscribe_company_id_subscribe_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
