# Generated by Django 4.0.1 on 2024-01-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_subscribe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='modified_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='modified_id',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
