# Generated by Django 4.0.1 on 2024-01-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_subscribe_created_date_subscribe_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'subscribe'},
        ),
        migrations.AlterField(
            model_name='service',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_services', to='registration.plan'),
        ),
    ]
