# Generated by Django 4.0.1 on 2024-02-17 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_subscribe_options_alter_service_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
