# Generated by Django 4.0.1 on 2024-03-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_subscribe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='count_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
