# Generated by Django 4.0.1 on 2024-03-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_servicecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCount',
        ),
    ]
