# Generated by Django 4.0.1 on 2024-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_subscriptionorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
