# Generated by Django 4.0.1 on 2024-03-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_subscriptionorder_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionorder',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='subscribe',
        ),
    ]
