# Generated by Django 4.0.1 on 2024-04-16 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_plan_user_requestcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('user_id', models.PositiveIntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plan_id', models.PositiveIntegerField(default=0)),
                ('customer_remaining', models.PositiveIntegerField(default=0)),
                ('vendor_remaining', models.PositiveIntegerField(default=0)),
                ('invoice_remaining', models.PositiveIntegerField(default=0)),
                ('bill_remaining', models.PositiveIntegerField(default=0)),
                ('bank_remaining', models.PositiveIntegerField(default=0)),
                ('cn_remaining', models.PositiveIntegerField(default=0)),
                ('dc_remaining', models.PositiveIntegerField(default=0)),
                ('dn_remaining', models.PositiveIntegerField(default=0)),
                ('doc_remaining', models.PositiveIntegerField(default=0)),
                ('po_remaining', models.PositiveIntegerField(default=0)),
                ('estimates_remaining', models.PositiveIntegerField(default=0)),
                ('expense_remaining', models.PositiveIntegerField(default=0)),
                ('journal_remaining', models.PositiveIntegerField(default=0)),
                ('pm_remaining', models.PositiveIntegerField(default=0)),
                ('pr_remaining', models.PositiveIntegerField(default=0)),
                ('so_remaining', models.PositiveIntegerField(default=0)),
                ('statement_remaining', models.PositiveIntegerField(default=0)),
                ('items', models.BooleanField(default=False)),
                ('coas', models.BooleanField(default=False)),
                ('profit_loss', models.BooleanField(default=False)),
                ('balance_sheet', models.BooleanField(default=False)),
                ('invoice_details', models.BooleanField(default=False)),
                ('pr_details', models.BooleanField(default=False)),
                ('bill_details', models.BooleanField(default=False)),
                ('pm_details', models.BooleanField(default=False)),
                ('sales_gst', models.BooleanField(default=False)),
                ('purchase_gst', models.BooleanField(default=False)),
                ('gstr_3b', models.BooleanField(default=False)),
                ('gstr_2b', models.BooleanField(default=False)),
                ('gstr_2a', models.BooleanField(default=False)),
                ('inventory', models.BooleanField(default=False)),
                ('inventory_valuation', models.BooleanField(default=False)),
                ('day_book', models.BooleanField(default=False)),
                ('cash_book', models.BooleanField(default=False)),
                ('bank_book', models.BooleanField(default=False)),
                ('webapp', models.BooleanField(default=False)),
                ('backup', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'feature',
                'managed': False,
            },
        ),
    ]
