# Generated by Django 4.0.1 on 2024-04-25 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_user_role_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
