# Generated by Django 4.0.1 on 2024-04-30 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_user_sub_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
