# Generated by Django 4.0.1 on 2024-04-30 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_useraccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_users',
            field=models.ManyToManyField(blank=True, related_name='user_sub', to=settings.AUTH_USER_MODEL),
        ),
    ]
