# Generated by Django 4.0.1 on 2024-05-22 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_user_sub_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
