# Generated by Django 4.0.1 on 2024-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_branch_options'),
        ('registration', '0022_alter_user_sub_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='branches',
            field=models.ManyToManyField(blank=True, to='company.Branch'),
        ),
    ]
