# Generated by Django 4.0.1 on 2024-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_useraccess_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='company_branches',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
