# Generated by Django 4.0.1 on 2024-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_plan_company_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='tally',
            field=models.BooleanField(default=False),
        ),
    ]
