# Generated by Django 4.0.1 on 2024-08-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_plan_tally_useraccess_tally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='tally',
            field=models.BooleanField(default=True),
        ),
    ]
