# Generated by Django 4.0.1 on 2024-09-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_alter_useraccess_tally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='coas',
            field=models.BooleanField(default=True),
        ),
    ]
