# Generated by Django 4.0.1 on 2024-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_alter_plan_coas'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='filing',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='filing',
            field=models.BooleanField(default=False),
        ),
    ]
