# Generated by Django 4.0.1 on 2024-10-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_plan_filing_useraccess_filing'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='full_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='full_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
