# Generated by Django 4.0.1 on 2024-10-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_plan_full_inventory_useraccess_full_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='audit',
            field=models.BooleanField(default=False),
        ),
    ]
