# Generated by Django 4.0.1 on 2024-10-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_plan_audit_useraccess_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.BooleanField(default=True)),
                ('inventory', models.BooleanField(default=True)),
                ('full_inventory', models.BooleanField(default=False)),
                ('company', models.BooleanField(default=True)),
                ('customer', models.BooleanField(default=True)),
                ('estimate', models.BooleanField(default=True)),
                ('so', models.BooleanField(default=True)),
                ('dc', models.BooleanField(default=True)),
                ('invoice', models.BooleanField(default=True)),
                ('pr', models.BooleanField(default=True)),
                ('cn', models.BooleanField(default=True)),
                ('vendor', models.BooleanField(default=True)),
                ('expense', models.BooleanField(default=True)),
                ('po', models.BooleanField(default=True)),
                ('bill', models.BooleanField(default=True)),
                ('pm', models.BooleanField(default=True)),
                ('dn', models.BooleanField(default=True)),
                ('journal', models.BooleanField(default=True)),
                ('coa', models.BooleanField(default=True)),
                ('reconcilation', models.BooleanField(default=True)),
                ('bank', models.BooleanField(default=True)),
                ('ocr', models.BooleanField(default=True)),
                ('profit_loss', models.BooleanField(default=True)),
                ('balance', models.BooleanField(default=True)),
                ('invoice_report', models.BooleanField(default=True)),
                ('pr_report', models.BooleanField(default=True)),
                ('bill_report', models.BooleanField(default=True)),
                ('pm_report', models.BooleanField(default=True)),
                ('sales_gst_report', models.BooleanField(default=True)),
                ('purchase_gst_report', models.BooleanField(default=True)),
                ('gstr_3b_report', models.BooleanField(default=True)),
                ('gstr_2b_report', models.BooleanField(default=True)),
                ('gstr_2a_report', models.BooleanField(default=True)),
                ('inventory_report', models.BooleanField(default=True)),
                ('inventory_valuation_report', models.BooleanField(default=True)),
                ('day_book', models.BooleanField(default=True)),
                ('cash_book', models.BooleanField(default=True)),
                ('bank_book', models.BooleanField(default=True)),
                ('audit', models.BooleanField(default=False)),
                ('tally', models.BooleanField(default=True)),
                ('filing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_access_view',
                'managed': False,
            },
        ),
    ]
