# Generated by Django 4.0.1 on 2024-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_audit_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='sub_module',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
