# Generated by Django 4.0.1 on 2024-10-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_audit_sub_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
