# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('city', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='null', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('pincode', models.BigIntegerField(blank=True, default='null', null=True)),
                ('primary_contact', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('state', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('transaction_series', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('website', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, default='null', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('trial_company', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('alias_name', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('locality', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('pincode', models.BigIntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('other', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=True, null=True)),
                ('primary_phone_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('primary_mobile_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('primary_alternate_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('primary_email', models.EmailField(blank=True, default='null', max_length=50, null=True)),
                ('secondary_phone_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('secondary_mobile_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('secondary_alternate_number', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('secondary_email', models.EmailField(blank=True, default='null', max_length=50, null=True)),
                ('website', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('books_start_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('company_type', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('gstin', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('cin', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('other_registration_number', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('password', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('security_control', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('audit_feature', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('logo_image', models.ImageField(blank=True, default='null', null=True, upload_to=None)),
                ('report_basis', models.CharField(blank=True, default='null', max_length=80, null=True)),
                ('company_edit_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('tax_edit_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('separate_payment_address', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('address_receive_payment', models.TextField(blank=True, default='null', null=True)),
            ],
            options={
                'verbose_name_plural': 'company',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('fy_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('financial_start_date', models.DateField(blank=True, null=True)),
                ('financial_end_date', models.DateField(blank=True, null=True)),
                ('is_year_started', models.BooleanField(default=False, null=True)),
                ('is_year_closed', models.BooleanField(default=False, null=True)),
                ('Financial_year_close', models.BooleanField(default=False, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Financial Year',
            },
        ),
        migrations.CreateModel(
            name='Company_Year',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comp_yearid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
