# Generated by Django 4.0.1 on 2023-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_copied_coa',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_new_company',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
