# Generated by Django 4.0.1 on 2023-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_copied_coa_company_is_new_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='financial_year',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
