# Generated by Django 4.0.1 on 2023-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_sequence',
            field=models.BigIntegerField(default=1),
        ),
    ]
