# Generated by Django 4.0.1 on 2024-01-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_invoice_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='logo/'),
        ),
    ]
