# Generated by Django 4.0.1 on 2024-01-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_logo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'company'},
        ),
    ]
