# Generated by Django 4.0.1 on 2024-05-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
