# Generated by Django 4.0.1 on 2024-05-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_currency_company_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='inr', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
