# Generated by Django 4.0.1 on 2024-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_currency_alter_company_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
