# Generated by Django 4.0.1 on 2024-06-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_branches', to='company.company'),
        ),
    ]
