# Generated by Django 4.0.1 on 2024-06-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_branch_company_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'branch'},
        ),
    ]
