# Generated by Django 4.0.1 on 2024-06-28 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_branch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
