# Generated by Django 4.0.1 on 2024-06-28 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_financialyear_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_branches', to='company.company'),
        ),
    ]
