# Generated by Django 4.0.1 on 2024-06-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_branch_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='main_branch',
            field=models.BooleanField(default=False),
        ),
    ]
