# Generated by Django 4.0.1 on 2024-08-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_branch_main_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
    ]
