# Generated by Django 4.0.1 on 2024-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_branch_ext_id_branch_ext_type_company_ext_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_year',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
