# Generated by Django 4.0.1 on 2024-09-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ext_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='gstin',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='website',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
