# Generated by Django 4.0.1 on 2024-10-04 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_company_created_by_company_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaults',
            name='id',
        ),
        migrations.AddField(
            model_name='defaults',
            name='def_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
