# Generated by Django 4.0.1 on 2024-11-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_remove_defaults_id_defaults_def_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
