# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_head', models.CharField(blank=True, max_length=50, null=True)),
                ('account_subhead', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'BaseCOA',
            },
        ),
        migrations.CreateModel(
            name='COA',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('coa_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_head', models.CharField(blank=True, max_length=50, null=True)),
                ('account_subhead', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('add_to_watchlist_on_my_dashboard', models.BooleanField(blank=True, null=True)),
                ('mark_this_is_sub_account', models.BooleanField(blank=True, null=True)),
                ('is_child_allowed', models.BooleanField(blank=True, null=True)),
                ('parent_account', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('ListID', models.CharField(blank=True, max_length=50, null=True)),
                ('EditSequence', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('FullName', models.CharField(blank=True, max_length=50, null=True)),
                ('IsActive', models.BooleanField(blank=True, default=False, null=True)),
                ('ParentRefListID', models.CharField(blank=True, max_length=50, null=True)),
                ('ParentRefFullName', models.CharField(blank=True, max_length=50, null=True)),
                ('Sublevel', models.CharField(blank=True, max_length=50, null=True)),
                ('SpecialAccountType', models.CharField(blank=True, max_length=50, null=True)),
                ('IsTaxAccount', models.BooleanField(blank=True, default=False, null=True)),
                ('AccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('BankNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Balance', models.FloatField(blank=True, default=0, null=True)),
                ('TotalBalance', models.FloatField(blank=True, default=0, null=True)),
                ('OpenBalance', models.FloatField(blank=True, default=0, null=True)),
                ('OpenBalanceDate', models.DateField(blank=True, null=True)),
                ('SalesTaxCodeRefListID', models.CharField(blank=True, max_length=50, null=True)),
                ('SalesTaxCodeRefFullName', models.CharField(blank=True, max_length=50, null=True)),
                ('TaxCodeRefListID', models.CharField(blank=True, max_length=50, null=True)),
                ('TaxCodeRefFullName', models.CharField(blank=True, max_length=50, null=True)),
                ('TaxLineInfoRetTaxLineID', models.CharField(blank=True, max_length=50, null=True)),
                ('TaxLineInfoRetTaxLineName', models.CharField(blank=True, max_length=50, null=True)),
                ('CashFlowClassification', models.CharField(blank=True, max_length=50, null=True)),
                ('CurrencyRefListID', models.CharField(blank=True, max_length=50, null=True)),
                ('CurrencyRefFullName', models.CharField(blank=True, max_length=50, null=True)),
                ('isdefault', models.BooleanField(blank=True, default=False, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
            ],
            options={
                'verbose_name_plural': 'Chart Of Account',
                'db_table': 'coa',
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ob_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('available_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('migration_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opbalance', to='coa.coa')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
            ],
            options={
                'verbose_name_plural': 'Opening Balance',
            },
        ),
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ah_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_head', models.CharField(blank=True, max_length=50, null=True)),
                ('account_subhead', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch')),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coa.coa')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
            ],
            options={
                'verbose_name_plural': 'Account Head',
            },
        ),
    ]
