# Generated by Django 4.0.1 on 2023-11-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coa',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Chart Of Account'},
        ),
    ]
