# Generated by Django 4.0.1 on 2024-02-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_alter_coa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coa',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Chart Of Account'},
        ),
        migrations.AlterModelOptions(
            name='openingbalance',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Opening Balance'},
        ),
        migrations.AddField(
            model_name='coa',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coa',
            name='open_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
