# Generated by Django 4.0.1 on 2024-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0004_transactiondetail_alter_coa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coa',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coa',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=50),
        ),
    ]
