# Generated by Django 4.0.1 on 2024-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0005_coa_ext_id_coa_ext_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthead',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecoa',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='coa',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
