# Generated by Django 4.0.1 on 2024-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0006_alter_accounthead_modified_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetailCV',
            fields=[
                ('L1detail_id', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('vendor_id', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_head', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_subhead', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('trans_status', models.CharField(blank=True, default='null', max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_type', models.CharField(blank=True, default='null', max_length=100, null=True)),
            ],
            options={
                'db_table': 'transaction_detail_cv',
                'managed': False,
            },
        ),
    ]
