# Generated by Django 4.0.1 on 2024-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_alter_coa_accountnumber_alter_coa_banknumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecoa',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coa',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
