# Generated by Django 4.0.1 on 2024-11-14 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_remove_defaults_id_defaults_def_id'),
        ('coa', '0009_basecoa_system_coa_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tax_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of the tax, e.g., VAT, GST', max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage, e.g., 5.00 for 5%', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Optional description for the tax', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this tax is active')),
                ('system', models.BooleanField(default=0)),
                ('account_type', models.CharField(default='Liabilities', help_text='account type', max_length=255)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_taxes', to='company.branch')),
                ('coa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_taxes', to='coa.coa')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_taxes', to='company.company')),
                ('company_yearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
