# Generated by Django 4.0.1 on 2024-11-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0010_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
