# Generated by Django 4.0.1 on 2024-11-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0012_tax_ext_id_tax_ext_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='sub_section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('GST', 'GST')], max_length=200, null=True),
        ),
    ]
