# Generated by Django 4.0.1 on 2024-11-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0013_tax_sub_section_alter_tax_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='coa_id_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_1_taxes', to='coa.coa'),
        ),
    ]
