# Generated by Django 4.0.1 on 2024-11-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0014_tax_coa_id_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='rate_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate as a percentage, e.g., 5.00 for 5%', max_digits=5),
        ),
    ]
