# Generated by Django 4.0.1 on 2024-11-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0015_tax_rate_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='rate_1',
        ),
    ]
