# Generated by Django 4.0.1 on 2024-11-29 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0016_remove_tax_rate_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceView',
            fields=[
                ('coa_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_head', models.CharField(blank=True, max_length=50, null=True)),
                ('account_subhead', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'opening_balance_view',
                'managed': False,
            },
        ),
    ]
