# Generated by Django 4.0.1 on 2024-03-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.BinaryField()),
                ('error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('time_required', models.FloatField(default=0)),
                ('resolution', models.CharField(default='0,0', max_length=10)),
                ('pages_count', models.SmallIntegerField(default=0)),
                ('created', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('document_type', models.CharField(blank=True, choices=[('INVOICE', 'INVOICE'), ('BILL', 'BILL')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('IDLE', 'IDLE'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='IDLE', max_length=100)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
