# Generated by Django 4.0.1 on 2024-04-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_remove_document_id_document_doc_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_date']},
        ),
    ]
