# Generated by Django 4.0.1 on 2024-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='branch_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
