# Generated by Django 4.0.1 on 2024-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_document_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
