# Generated by Django 4.0.1 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('purchase', '0001_initial'),
        ('accounting', '0001_initial'),
        ('salescustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltransaction',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salescustomer.salescustomer'),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='mj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_transactions', to='accounting.manualjournal'),
        ),
        migrations.AddField(
            model_name='journaltransaction',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='bulkupdate',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='bulkupdate',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='bulkupdate',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
        migrations.AddField(
            model_name='budget',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company_yearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company_year'),
        ),
    ]
