# Generated by Django 4.0.1 on 2024-09-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_budget_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltransaction',
            name='account',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journaltransaction',
            name='contact',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journaltransaction',
            name='des',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journaltransaction',
            name='transaction_type',
            field=models.CharField(default='Journal', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='ext_type',
            field=models.CharField(choices=[('TALLY', 'TALLY')], default='TALLY', max_length=100),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='journal_ref_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='journal_serial_no',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='journal_status',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='journal_type',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
