# Generated by Django 4.0.1 on 2024-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journaltransaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltransaction',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualjournal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
