# Generated by Django 4.0.1 on 2024-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journaltransaction_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='created_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manualjournal',
            name='modified_by',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
